'use strict';
const crypto=require('node:crypto');
const fail=(code,status=409)=>{throw Object.assign(Error(code),{status})};
const integer=(n,min=0,max=100000000)=>{n=Number(n??0);if(!Number.isSafeInteger(n)||n<min||n>max)fail('wallet-invalid-amount',400);return n};
const id=value=>{if(typeof value!=='string'||!/^[a-zA-Z0-9_-]{1,100}$/.test(value))fail('wallet-invalid-request',400);return value};
const day=now=>new Date(now+9*3600000).toISOString().slice(0,10);
const PRODUCTS={character_slot_1:{cost:100,field:'characterSingleSlots'},town_slot_1:{cost:190,field:'townSlotPacks'},storage_50mb:{cost:290,field:'storage50'}};
function balance(ent={}){const paid=integer(ent.diamondPaid,-100000000),bonus=integer(ent.diamondBonus);return {paid,bonus,total:Math.max(0,paid+bonus),frozen:paid<0}}
function spend(ent,productId){const product=PRODUCTS[productId];if(!product)fail('wallet-invalid-product',400);const b=balance(ent);if(b.frozen)fail('wallet-refund-pending');if(b.total<product.cost)fail('wallet-insufficient');if(product.field==='storage50'&&ent.storage50)fail('wallet-already-owned');const bonus=Math.min(product.cost,b.bonus);return {...ent,diamondPaid:b.paid-(product.cost-bonus),diamondBonus:b.bonus-bonus,[product.field]:product.field==='storage50'?true:integer(ent[product.field])+1}}
function createWallet({db,clock=Date.now,random=()=>crypto.randomUUID(),sandbox=false}){
 const entitlementField=sandbox?'appleSandboxEntitlements':'entitlements';
 const user=uid=>db.collection(sandbox?'appleSandboxAccounts':'users').doc(uid),settings=()=>db.collection('economySettings').doc('live').get();
 async function policy(){const p=(await settings()).data()||{};return {enabled:p.enabled===true,adsEnabled:!sandbox&&p.adsEnabled===true,dailyReward:1,adReward:3,adDailyLimit:3,products:PRODUCTS,adUnits:p.adUnits||{},bannerUnits:p.bannerUnits||{}}}
 async function read(uid){const [u,p,d,events]=await Promise.all([user(uid).get(),policy(),user(uid).collection('diamondDays').doc(day(clock())).get(),db.collection('diamondEvents').where('active','==',true).limit(20).get()]);const value=d.data()||{};return {...balance(u.data()?.[entitlementField]),...p,storage50:!!u.data()?.[entitlementField]?.storage50,dailyClaimed:!!value.visit,adsRemaining:Math.max(0,p.adDailyLimit-(value.ads||0)),events:events.docs.filter(e=>e.data().startAt<=clock()&&e.data().endAt>clock()).map(e=>({id:e.id,title:String(e.data().title||'Event'),amount:integer(e.data().amount,1,10000)}))}}
 async function purchase(uid,input){const requestId=id(input.requestId),productId=id(input.productId),p=await policy();if(!p.enabled)fail('wallet-unavailable',503);const root=user(uid),receipt=root.collection('diamondTransactions').doc('buy-'+requestId);return db.runTransaction(async tx=>{const [prior,u,tombstone]=await Promise.all([tx.get(receipt),tx.get(root),tx.get(db.collection('deletedAccounts').doc(uid))]);if(tombstone.exists)fail('wallet-account-deleted',403);if(prior.exists){if(prior.data().productId!==productId)fail('wallet-request-reused');return {alreadyApplied:true,...balance(u.data()?.[entitlementField])}}const old=u.data()?.[entitlementField]||{},next=spend(old,productId);tx.set(root,{[entitlementField]:next},{merge:true});tx.create(receipt,{kind:'purchase',productId,cost:PRODUCTS[productId].cost,paid:balance(old).paid-next.diamondPaid,bonus:balance(old).bonus-next.diamondBonus,createdAt:clock()});return balance(next)})}
 async function claim(uid,input={}){if(sandbox)fail('wallet-test-purchase-only');const p=await policy();if(!p.enabled)fail('wallet-unavailable',503);const now=clock(),eventId=input.eventId?id(input.eventId):'',root=user(uid),daily=root.collection('diamondDays').doc(day(now)),receipt=root.collection('diamondTransactions').doc(eventId?'event-'+eventId:'visit-'+day(now));return db.runTransaction(async tx=>{const refs=[receipt,root,daily,db.collection('deletedAccounts').doc(uid)];if(eventId)refs.push(db.collection('diamondEvents').doc(eventId));const [prior,u,d,tombstone,event]=await Promise.all(refs.map(r=>tx.get(r)));if(tombstone.exists)fail('wallet-account-deleted',403);if(prior.exists)return {alreadyApplied:true};let amount=p.dailyReward;if(eventId){const e=event.data();if(!e?.active||e.startAt>now||e.endAt<=now||e.eligibleUids&&!e.eligibleUids.includes(uid)||e.maxClaims&&Number(e.claims||0)>=e.maxClaims)fail('wallet-event-unavailable');amount=integer(e.amount,1,10000);tx.update(event.ref,{claims:integer(e.claims)+1})}else tx.set(daily,{...(d.data()||{}),visit:true},{merge:true});const ent=u.data()?.[entitlementField]||{};tx.set(root,{[entitlementField]:{...ent,diamondBonus:balance(ent).bonus+amount}},{merge:true});tx.create(receipt,{kind:eventId?'event':'visit',bonus:amount,createdAt:now});return {granted:amount}})}
 async function prepareAd(uid,input){const p=await policy(),adUnit=p.adUnits[input.platform];if(!p.enabled||!p.adsEnabled||!/^ca-app-pub-\d+\/\d+$/.test(adUnit||''))fail('ads-unavailable',503);const root=user(uid),now=clock(),daily=root.collection('diamondDays').doc(day(now)),ticketId=random();return db.runTransaction(async tx=>{const [d,u,tombstone]=await Promise.all([tx.get(daily),tx.get(root),tx.get(db.collection('deletedAccounts').doc(uid))]);if(tombstone.exists)fail('wallet-account-deleted',403);if(balance(u.data()?.[entitlementField]).frozen)fail('wallet-refund-pending');const value=d.data()||{};if(integer(value.ads)>=p.adDailyLimit)fail('ads-daily-limit');if(value.lastAdAt&&now-value.lastAdAt<60000)fail('ads-wait');tx.set(daily,{...value,lastAdAt:now},{merge:true});tx.create(db.collection('diamondAdTickets').doc(ticketId),{uid,adUnit,reward:p.adReward,day:day(now),dailyLimit:p.adDailyLimit,createdAt:now,expiresAt:now+3600000});return {ticketId,adUnit,reward:p.adReward}})}
 // Called only after the Google signature has been verified, never by an app reward event.
 async function rewardAd(data){const ticketId=id(data.custom_data),transactionId=id(data.transaction_id),ticket=db.collection('diamondAdTickets').doc(ticketId),receipt=db.collection('diamondAdReceipts').doc(transactionId);return db.runTransaction(async tx=>{const [t,prior]=await Promise.all([tx.get(ticket),tx.get(receipt)]);if(prior.exists){if(prior.data().ticketId!==ticketId)fail('ads-replay');return {alreadyApplied:true}}const v=t.data();if(!Number.isSafeInteger(Number(data.timestamp))||!v||v.used||v.expiresAt<clock()||v.createdAt-60000>Number(data.timestamp)||Number(data.timestamp)>v.expiresAt||v.uid!==data.user_id||![v.adUnit,v.adUnit.split('/').at(-1)].includes(data.ad_unit)||Number(data.reward_amount)!==v.reward||data.reward_item!=='diamond')fail('ads-invalid-reward',400);const root=user(v.uid),daily=root.collection('diamondDays').doc(v.day),[u,d,tombstone]=await Promise.all([tx.get(root),tx.get(daily),tx.get(db.collection('deletedAccounts').doc(v.uid))]);if(tombstone.exists)fail('wallet-account-deleted',403);const value=d.data()||{};if(integer(value.ads)>=v.dailyLimit)fail('ads-daily-limit');const ent=u.data()?.[entitlementField]||{};tx.set(root,{[entitlementField]:{...ent,diamondBonus:balance(ent).bonus+v.reward}},{merge:true});tx.set(daily,{...value,ads:integer(value.ads)+1},{merge:true});tx.update(ticket,{used:true,transactionId});tx.create(receipt,{ticketId,uid:v.uid,bonus:v.reward,createdAt:clock()});tx.create(root.collection('diamondTransactions').doc('ad-'+transactionId),{kind:'ad',bonus:v.reward,createdAt:clock()});return {granted:v.reward}})}
 return {read,purchase,claim,prepareAd,rewardAd};
}
module.exports={balance,spend,createWallet,PRODUCTS};
