const {randomBytes}=require('node:crypto'),engine=require('./mafia-engine');
const fail=(message,status=400)=>{throw Object.assign(Error(message),{status})};
const id=v=>{if(typeof v!=='string'||!v||v.length>180||/[\/\\\x00-\x1f]/.test(v))fail('game-invalid-input');return v};
const rows=s=>s.docs.map(d=>({...d.data(),id:d.id}));
module.exports=({db,clock=Date.now})=>{
 async function context(tx,uid,input){const root=db.collection('groups').doc(id(input.groupId));const [group,member]=await Promise.all([tx.get(root),tx.get(root.collection('members').doc(uid))]);if(!group.exists||!member.exists)fail('group-membership-required',403);return {root,group:group.data(),manager:group.data().ownerUid===uid||['owner','manager','operator'].includes(member.data().role)}}
 const parse=s=>{try{return JSON.parse(s||'{}')}catch{return {}}};
 function participant(r,delegated=false){const p=parse(r.profileJson);return {id:r.id,name:String(r.name||'').slice(0,60),ownerUid:r.ownerUid,delegated,speechStyle:p.speechStyle||'',personalityTypes:Array.isArray(p.personalityTypes)?p.personalityTypes.slice(0,8):[],traits:JSON.stringify([p.personalityTypes,p.personality,p.temperament,p.emotionalBaseline,p.angerResponse]).slice(0,1500),sleep:p.sleep||'23:00',alive:true}}
 function locations(group,homes){const places=(group.towns||[]).flatMap(t=>(t.places||[]).map(p=>({id:t.id+':'+p.id,name:String(p.name||p.type||'').slice(0,60)})));for(const h of homes){const layout=parse(h.layoutJson);for(const [key,room] of Object.entries(layout.rooms||{}))places.push({id:h.id+':'+key,name:String(h.name+' · '+(room.name||key)).slice(0,60)})}return places.filter(p=>p.name).slice(0,40)}
 async function gameAction(uid,input,fn){return db.runTransaction(async tx=>{const ctx=await context(tx,uid,input),ref=ctx.root.collection('games').doc(id(input.gameId)),snapshot=await tx.get(ref);if(!snapshot.exists)fail('game-missing',404);const game=snapshot.data(),residents=rows(await tx.get(ctx.root.collection('residents')));const current=new Set(residents.map(r=>r.id));game.players.forEach(p=>{if(!current.has(p.id))p.alive=false});engine.advance(game,clock());const result=await fn(tx,ctx,game,residents);tx.set(ref,game);if(game.status==='finished'&&!game.moodApplied){for(const p of game.players.filter(p=>current.has(p.id)))tx.update(ctx.root.collection('residents').doc(p.id),{gameMood:{value:(p.role===game.winner?6:-4)*(p.delegated?.5:1),until:game.finishedAt+10800000}});game.moodApplied=true;tx.set(ref,game)}return result||engine.view(game,uid)})}
 return {
  readGames:async(uid,input)=>db.runTransaction(async tx=>{const ctx=await context(tx,uid,input),[games,residents,homes,consent]=await Promise.all([tx.get(ctx.root.collection('games').orderBy('createdAt','desc').limit(20)),tx.get(ctx.root.collection('residents')),tx.get(ctx.root.collection('homes')),tx.get(ctx.root.collection('gameConsent').doc(uid))]);return {manager:ctx.manager,games:rows(games).map(g=>engine.view(g,uid)),characters:rows(residents).filter(r=>r.ownerUid===uid).map(r=>({id:r.id,name:r.name})),locations:locations(ctx.group,rows(homes)),consent:consent.data()?.characters||[]}}),
  setGameConsent:async(uid,input)=>db.runTransaction(async tx=>{const ctx=await context(tx,uid,input),residents=rows(await tx.get(ctx.root.collection('residents')));if(!Array.isArray(input.characters)||input.characters.length>100||input.characters.some(c=>!residents.some(r=>r.id===c&&r.ownerUid===uid)))fail('character-owner-required',403);tx.set(ctx.root.collection('gameConsent').doc(uid),{characters:[...new Set(input.characters)]});return {saved:true}}),
  createGame:async(uid,input)=>db.runTransaction(async tx=>{const ctx=await context(tx,uid,input);if(!ctx.manager)fail('manager-required',403);const [games,homes]=await Promise.all([tx.get(ctx.root.collection('games').where('status','in',['recruiting','playing'])),tx.get(ctx.root.collection('homes'))]);if(games.docs.length>=3)fail('game-limit');const valid=locations(ctx.group,rows(homes));if(!Array.isArray(input.locations)||input.locations.length<3||input.locations.length>8||new Set(input.locations).size!==input.locations.length||input.locations.some(p=>!valid.some(v=>v.id===p)))fail('game-locations');const capacity=Number(input.capacity),hours=Number(input.hours);if(!Number.isInteger(capacity)||capacity<4||capacity>10||![6,12,24].includes(hours))fail('game-invalid-input');const gameId=id(input.gameId),ref=ctx.root.collection('games').doc(gameId);if((await tx.get(ref)).exists)fail('game-exists',409);const game={id:gameId,type:'mafia',name:String(input.name||'Mafia').slice(0,60),hostUid:uid,status:'recruiting',createdAt:clock(),capacity,durationMs:hours*3600000,locations:input.locations.map(p=>valid.find(v=>v.id===p)),players:[],seed:randomBytes(16).toString('hex')};tx.create(ref,game);return engine.view(game,uid)}),
  joinGame:(uid,input)=>gameAction(uid,input,async(tx,ctx,g,residents)=>{if(g.status!=='recruiting')fail('game-already-started');const r=residents.find(r=>r.id===input.characterId&&r.ownerUid===uid);if(!r)fail('character-owner-required',403);if(g.players.some(p=>p.id===r.id))return;if(g.players.some(p=>p.ownerUid===uid&&!p.delegated))fail('game-one-character');if(g.players.length>=g.capacity)fail('game-full');g.players.push(participant(r))}),
  startGame:(uid,input)=>gameAction(uid,input,async(tx,ctx,g,residents)=>{if(!ctx.manager)fail('manager-required',403);if(g.status!=='recruiting')fail('game-already-started');const consents=rows(await tx.get(ctx.root.collection('gameConsent'))),allowed=new Map(consents.map(c=>[c.id,c.characters||[]]));const available=residents.filter(r=>!g.players.some(p=>p.id===r.id)&&allowed.get(r.ownerUid)?.includes(r.id)).sort((a,b)=>engine.random(g.seed,a.id)-engine.random(g.seed,b.id));while(g.players.length<g.capacity&&available.length)g.players.push(participant(available.shift(),true));if(g.players.length<4)fail('game-not-enough-players');const perceptions=rows(await tx.get(ctx.root.collection('perceptions')));g.bias={};for(const v of perceptions){const terms=JSON.stringify(parse(v.viewJson));g.bias[v.sourceId+':'+v.targetId]=/미워|싫어|질투|불편|경계/.test(terms)?3:/신뢰|친구|소중|사랑|편안/.test(terms)?-3:0}g.deadlineAt=clock()+g.durationMs;engine.start(g)}),
  submitGame:(uid,input)=>gameAction(uid,input,async(tx,ctx,g)=>{if(g.status!=='playing'||g.phaseIndex!==input.phaseIndex)fail('game-stale-phase',409);const p=g.players.find(p=>p.id===input.characterId&&p.ownerUid===uid&&!p.delegated&&p.alive);if(!p)fail('character-owner-required',403);const action=input.action||{};if(g.phase==='plan'){if(!engine.validatePlan(g,p,action.plan))fail('game-invalid-plan')}
   else if(g.phase==='vote'){if(!g.players.some(q=>q.id===action.targetId&&q.alive&&q.id!==p.id))fail('game-invalid-target')}
   else if(g.debateRound===0&&action.kind==='statement'){if(!engine.validateStatement(g,action.segments))fail('game-invalid-statement')}
   else {if(!['card','forge','accuse','defend','pass'].includes(action.kind))fail('game-invalid-action');if(['card','forge'].includes(action.kind)&&!(g.cards[p.id]||[]).some(c=>c.id===action.cardId))fail('game-private-card',403);if(action.kind==='forge'&&(p.role!=='mafia'||p.forgedDay===g.day||!g.locations.some(l=>l.id===action.place)))fail('game-invalid-action');if(['accuse','defend'].includes(action.kind)&&!g.players.some(q=>q.id===action.targetId&&q.alive&&q.id!==p.id))fail('game-invalid-target')}
   g.submissions[p.id]=g.phase==='plan'?{plan:action.plan.map(({kind,place})=>({kind,place}))}:g.phase==='vote'?{targetId:action.targetId}:g.debateRound===0?{kind:'statement',segments:(action.kind==='statement'?action.segments:engine.openingStatement(g,p)).map(({period,place,action})=>({period,place,action}))}:{kind:action.kind,...(action.cardId?{cardId:action.cardId}:{}),...(action.targetId?{targetId:action.targetId}:{}),...(action.place?{place:action.place}:{})};
  }),
  cancelGame:(uid,input)=>gameAction(uid,input,async(tx,ctx,g)=>{if(!ctx.manager)fail('manager-required',403);if(g.status==='finished')fail('game-already-started');g.status='cancelled';g.submissions={}}),
  leaveGame:(uid,input)=>gameAction(uid,input,async(tx,ctx,g)=>{const p=g.players.find(p=>p.ownerUid===uid&&!p.delegated);if(!p)fail('character-owner-required',403);if(g.status==='recruiting')g.players=g.players.filter(q=>q.id!==p.id);else p.alive=false}),
  advanceGame:(uid,input)=>gameAction(uid,input,async()=>{})
 };
};
