import {bindWalletAccounts} from './wallet-sharing.js';
import {state,save} from './state.js?v=20260909dev305';
import {buildSharedWorld} from './shared-world.js?v=20260909dev305';
import {economyAvailable} from './economy-access.js';
import {ensureWallet,displayMoney,moneyEntry,settleEmployment} from './character-money.js';
import {careersFor,economyFor,saveCareer,archiveCareer,updateWorldCurrency,applyWorldCurrency} from './career-world.js';
import {careerLabel} from './career-catalog.js';
import {assignEmployment,nextSalaryPayout,salaryPreview,employmentsFor,removeEmployment} from './salary.js';
const tr=(ko,en,ja)=>({ko,en,ja}[state.uiLanguage]||ko);
export const paperwork=()=>tr('관공서에 서류 제출하는 중…','Submitting paperwork at the municipal office…','役所に書類を提出しています…');
const errorText=e=>({'career-builtin-readonly':tr('기본 직업은 수정할 수 없어요.','Built-in careers cannot be edited.','基本職業は編集できません。'),'career-permission':tr('직업을 관리할 권한이 없어요.','You cannot manage this career.','この職業の管理権限がありません。'),'career-conflict':tr('다른 멤버가 먼저 수정했어요. 다시 열어 주세요.','Another member made changes. Reopen this screen.','他のメンバーが変更しました。開き直してください。'),'career-invalid':tr('이름·지급일·월급·업무 내용을 확인해 주세요.','Check the names, payday, salary and duties.','名前・支給日・給与・業務内容を確認してください。')}[e.message]||tr('처리하지 못했어요. 다시 시도해 주세요.','Could not complete this. Please retry.','処理できませんでした。再試行してください。'));
function node(tag,text,className){const el=document.createElement(tag);if(text)el.textContent=text;if(className)el.className=className;return el}
function modal(title){const d=node('dialog',null,'career-dialog');const head=node('header'),h=node('h2',title),close=node('button','×');close.type='button';close.onclick=()=>d.close();head.append(h,close);const body=node('section',null,'career-body'),status=node('p');status.setAttribute('role','status');d.append(head,body,status);d.onclose=()=>{d.remove();window.dispatchEvent(new Event('drawer-money-updated'))};document.body.append(d);d.showModal();return {d,body,status}}
function field(body,label,type,value){const l=node('label',label),i=node('input');i.type=type;i.value=value??'';l.append(i);body.append(l);return i}
function button(body,label,run){const b=node('button',label);b.type='button';b.onclick=run;body.append(b);return b}
function context(){const s=window.DrawerVillageGroups?.getSnapshot?.(),snapshot=s?.activeGroupId&&s.group?s:null;return {snapshot,world:snapshot?buildSharedWorld(snapshot,state.uiLanguage):state}}
function controller(ui,info){let busy=false;const uid=window.ParallelCityAuth?.getInfo?.()?.user?.uid,accountState=state;return async(fn)=>{if(busy)return;busy=true;ui.status.textContent=paperwork();ui.d.setAttribute('aria-busy','true');const fields=[...ui.body.querySelectorAll('button,input,select,textarea')].map(e=>[e,e.disabled]);fields.forEach(([e])=>e.disabled=true);try{await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));if(state!==accountState||window.ParallelCityAuth?.getInfo?.()?.user?.uid!==uid)throw Error('career-context');if(info.snapshot&&(window.DrawerVillageGroups?.getSnapshot?.()?.activeGroupId!==info.snapshot.activeGroupId||window.ParallelCityAuth?.getInfo?.()?.user?.uid!==uid))throw Error('career-context');await fn();if(ui.d.isConnected)ui.status.textContent=tr('접수됐어요.','Filed successfully.','受理されました。')}catch(e){ui.status.textContent=errorText(e)}finally{busy=false;ui.d.removeAttribute('aria-busy');fields.forEach(([e,disabled])=>{if(e.isConnected)e.disabled=disabled})}}}
export function openCareerWorld(pane='jobs'){
 const info=context(),ui=modal(tr('세계관 직업·재산','World careers and economy','世界の職業・資産')), {world,snapshot}=info;
 if(!economyAvailable()){ui.body.textContent=tr('준비 중입니다.','Coming soon.','準備中です。');return ui.d}
 const uid=window.ParallelCityAuth?.getInfo?.()?.user?.uid;let manager=!snapshot||snapshot.group.ownerUid===uid||['manager','operator'].includes(snapshot.members?.find(m=>(m.uid||m.id)===uid)?.role),canCreate=manager||snapshot?.group.rules?.allowMemberCareerAdd===true;
 const run=controller(ui,info),persist=async(action,payload)=>{if(snapshot){const result=await window.DrawerVillageGroups.careerWorld({action,revision:economyFor(world).revision,...payload});world.economy=result.economy;snapshot.group.economy=result.economy;manager=result.canManage;canCreate=result.canCreate}else{if(action==='save')saveCareer(world,payload.career,'',true);else if(action==='archive')archiveCareer(world,payload.id);else updateWorldCurrency(world,payload.unit,payload.mealPrice);if(!await save(true))throw Error('save-failed')}};
 const draw=()=>{ui.d.scrollTop=0;ui.body.replaceChildren();const nav=node('nav');button(nav,tr('직업','Careers','職業'),()=>{pane='jobs';draw()});button(nav,tr('재산·화폐','Currency','資産・通貨'),()=>{pane='currency';draw()});ui.body.append(nav);
 if(pane==='currency'){const e=economyFor(world),unit=field(ui.body,tr('화폐 이름','Currency name','通貨名'),'text',e.unit),meal=field(ui.body,tr('기본 외식 한 끼 가격','Ordinary restaurant meal price','標準の外食1食の価格'),'number',e.mealPrice);unit.maxLength=20;meal.min='.0001';meal.step='any';ui.body.append(node('p',tr('월급과 재산의 표시에 함께 적용돼요. 기존 재산의 구매력은 유지돼요.','Applies to salary and wealth display while preserving purchasing power.','給与と資産の表示に適用し、購買力は維持します。')));button(ui.body,tr('저장','Save','保存'),()=>run(async()=>{await persist('currency',{unit:unit.value,mealPrice:Number(meal.value)});draw()})).disabled=!manager;unit.disabled=meal.disabled=!manager;return}
 button(ui.body,tr('＋ 직업 만들기','＋ Create career','＋ 職業を作成'),()=>edit({id:'custom-'+crypto.randomUUID(),name:'',payDay:25,ranks:[{id:crypto.randomUUID(),name:'',salaryMeals:250,duties:[]}]})).disabled=!canCreate;
 const list=node('div',null,'career-list');ui.body.append(list);for(const j of careersFor(world).filter(j=>!j.archived)){const b=button(list,careerLabel(j,state.uiLanguage)+' · '+j.ranks.length+tr('개 직급',' ranks','職階'),()=>edit(structuredClone(j)));b.dataset.careerId=j.id;}
 };
 const edit=job=>{ui.d.scrollTop=0;ui.body.replaceChildren();button(ui.body,tr('‹ 직업 목록','‹ Careers','‹ 職業一覧'),draw);const editable=!job.builtin&&(manager||(!job.ownerUid?canCreate:job.ownerUid===uid)),name=field(ui.body,tr('직업 분류 이름','Career category name','職業分類名'),'text',job.name),day=field(ui.body,tr('매월 월급 지급일','Monthly payday','毎月の給与支給日'),'number',job.payDay);name.maxLength=60;day.min=1;day.max=31;const departments=node('textarea');departments.value=(job.departments||[]).join('\n');departments.setAttribute('aria-label',tr('부서·소속 목록 (한 줄에 하나)','Departments (one per line)','部署・所属一覧（1行に1つ）'));departments.placeholder=tr('부서·소속: 한 줄에 하나씩','Departments: one per line','部署・所属：1行に1つ');const departmentLabel=node('label',tr('부서·소속 목록 (한 줄에 하나)','Departments (one per line)','部署・所属一覧（1行に1つ）'));departmentLabel.append(departments);ui.body.append(departmentLabel);departments.disabled=!editable;ui.body.append(node('p',tr('해당 날짜가 없는 달에는 말일에 지급해요. 월급은 재직 기간에 비례해 계산해요.','Uses the last day in shorter months. Pay is prorated for time employed.','該当日がない月は月末に支給します。在職期間に比例して計算します。')));const ranks=node('div',null,'career-ranks');ui.body.append(ranks);
 if(job.builtin)ui.body.append(node('p',tr('기본 직업은 읽기 전용이에요. 새로운 직업은 직업 만들기에서 추가해 주세요.','Built-in careers are read-only. Use Create career to add your own.','基本職業は閲覧専用です。「職業を作成」で新しい職業を追加できます。')));
 const paintRanks=()=>{ranks.replaceChildren();for(const rank of job.ranks){const card=node('section',null,'career-rank');ranks.append(card);const rn=field(card,tr('직급 이름','Rank name','職階名'),'text',rank.name),salary=field(card,tr('월급 · 외식 횟수 기준','Monthly pay · meals','月給・外食回数換算'),'number',rank.salaryMeals);rn.maxLength=60;salary.min=0;salary.max=1000000;salary.step='.0001';rn.oninput=()=>rank.name=rn.value;salary.oninput=()=>rank.salaryMeals=Number(salary.value);const preview=node('small');const refresh=()=>{const e=economyFor(world);preview.textContent=(Number(salary.value)*e.mealPrice).toLocaleString()+' '+e.unit};salary.addEventListener('input',refresh);refresh();card.append(preview);const duties=node('div',null,'career-duties');card.append(duties);for(const duty of rank.duties){const row=node('section');duties.append(row);const dn=field(row,tr('업무 이름','Duty name','業務名'),'text',duty.name),desc=node('textarea');dn.maxLength=80;desc.maxLength=500;desc.value=duty.description;desc.setAttribute('aria-label',tr('업무 설명 · 근무 로그','Duty description · work log','業務の説明・勤務ログ'));row.append(desc);dn.oninput=()=>duty.name=dn.value;desc.oninput=()=>duty.description=desc.value;button(row,tr('업무 제거','Remove duty','業務を削除'),()=>{rank.duties.splice(rank.duties.indexOf(duty),1);paintRanks()})}button(card,tr('＋ 업무 추가','＋ Add duty','＋ 業務を追加'),()=>{rank.duties.push({name:'',description:''});paintRanks()}).disabled=rank.duties.length>=20;button(card,tr('직급 제거','Remove rank','職階を削除'),()=>{job.ranks.splice(job.ranks.indexOf(rank),1);paintRanks()}).disabled=job.ranks.length<=1;}if(!editable)ranks.querySelectorAll('input,textarea,button').forEach(e=>e.disabled=true)};paintRanks();
 button(ui.body,tr('＋ 직급 추가','＋ Add rank','＋ 職階を追加'),()=>{if(job.ranks.length<30){job.ranks.push({id:crypto.randomUUID(),name:'',salaryMeals:250,duties:[]});paintRanks()}}).disabled=!editable;
 button(ui.body,tr('서류 제출','Submit paperwork','書類を提出'),()=>run(async()=>{await persist('save',{career:{...job,name:name.value,payDay:Number(day.value),departments:departments.value.split('\n').map(s=>s.trim()).filter(Boolean)}});draw()})).disabled=!editable;
 if(job.ownerUid!==undefined&&!job.builtin)button(ui.body,tr('직업 모집 종료','Archive career','職業の募集を終了'),()=>run(async()=>{await persist('archive',{id:job.id});draw()})).disabled=!editable;name.disabled=day.disabled=!editable;
 };
 if(snapshot)void run(async()=>{const result=await window.DrawerVillageGroups.careerWorld({action:'read'});world.economy=result.economy;manager=result.canManage;canCreate=result.canCreate;draw()});else draw();return ui.d;
}
export function openEmployment(world,c,snapshot=null){
 window.dispatchEvent(new CustomEvent('drawer-open-career-page',{detail:{id:c.id,groupId:snapshot?.activeGroupId||''}}));
}
export function mountEmployment(container,world,c,snapshot=null){
 if(snapshot?.group?.economy)world.economy=snapshot.group.economy;
 const initialState=state,uid=window.ParallelCityAuth?.getInfo?.()?.user?.uid;
 const valid=()=>container.isConnected&&state===initialState&&window.ParallelCityAuth?.getInfo?.()?.user?.uid===uid&&(!snapshot||window.DrawerVillageGroups?.getSnapshot?.()?.activeGroupId===snapshot.activeGroupId);
 const body=node('section',null,'career-body'),status=node('p');status.setAttribute('role','status');container.replaceChildren(body,status);
 if(!economyAvailable()){body.textContent=tr('준비 중입니다.','Coming soon.','準備中です。');return container;}
 const ui={d:container,body,status},run=controller(ui,{world,snapshot}),owner=!snapshot||c.ownerUid===window.ParallelCityAuth?.getInfo?.()?.user?.uid;
 let editingId=null,adding=false;
 const draw=()=>{ui.d.scrollTop=0;ui.body.replaceChildren();ensureWallet(c);applyWorldCurrency(world,c);bindWalletAccounts(world);const list=employmentsFor(c),employment=adding?null:list.find(e=>e.id===editingId)||list[0];const nav=node('nav');for(const e of list)button(nav,careerLabel(careersFor(world).find(j=>j.id===e.jobId),state.uiLanguage)||e.jobName,()=>{editingId=e.id;adding=false;draw()});button(nav,tr('＋ 직업 추가','＋ Add job','＋ 職業を追加'),()=>{adding=true;editingId=null;draw()}).disabled=!owner||list.length>=10;ui.body.append(nav);const jobs=careersFor(world).filter(j=>!j.archived),selected=employment?.jobId||jobs.find(j=>j.name===c.job)?.id||jobs[0].id;
 const label=node('label',tr('직업 종류','Career type','職業の種類')),select=node('select');for(const j of jobs)select.add(new Option(careerLabel(j,state.uiLanguage),j.id,false,j.id===selected));select.setAttribute('aria-label',tr('직업 종류','Career type','職業の種類'));label.append(select);ui.body.append(label);const rankLabel=node('label',tr('직급','Rank','職階')),rankSelect=node('select');rankSelect.setAttribute('aria-label',tr('직급','Rank','職階'));rankLabel.append(rankSelect);ui.body.append(rankLabel);const summary=node('p'),duties=node('ul');ui.body.append(summary,duties);const choose=()=>{const j=jobs.find(j=>j.id===select.value),rank=j.ranks.find(r=>r.id===rankSelect.value)||j.ranks[0];summary.textContent=tr('월 환산액 ','Monthly equivalent ','月額換算 ')+displayMoney(rank.salaryMeals*10000,c,state.uiLanguage)+' · '+tr('매월 ','Day ','毎月')+j.payDay+tr('일 정산',' settlement day','日精算');duties.replaceChildren(...rank.duties.map(d=>{const copy=d.copy?.[state.uiLanguage]||d;return node('li',copy.name+' — '+copy.description)}))};const populate=()=>{rankSelect.replaceChildren();const j=jobs.find(j=>j.id===select.value);for(const r of j.ranks)rankSelect.add(new Option(careerLabel(r,state.uiLanguage),r.id,false,r.id===employment?.rankId));choose()};select.onchange=populate;rankSelect.onchange=choose;populate();
 const frequencyLabel=node('label',tr('급여 지급 방식','Pay frequency','給与の支給頻度')),frequency=node('select');for(const [id,ko,en,ja]of [['daily','일급','Daily','日払い'],['weekly','주급','Weekly','週払い'],['monthly','월급','Monthly','月払い']])frequency.add(new Option(tr(ko,en,ja),id,false,id===(employment?.frequency||'monthly')));frequency.setAttribute('aria-label',tr('급여 지급 방식','Pay frequency','給与の支給頻度'));frequencyLabel.append(frequency);ui.body.append(frequencyLabel,node('p',tr('월 환산액은 같아요. 주급은 7일 간격으로, 남은 기간과 단위 정산 차액은 월 정산일에 맞춰 지급해요.','The monthly total stays the same. Weekly pay is every seven days; the remaining period and rounding balance settle on the monthly payday.','月額は同じです。週払いは7日ごとで、残りの日数と端数は月の精算日に支払います。')));
 const department=field(ui.body,tr('부서·소속','Department / branch','部署・所属'),'text',employment?.department||''),specialty=field(ui.body,tr('세부 분야 · 병과 (선택)','Specialty (optional)','専門分野・兵科（任意）'),'text',employment?.specialty||'');department.maxLength=specialty.maxLength=60;const choices=node('datalist');choices.id='career-departments-'+crypto.randomUUID();department.setAttribute('list',choices.id);const fillDepartments=()=>{choices.replaceChildren(...(jobs.find(j=>j.id===select.value)?.departments||[]).map(n=>new Option(n,n)))};select.addEventListener('change',fillDepartments);fillDepartments();ui.body.append(choices);
 const title=field(ui.body,tr('표시할 직업명 (선택)','Display job title (optional)','表示する職業名（任意）'),'text',c.jobTitle||'');title.maxLength=80;
 ui.body.append(node('p',employment?tr('다음 지급일: ','Next payday: ','次の支給日：')+new Date(nextSalaryPayout(employment)).toLocaleDateString():tr('처음 서류를 제출한 날부터 월급이 쌓여요.','Salary starts accruing when you first submit.','最初の書類提出日から給与を計算します。')));
 if(employment){const preview=salaryPreview(employment);ui.body.append(node('p',tr('다음 예상 지급액: ','Expected next payment: ','次回の支給予定額：')+displayMoney(preview.amount,c,state.uiLanguage)))}
 button(ui.body,tr('직업·직급 서류 제출','Submit career and rank','職業・職階の書類を提出'),()=>run(async()=>{const jobId=select.value,rankId=rankSelect.value;if(snapshot){const result=await window.DrawerVillageGroups.characterMoney({id:c.id,action:'employment',jobId,rankId,jobTitle:title.value,department:department.value,specialty:specialty.value,frequency:frequency.value,employmentId:employment?.id,add:adding});if(!valid())return;Object.assign(c,{wallet:result.wallet,job:result.job,jobTitle:result.jobTitle});if(result.walletSharing){world.walletSharing=result.walletSharing;snapshot.group.walletSharing=result.walletSharing;bindWalletAccounts(world);}const r=snapshot.residents.find(r=>r.id===c.id);if(r){r.lifeJson=JSON.stringify({...JSON.parse(r.lifeJson||'{}'),wallet:c.wallet});r.profileJson=JSON.stringify({...JSON.parse(r.profileJson||'{}'),job:c.job,jobTitle:c.jobTitle})}}else{assignEmployment(world,c,jobId,rankId,Date.now(),moneyEntry,{department:department.value,specialty:specialty.value,frequency:frequency.value,employmentId:employment?.id,add:adding});c.jobTitle=title.value;if(!await save(true))throw Error('save-failed')}adding=false;draw()})).disabled=!owner;
 if(employment)button(ui.body,tr('이 직업 그만두기','Leave this job','この職業を辞める'),()=>run(async()=>{if(snapshot){const result=await window.DrawerVillageGroups.characterMoney({id:c.id,action:'employment-remove',employmentId:employment.id});if(!valid())return;c.wallet=result.wallet;if(result.walletSharing){world.walletSharing=result.walletSharing;snapshot.group.walletSharing=result.walletSharing;bindWalletAccounts(world);}c.job=result.job;const r=snapshot.residents.find(r=>r.id===c.id);if(r){r.lifeJson=JSON.stringify({...JSON.parse(r.lifeJson||'{}'),wallet:c.wallet});r.profileJson=JSON.stringify({...JSON.parse(r.profileJson||'{}'),job:c.job,jobTitle:c.jobTitle});}}else{removeEmployment(c,employment.id,Date.now(),moneyEntry);if(!await save(true))throw Error('save-failed')}editingId=null;draw()})).disabled=!owner;
 if(!owner)ui.body.querySelectorAll('input,select').forEach(e=>e.disabled=true);
 };
 if(snapshot&&owner){draw();void run(async()=>{const result=await window.DrawerVillageGroups.characterMoney({id:c.id,action:'read'});if(!valid())return;c.wallet=result.wallet;if(result.walletSharing){world.walletSharing=result.walletSharing;snapshot.group.walletSharing=result.walletSharing;bindWalletAccounts(world);}draw()});}else{if(!snapshot&&settleEmployment(world,c,Date.now(),true))void save(true);draw()}return ui.d;
}
