import {recipeUnlocked,medievalCookingAccess} from './cooking-access.js';
import {preparedFoods} from './prepared-food.js';
import {savedRecipeById} from './cooking.js';
import {recipeIcon} from './cooking-display.js';
import {RECIPES} from './recipes.js';
import {catalogRecipes,sortCookingRecipes} from './catalog-recipes.js';
import {recipeName,recipeStep,recipeIngredients} from './recipe-localizations.js';
import {cookingLevel,cookingProgress,recipeAllowed,canStartCooking,finishCooking} from './cooking.js';
import {state,save,directCharacterActivity} from './state.js?v=20260909dev305';
import {buildSharedWorld} from './shared-world.js?v=20260909dev305';
import {displayMoney,BASE_MEAL} from './character-money.js';
import {characterTown} from './town-setting.js';
import {economyAvailable} from './economy-access.js';
import {playCookingSound,stopCookingSound} from './cooking-audio.js';
const text=(lang,ko,en,ja)=>({ko,en,ja}[lang]||ko);
const cuisines={chinese:['중식','Chinese','中国料理'],dessert:['디저트·빵','Desserts and bread','デザート・パン'],other:['기타','Other','その他'],medieval:['중세 유럽','Medieval Europe','中世ヨーロッパ'],korean:['한식','Korean','韓国料理'],japanese:['일식','Japanese','日本料理'],american:['미국식','American','アメリカ料理'],italian:['이탈리안','Italian','イタリア料理'],quick:['간편식','Quick meals','簡単料理'],gourmet:['고급 요리','Gourmet','高級料理']};
function context(id){const api=window.DrawerVillageGroups,snapshot=api?.getSnapshot?.(),shared=snapshot?.activeGroupId&&snapshot.group,w=shared?buildSharedWorld(snapshot,state.uiLanguage):state;return {w,c:w.characters[id||w.activeId],api,snapshot:shared?snapshot:null,uid:window.ParallelCityAuth?.getInfo?.()?.user?.uid||''}}
export function openCooking(id){
 if(!economyAvailable())return;const initial=context(id);if(!initial.c)return;id=initial.c.id;const gid=initial.snapshot?.activeGroupId||'',owner=initial.uid,lang=state.uiLanguage,tr=(ko,en,ja)=>text(lang,ko,en,ja),d=document.createElement('dialog');d.className='cooking-dialog';
 const head=document.createElement('header'),heading=document.createElement('h2'),close=document.createElement('button');heading.textContent=tr('요리하기','Cook','料理する');close.textContent='×';close.setAttribute('aria-label',tr('닫기','Close','閉じる'));close.onclick=()=>d.close();head.append(heading,close);d.append(head);
 const filter=document.createElement('select');filter.setAttribute('aria-label',tr('요리 종류','Cuisine','料理の種類'));for(const [key,labels] of [['all',['전체','All','すべて']],...Object.entries(cuisines).filter(([key])=>key!=='medieval'||medievalCookingAccess(initial.w,initial.c))]){const o=document.createElement('option');o.value=key;o.textContent=labels[{ko:0,en:1,ja:2}[lang]||0];filter.append(o)}
 const search=document.createElement('input');search.type='search';search.placeholder=tr('요리 검색','Find a recipe','料理を検索');search.setAttribute('aria-label',search.placeholder);const controls=document.createElement('nav');const sort=document.createElement('select');sort.setAttribute('aria-label',tr('정렬','Sort','並び順'));for(const [value,ko,en,ja] of [['level','레벨순 · 쉬운 순','Level · easiest first','レベル順・簡単な順'],['price','가격순 · 저렴한 순','Price · low to high','価格順・安い順']]){const option=document.createElement('option');option.value=value;option.textContent=tr(ko,en,ja);sort.append(option)}controls.append(filter,sort,search);d.append(controls);
 const content=document.createElement('section'),status=document.createElement('p');status.setAttribute('role','status');d.append(content,status);let requestId='',busy=false;
 const valid=()=>{const next=context(id);return next.c&&next.uid===owner&&(next.snapshot?.activeGroupId||'')===gid?next:null};
 const detail=r=>{content.className="recipe-detail";content.replaceChildren();const info=valid();if(!info){d.close();return}const {c,w}=info;const title=document.createElement('h3');title.textContent=recipeName(r,lang);const back=document.createElement('button');back.textContent=tr('‹ 목록','‹ Recipes','‹ 一覧');back.onclick=list;
 const price=document.createElement('p');price.textContent=tr('재료비 ','Ingredients ','材料費 ')+displayMoney(Math.round(r.cost.home*BASE_MEAL),c,lang)+' · '+tr('외식 기준 ','Dining out ','外食の目安 ')+displayMoney(Math.round(r.cost.out*BASE_MEAL),c,lang);
 const level=document.createElement('p');level.textContent=tr('요리 레벨 ','Cooking level ','料理レベル ')+cookingLevel(c)+' / '+tr('필요 레벨 ','Required ','必要レベル ')+r.level;
 const ingredients=document.createElement('p');ingredients.textContent=recipeIngredients(r,lang).join(' · ');const steps=document.createElement('ol');r.steps.forEach((s,i)=>{const li=document.createElement('li');li.textContent=recipeStep(r,i,lang);steps.append(li)});
 const start=document.createElement('button');start.dataset.cookingStart=r.id;start.textContent=tr('요리 시작','Start cooking','料理を始める');const reason=canStartCooking(w,c,r.id);start.disabled=!!reason||!!info.snapshot&&c.ownerUid!==owner;const help=document.createElement('p');help.textContent=reason==='cooking-level'?tr('더 쉬운 요리로 경험을 쌓아 주세요.','Gain experience with easier recipes first.','簡単な料理で経験を積んでください。'):reason==='cooking-busy'?tr('진행 중인 요리를 먼저 마쳐 주세요.','Finish the current recipe first.','調理中の料理を先に完成させてください。'):tr('과정에 따라 한 단계에 3초~3분이 걸려요. 다른 화면으로 이동해도 계속됩니다.','Each step takes 3 seconds to 3 minutes. Cooking continues while you use other screens.','工程ごとに3秒〜3分かかります。ほかの画面に移動しても進みます。');
 requestId=crypto.randomUUID();start.onclick=async()=>{if(busy)return;const latest=valid();if(!latest)return d.close();busy=true;start.disabled=true;status.textContent=tr('준비하고 있어요…','Preparing…','準備しています…');try{const command={characterId:id,kind:'meal',lifeTask:'simple_cook',recipeId:r.id,cookingRequestId:requestId};if(latest.snapshot)await latest.api.command(command);else if(!directCharacterActivity(id,'meal',command))throw Error('cooking-unavailable');if(!valid())return d.close();status.textContent=tr('요리를 시작했어요. 관찰 화면에서 과정을 볼 수 있어요.','Cooking started. Watch the steps on the observe screen.','料理を始めました。観察画面で工程を見られます。');window.dispatchEvent(new Event('drawer-money-updated'));d.close()}catch{status.textContent=tr('주방·잔액·요리 레벨과 연결 상태를 확인해 주세요.','Check the kitchen, balance, cooking level and connection.','キッチン・残高・料理レベル・接続を確認してください。');start.disabled=false}finally{busy=false}};
 content.append(back,title,price,level,ingredients,help,start,steps);
 };
 const list=()=>{content.className="recipe-grid";content.replaceChildren();status.textContent='';const info=valid();if(!info)return d.close();const town=characterTown(info.w,info.c),query=search.value.trim().toLocaleLowerCase();const inventory=document.createElement('p');inventory.className='cooking-inventory';inventory.textContent=tr('완성한 요리: ','Prepared dishes: ','完成した料理：')+(Object.entries(info.c.cooking?.inventory||{}).filter(([,count])=>count>0).map(([id,count])=>{const r=savedRecipeById(id,info.w,info.c.cooking?.dishes?.find(d=>d.recipeId===id));return (r?recipeName(r,lang):id)+' × '+count}).join(' · ')||tr('아직 없어요.','None yet.','まだありません。'));content.append(inventory);for(const {dish} of preparedFoods(info.w).filter(x=>x.dish.homeId===info.c.homeId)){const food=document.createElement('button'),r=savedRecipeById(dish.recipeId,info.w,dish);food.dataset.preparedFood=dish.id;food.textContent=(dish.storage==='fridge'?'🧊 ':'🍽️ ')+(r?recipeName(r,lang):dish.recipeId);content.append(food)}const available=sortCookingRecipes([...catalogRecipes(info.w),...RECIPES].filter(r=>recipeAllowed(town,r)&&recipeUnlocked(info.w,info.c,r)&&(filter.value==='all'||r.cuisine===filter.value)&&recipeName(r,lang).toLocaleLowerCase().includes(query)),sort.value);for(const r of available){const button=document.createElement('button');button.className='recipe-choice';button.dataset.recipeId=r.id;button.dataset.recipeLevel=r.level;button.dataset.recipePrice=r.cost.home;const icon=document.createElement('span'),name=document.createElement('b'),meta=document.createElement('small');icon.className='recipe-icon';icon.setAttribute('aria-hidden','true');icon.textContent=recipeIcon(r);name.textContent=recipeName(r,lang);meta.textContent=(r.custom?tr('사용자 요리 · ','Custom · ','ユーザー料理 · '):'')+'Lv.'+r.level+' · '+displayMoney(Math.round(r.cost.home*BASE_MEAL),info.c,lang);button.append(icon,name,meta);button.onclick=()=>detail(r);content.append(button)}if(!available.length){const p=document.createElement('p');p.textContent=tr('이 조건에 맞는 요리가 없어요.','No recipes match these settings.','この条件に合う料理はありません。');content.append(p)}};
 filter.value='all';if(!RECIPES.some(r=>recipeAllowed(characterTown(initial.w,initial.c),r)&&r.cuisine===filter.value))filter.value='all';filter.onchange=list;sort.onchange=list;search.oninput=list;d.onclose=()=>d.remove();document.body.append(d);list();d.showModal();
}
let timer=0;
const settlements=new Set();
export function syncCookingUI(){
 clearTimeout(timer);stopCookingSound();const id=document.querySelector('[data-observed-character]')?.dataset.observedCharacter||state.activeId;if(!id||!economyAvailable())return;
 const info=context(id),job=info.c?.cooking?.active,host=document.querySelector('[data-game-hud-moment]');if(!job||!host)return;
 host.dataset.cookingActive=job.id;let finished=false;
 const tick=async()=>{if(!host.isConnected||document.hidden){stopCookingSound();return}const progress=cookingProgress(job);if(!progress)return;const lang=state.uiLanguage;host.querySelector('h1').textContent=text(lang,recipeName(progress.recipe,lang)+' 만드는 중','Making '+recipeName(progress.recipe,lang),recipeName(progress.recipe,lang)+'を作っています');host.querySelector('.game-hud-moment-body>p').textContent=progress.waiting?text(lang,'주방으로 이동하는 중','Heading to the kitchen','キッチンへ移動中'):progress.complete?text(lang,'요리가 완성됐어요.','The dish is ready.','料理が完成しました。'):recipeStep(progress.recipe,progress.step,lang);
 if(progress.complete){stopCookingSound();if(!finished&&!settlements.has((info.snapshot?.activeGroupId||'local')+':'+job.id)){finished=true;const settlementKey=(info.snapshot?.activeGroupId||'local')+':'+job.id;settlements.add(settlementKey);if(settlements.size>100)settlements.delete(settlements.values().next().value);try{if(info.snapshot){const result=await info.api.advanceLife(true);if(result?.updated===false)throw Error('cooking-pending')}else{finishCooking(state,info.c,Date.now());save(true)}window.dispatchEvent(new Event('drawer-money-updated'))}catch{settlements.delete(settlementKey);finished=false;timer=setTimeout(tick,10000)}}return}
 if(!progress.waiting)playCookingSound(progress.recipe.steps[progress.step],progress.step,state);timer=setTimeout(tick,500);
 };void tick();
}

if(globalThis.document)document.addEventListener('visibilitychange',()=>{if(!document.hidden)syncCookingUI()});
