import {showRewardedAd} from "./rewarded-ad.js?v=20260909dev305";
const copies={
 ko:{gold:'골드 · 준비 중',balance:'다이아 잔액',title:'다이아 상점',paid:'유료',bonus:'보너스',loading:'잔액 확인 중',ready:'다이아 상점을 준비 중이에요.',login:'로그인 후 이용해 주세요.',charge:'다이아 100개 충전',slot:'캐릭터 슬롯 1개',town:'마을 슬롯 1개',storage:'사진 저장 공간 50MB',buy:'구매',visit:'오늘의 방문 보상 받기',ad:'광고 보고 다이아 받기',adInfo:'광고는 원할 때만 시청해요. 보상은 시청 확인 후 지급됩니다.',refresh:'잔액 새로고침',privacy:'광고 개인정보 선택',error:'처리하지 못했어요. 잠시 후 다시 확인해 주세요.',insufficient:'다이아가 부족해요.',frozen:'환불 내역을 확인 중이에요. 고객센터에 문의해 주세요.',pending:'시청 확인 중이에요. 잠시 후 잔액을 새로고침해 주세요.',done:'적용했어요.',terms:'보너스 다이아부터 사용해요. 충전한 다이아에는 유효기간이 없어요.',claimed:'오늘의 보상 받음',unavailable:'광고 준비 중',sandbox:'테스트 잔액 · 실제 구매분과 별도',cancelled:'광고를 닫았어요. 다이아는 차감되지 않아요.',event:'이벤트 보상 받기'},
 en:{gold:'Gold · coming soon',balance:'Diamond balance',title:'Diamond shop',paid:'Purchased',bonus:'Bonus',loading:'Checking balance',ready:'The diamond shop is coming soon.',login:'Sign in to continue.',charge:'Buy 100 diamonds',slot:'1 character slot',town:'1 town slot',storage:'50MB image storage',buy:'Buy',visit:'Claim today’s visit reward',ad:'Watch an ad for diamonds',adInfo:'Watch only when you choose. Rewards arrive after viewing is verified.',refresh:'Refresh balance',privacy:'Ad privacy choices',error:'Unable to complete this. Please check again shortly.',insufficient:'Not enough diamonds.',frozen:'A refund needs review. Please contact support.',pending:'Verifying your reward. Refresh your balance shortly.',done:'Applied.',terms:'Bonus diamonds are used first. Purchased diamonds do not expire.',claimed:'Today’s reward claimed',unavailable:'Ads coming soon',sandbox:'Test balance · separate from real purchases',cancelled:'Ad closed. No diamonds were deducted.',event:'Claim event reward'},
 ja:{gold:'ゴールド・準備中',balance:'ダイヤ残高',title:'ダイヤショップ',paid:'有償',bonus:'ボーナス',loading:'残高を確認中',ready:'ダイヤショップは準備中です。',login:'ログインしてご利用ください。',charge:'ダイヤ100個をチャージ',slot:'キャラクター枠1人分',town:'村スロット1個',storage:'画像保存容量50MB',buy:'購入',visit:'今日の訪問報酬を受け取る',ad:'広告を見てダイヤを受け取る',adInfo:'広告は希望する場合だけ視聴できます。視聴確認後に報酬を付与します。',refresh:'残高を更新',privacy:'広告のプライバシー設定',error:'処理できませんでした。しばらくしてから再度ご確認ください。',insufficient:'ダイヤが不足しています。',frozen:'返金履歴を確認中です。サポートにお問い合わせください。',pending:'視聴確認中です。しばらくしてから残高を更新してください。',done:'適用しました。',terms:'ボーナスダイヤから使用します。有償ダイヤに有効期限はありません。',claimed:'今日の報酬は受取済み',unavailable:'広告は準備中です',sandbox:'テスト残高・実際の購入分とは別です',cancelled:'広告を閉じました。ダイヤは減りません。',event:'イベント報酬を受け取る'}
};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>window.ParallelCityAuth?.getInfo?.()?.user?.uid||'';
let owner='',value=null,loading=null,busy=false,redraw=()=>{},language='ko',banner=false,adReady=null,adQueue=Promise.resolve();
const copy=()=>copies[language]||copies.ko;
const config=()=>window.PARALLEL_CITY_CONFIG?.diamonds||{};
const platform=()=>window.Capacitor?.getPlatform?.()||'web';
const native=()=>window.Capacitor?.isNativePlatform?.();
const ad=()=>window.Capacitor?.Plugins?.AdMob;
const sandbox=()=>sessionStorage.getItem('diamond-sandbox:'+uid())==='true';
async function request(action,body={}){const account=uid(),token=await window.ParallelCityAuth?.getIdToken?.();if(!account||!token)throw Error('wallet-login');const response=await fetch(config().backendUrl+'/'+action,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({...body,sandbox:sandbox()}),signal:AbortSignal.timeout(20000)});const result=await response.json();if(uid()!==account)throw Error('wallet-account-changed');if(!response.ok)throw Object.assign(Error(result.code),{status:response.status});return result}
async function refresh(){if(loading)return loading;const account=uid();if(!account)return;loading=request('read').then(result=>{if(uid()===account){owner=account;value=result}}).catch(()=>{if(uid()===account){owner=account;value={enabled:false}}}).finally(()=>{loading=null;document.querySelectorAll('[data-home-diamonds]').forEach(el=>{el.textContent=owner===uid()&&Number.isFinite(value?.total)?value.total.toLocaleString(language):'—'});if(document.querySelector('[data-diamond-shop]'))redraw()});return loading}
export function renderHomeCurrencies(lang='ko'){
 language=lang;if(owner!==uid()){owner=uid();value=null}
 const c=copy(),total=Number.isFinite(value?.total)?value.total.toLocaleString(lang):'—';
 return `<div class="game-hud-currencies"><button type="button" class="game-hud-currency" disabled aria-label="${esc(c.gold)}" title="${esc(c.gold)}"><span aria-hidden="true">🟡 —</span></button><button type="button" class="game-hud-currency" data-tab="shop" aria-label="${esc(c.balance)}${sandbox()?' · '+esc(c.sandbox):''}"><span>💎 <b data-home-diamonds>${total}</b>${sandbox()?' *':''}</span></button></div>`;
}
export function renderDiamondShop(lang='ko',isNative=false){language=lang;if(owner!==uid()){owner=uid();value=null}const c=copy(),v=value||{},enabled=!!v.enabled,disabled=!enabled||busy||v.frozen,items=[['character_slot_1','slot',100],['town_slot_1','town',190],['storage_50mb','storage',290]];
 const cards=items.map(([id,label,cost])=>`<article class="diamond-product"><b>${esc(c[label])}</b><button data-diamond-buy="${id}" ${disabled||id==='storage_50mb'&&v.storage50?'disabled':''}>◆ ${Number(v.products?.[id]?.cost)||cost} · ${esc(c.buy)}</button></article>`).join('');
 return `<section class="diamond-shop" data-diamond-shop><h2>${esc(c.title)}</h2>${sandbox()?`<p>${esc(c.sandbox)}</p>`:''}<div class="diamond-balance"><strong>◆ ${v.total??'—'}</strong><span>${esc(c.paid)} ${v.paid??0} · ${esc(c.bonus)} ${v.bonus??0}</span><button data-diamond-refresh ${busy?'disabled':''}>${esc(c.refresh)}</button></div><p role="status">${esc(!uid()?c.login:!value?c.loading:v.frozen?c.frozen:!enabled?c.ready:c.terms)}</p><div class="diamond-products">${cards}</div><article class="diamond-charge"><b>${esc(c.charge)}</b>${isNative&&enabled?`<button data-play-purchase="diamonds_100" data-play-owned="false" disabled><span data-play-price="diamonds_100">₩1,000</span><small data-play-label></small></button>`:!isNative&&enabled?`<a class="primary" href="./payment.html?product=diamonds_100&lang=${esc(language)}">₩1,000</a>`:`<button disabled>₩1,000</button>`}</article><div class="diamond-rewards"><button data-diamond-visit ${disabled||v.dailyClaimed?'disabled':''}>${esc(v.dailyClaimed?c.claimed:c.visit)} · ◆ ${v.dailyReward??1}</button><button data-diamond-ad ${disabled||!v.adsEnabled||!native()||!window.PARALLEL_CITY_CONFIG?.ads?.enabled||!v.adsRemaining?'disabled':''}>${esc(v.adsEnabled?c.ad:c.unavailable)} · ◆ ${v.adReward??3}</button><p>${esc(c.adInfo)}</p>${(v.events||[]).map(e=>`<button data-diamond-event="${esc(e.id)}" ${disabled?'disabled':''}>${esc(e.title)} · ${esc(c.event)} · ◆ ${e.amount}</button>`).join('')}</div>${v.adsEnabled&&native()?`<button data-ad-privacy>${esc(c.privacy)}</button>`:''}<div class="diamond-banner-space" data-diamond-banner aria-hidden="true"></div></section>`;
}
async function initializeAds(){if(!native()||!ad()||!window.PARALLEL_CITY_CONFIG?.ads?.enabled)throw Error('ads-unavailable');if(!adReady)adReady=(async()=>{await ad().initialize({initializeForTesting:window.PARALLEL_CITY_CONFIG.ads.testing===true,requestTrackingAuthorization:false});let info=await ad().requestConsentInfo();if(!info.canRequestAds&&info.isConsentFormAvailable)info=await ad().showConsentForm();if(!info.canRequestAds)throw Error('ads-unavailable');return true})().catch(e=>{adReady=null;throw e});return adReady}
function updateBanner(){adQueue=adQueue.catch(()=>{}).then(async()=>{const root=document.querySelector('[data-diamond-shop]'),unit=value?.bannerUnits?.[platform()],show=!!root&&value?.adsEnabled&&native()&&window.PARALLEL_CITY_CONFIG?.ads?.enabled&&!!unit;if(!show){if(banner){await ad()?.removeBanner();banner=false}document.body.classList.remove('diamond-banner-visible');return}if(banner)return;await initializeAds();if(!document.querySelector('[data-diamond-shop]'))return;await ad().showBanner({adId:unit,adSize:'BANNER',position:'BOTTOM_CENTER',margin:0,npa:true,isTesting:window.PARALLEL_CITY_CONFIG.ads.testing===true});banner=true;document.body.classList.add('diamond-banner-visible');if(!document.querySelector('[data-diamond-shop]')){await ad().removeBanner();banner=false;document.body.classList.remove('diamond-banner-visible')}}).catch(()=>{banner=false;document.body.classList.remove('diamond-banner-visible')})}
async function watchAd(){await initializeAds();const account=uid(),ticket=await request('prepareAd',{platform:platform()});await ad().prepareRewardVideoAd({adId:ticket.adUnit,npa:true,isTesting:window.PARALLEL_CITY_CONFIG.ads.testing===true,ssv:{userId:account,customData:ticket.ticketId}});if(uid()!==account)throw Error('wallet-account-changed');const earned=await showRewardedAd(ad());await refresh();return earned?copy().pending:copy().cancelled}
export function bindDiamondShop({render,toast}){redraw=render;updateBanner();const root=document.querySelector('[data-diamond-shop]');if(!value&&uid()&&(root||document.querySelector('[data-home-diamonds]')))void refresh();if(!root)return;const run=fn=>async()=>{if(busy)return;busy=true;render();try{const message=await fn();await refresh();toast(typeof message==='string'?message:copy().done)}catch(e){toast(e.message==='wallet-insufficient'?copy().insufficient:e.message==='wallet-refund-pending'?copy().frozen:copy().error)}finally{busy=false;render()}};
 root.querySelector('[data-diamond-refresh]')?.addEventListener('click',run(refresh));
 root.querySelector('[data-diamond-visit]')?.addEventListener('click',run(()=>request('claim')));
 root.querySelectorAll('[data-diamond-event]').forEach(b=>b.onclick=run(()=>request('claim',{eventId:b.dataset.diamondEvent})));
 root.querySelectorAll('[data-diamond-buy]').forEach(b=>b.onclick=run(async()=>{const productId=b.dataset.diamondBuy,key='diamond-purchase:'+uid()+':'+sandbox();let pending;try{pending=JSON.parse(localStorage.getItem(key)||'null')}catch{}if(pending&&pending.productId!==productId)throw Error('wallet-pending');pending??={requestId:crypto.randomUUID(),productId};localStorage.setItem(key,JSON.stringify(pending));try{await request('purchase',pending);localStorage.removeItem(key);if(!sandbox())await window.ParallelCityAuth?.refreshEntitlements?.()}catch(e){if(e.status>=400&&e.status<500)localStorage.removeItem(key);throw e}}));
 root.querySelector('[data-diamond-ad]')?.addEventListener('click',run(watchAd));
 root.querySelector('[data-ad-privacy]')?.addEventListener('click',run(async()=>{await ad()?.showPrivacyOptionsForm();adReady=null;await ad()?.removeBanner();banner=false}));
}
window.addEventListener('drawer-village-diamonds-charged',event=>{const account=uid();if(event.detail?.environment==='Sandbox')sessionStorage.setItem('diamond-sandbox:'+account,'true');else if(event.detail?.environment==='Production')sessionStorage.removeItem('diamond-sandbox:'+account);value=null;void refresh()});

export function diamondShopGuide(lang){return {ko:["다이아 상점","다이아를 충전하거나 방문·이벤트·광고 보상으로 모아 캐릭터·마을 슬롯을 구매할 수 있어요. 보상 광고는 직접 눌렀을 때만 열려요. 기존에 구매한 슬롯은 그대로 유지됩니다."],en:["Diamond shop","Buy diamonds or earn them through visits, events and optional ads to purchase character and town slots. Rewarded ads open only when you choose. Previously purchased slots are preserved."],ja:["ダイヤショップ","ダイヤをチャージしたり、訪問・イベント・任意の広告視聴で集めたりして、キャラクターや村の枠を購入できます。報酬広告は自分で選んだ場合だけ表示されます。購入済みの枠は維持されます。"]}[lang]||diamondShopGuide("ko")}
