import {personalChoices,hobbyChoice} from './automatic-activities.js?v=20260909dev300';
import {workTasks} from './social-activities.js?v=20260909dev300';
import {LIFE_TASKS} from './life-tasks.js?v=20260909dev300';
export function installDirectSteps(command,copy,character,world){
 const lang=document.documentElement.lang==='en'?1:document.documentElement.lang==='ja'?2:0,text=(...labels)=>labels[lang],dialog=command.closest('dialog');
 const social=command.querySelector('[data-direct-panel="social"]'),targets=social.querySelector('[data-direct-target-list]'),payment=social.querySelector('[data-direct-payment-field]'),submit=social.querySelector('[data-direct-social-submit]');
 const socialButtons=[...social.querySelectorAll('[data-direct-social-action]')],simpleButtons=[...command.querySelectorAll('[data-direct-simple-action]')];
 command.className='home-occupant-command command-menu';command.replaceChildren();const pages=[],titles=new Map();let current=null;const history=[];
 const createPage=title=>{const p=document.createElement('section');p.className='command-menu-page';p.hidden=true;command.append(p);pages.push(p);titles.set(p,title);return p};
 const title=dialog.querySelector('h2'),back=dialog.querySelector('[data-command-close]');back.textContent='';back.setAttribute('aria-label',text('뒤로','Back','戻る'));
 const show=(p,push=true)=>{if(current&&push)history.push(current);current=p;pages.forEach(x=>x.hidden=x!==p);title.textContent=titles.get(p);dialog.querySelector('.direct-command-body').scrollTop=0};
 back.onclick=()=>history.length?show(history.pop(),false):dialog.close();dialog.addEventListener('cancel',e=>{if(history.length){e.preventDefault();show(history.pop(),false)}});
 const button=(parent,label,action)=>{const b=document.createElement('button');b.type='button';b.className='command-menu-button';b.textContent=label;if(action)b.onclick=action;parent.append(b);return b};
 const root=createPage(text('활동 선택','Choose an activity','活動を選ぶ')),life=createPage(text('생활','Daily life','生活')),exchange=createPage(text('교류','Social','交流')),hobby=createPage(text('취미','Hobbies','趣味')),work=createPage(text('일·학업','Work and study','仕事・学業')),move=createPage(text('이동','Movement','移動')),self=createPage(text('나답게','Personal time','自分らしく'));
 for(const [p,label] of [[life,text('생활','Daily life','生活')],[move,text('이동','Movement','移動')],[exchange,text('교류','Social','交流')],[hobby,text('취미활동','Enjoy a hobby','趣味を楽しむ')],[work,text('일·학업','Work and study','仕事・学業')],[self,text('나답게','Personal time','自分らしく')]]){const b=button(root,label,()=>show(p));if(p===hobby){b.dataset.directSimpleAction='relax';b.dataset.lifeTask='hobby_auto';b.onclick=null;if(!hobbyChoice(world,character,0)){b.disabled=true;b.textContent=text('취미 설정 필요','Set a hobby first','趣味を設定してください')}}}
 const addTask=(p,t)=>{const b=button(p,t.labels[lang]);b.dataset.directSimpleAction=t.kind;b.dataset.lifeTask=t.id};
 for(const [group,labels] of [['food',['식사·요리','Food and cooking','食事・料理']],['hygiene',['위생','Hygiene','清潔']],['rest',['휴식·개인시간','Rest and personal time','休息・自分の時間']],['groom',['몸단장','Grooming','身支度']],['chores',['집안일·살림','Household chores','家事']],['sleep',['수면','Sleep','睡眠']]]){const p=createPage(text('생활 · ','Daily life · ','生活・')+labels[lang]);button(life,labels[lang],()=>show(p));LIFE_TASKS.filter(t=>t.group===group).forEach(t=>addTask(p,t))}
 const addSimple=(p,kind)=>{const source=simpleButtons.find(b=>b.dataset.directSimpleAction===kind);if(source){const b=source.cloneNode(true);b.className='command-menu-button';p.append(b)}};
 ['read','music','game','art','exercise'].forEach(k=>addSimple(hobby,k));['walk','exercise'].forEach(k=>addSimple(move,k));for(const choice of personalChoices(world,character)){const b=button(self,choice.labels[lang]);if(choice.targetId){b.dataset.directSocialAction=choice.kind;b.dataset.autoTarget=choice.targetId}else{b.dataset.directSimpleAction=choice.kind;b.dataset.lifeTask=choice.lifeTask}}
 for(const task of workTasks(character||{})){const b=button(work,task.labels[lang]);b.dataset.directSimpleAction='work';b.dataset.workTask=task.id}addSimple(work,'study');addSimple(work,'research');
 const targetPage=createPage(text('함께할 상대 고르기','Choose a companion','相手を選ぶ'));targetPage.classList.add('command-target-page');if(targets)targetPage.append(targets);else{const p=document.createElement('p');p.textContent=copy.noTarget;targetPage.append(p)}
 const sections=[['대화','Conversation','会話',['talk','debate','gossip','custom_social']],['연락','Keeping in touch','交流を深める',['hangout','comfort','compliment']],['애정','Affection','愛情',['hug','handhold','lean','kiss','kiss_cautious','kiss_reconcile','affection']],['갈등','Conflict','対立',['taunt','insult','argue','fight']],['선물','Gifts','贈り物',[]],['동행','Together','一緒に',['dine','tea','drinks','cook_together','play_together','study_together','read_together','compete']]];
 for(const [ko,en,ja,kinds] of sections){const p=createPage(text('교류 · ','Social · ','交流・')+text(ko,en,ja));button(exchange,text(ko,en,ja),()=>show(p));if(!kinds.length){button(p,text('우편함에서 선물 보내기','Send a gift from the mailbox','郵便箱から贈り物を送る'),()=>{dialog.close();location.hash='tab=mailbox'});continue}const choose=button(p,text('함께할 상대 고르기','Choose a companion','相手を選ぶ'),()=>show(targetPage));choose.classList.add('command-companion');for(const kind of kinds){const b=socialButtons.find(b=>b.dataset.directSocialAction===kind);if(b){b.hidden=false;b.className='command-menu-button';p.append(b)}}}
 if(payment){payment.hidden=false;payment.classList.add('command-payment');const together=pages.find(p=>titles.get(p)===text('교류 · ','Social · ','交流・')+text('동행','Together','一緒に'));together?.append(payment)}
 submit.hidden=true;command.append(submit);
 command.addEventListener('click',e=>{const auto=e.target.closest('[data-auto-target]');if(auto)command.dataset.directTarget=auto.dataset.autoTarget},true);
 command.addEventListener('click',e=>{const target=e.target.closest('button[data-direct-target]');if(target){command.querySelectorAll('.command-companion').forEach(b=>b.textContent=target.textContent.trim());if(history.length)show(history.pop(),false)}const action=e.target.closest('button[data-direct-social-action]');if(action)queueMicrotask(()=>{if(!command.dataset.directTarget){show(targetPage);return}submit.disabled=false;submit.click()})});
 show(root,false);
}
