import {personalChoices,hobbyNames} from './automatic-activities.js?v=20260909dev302';
import {workTasks} from './social-activities.js?v=20260909dev302';
import {LIFE_TASKS} from './life-tasks.js?v=20260909dev302';
export function installDirectSteps(command,copy,character,world){
 const lang=document.documentElement.lang==='en'?1:document.documentElement.lang==='ja'?2:0,text=(...labels)=>labels[lang],dialog=command.closest('dialog');
 const social=command.querySelector('[data-direct-panel="social"]'),targets=social.querySelector('[data-direct-target-list]'),payment=social.querySelector('[data-direct-payment-field]'),submit=social.querySelector('[data-direct-social-submit]');
 const socialButtons=[...social.querySelectorAll('[data-direct-social-action]')],simpleButtons=[...command.querySelectorAll('[data-direct-simple-action]')];
 command.className='home-occupant-command command-menu';command.replaceChildren();const pages=[],titles=new Map();let current=null;const history=[];
 const createPage=title=>{const p=document.createElement('section');p.className='command-menu-page';p.hidden=true;command.append(p);pages.push(p);titles.set(p,title);return p};
 const title=dialog.querySelector('h2'),back=dialog.querySelector('[data-command-close]');back.textContent='';back.setAttribute('aria-label',text('뒤로','Back','戻る'));
 const trail=document.createElement('p');trail.className='command-breadcrumb';dialog.querySelector('header').after(trail);
 const show=(p,push=true)=>{if(current&&push)history.push(current);if(current)current.hidden=true;current=p;p.hidden=false;title.textContent=titles.get(p);trail.textContent=history.map(x=>titles.get(x)).join(' › ');trail.hidden=!history.length;dialog.querySelector('.direct-command-body').scrollTop=0};
 back.onclick=()=>history.length?show(history.pop(),false):dialog.close();dialog.addEventListener('cancel',e=>{if(history.length){e.preventDefault();show(history.pop(),false)}});
 const button=(parent,label,action)=>{const b=document.createElement('button');b.type='button';b.className='command-menu-button';b.textContent=label;if(action)b.onclick=action;parent.append(b);return b};
 const root=createPage(text('활동 선택','Choose an activity','活動を選ぶ')),life=createPage(text('생활','Daily life','生活')),exchange=createPage(text('교류','Social','交流')),hobby=createPage(text('취미','Hobbies','趣味')),work=createPage(text('일·학업','Work and study','仕事・学業')),move=createPage(text('이동','Movement','移動')),self=createPage(text('나답게','Personal time','自分らしく'));
 root.classList.add('command-root-page');
 for(const [p,label,icon,hint] of [[life,text('생활','Daily life','生活'),'☕',text('먹고, 씻고, 쉬어요','Eat, wash and rest','食べて、洗って、休む')],[move,text('이동','Movement','移動'),'🌿',text('가볍게 몸을 움직여요','Step out and stretch','歩いて、体を動かす')],[exchange,text('교류','Social','交流'),'💬',text('누군가와 함께해요','Spend time with someone','誰かと過ごす')],[hobby,text('취미활동','Hobbies','趣味'),'🎨',text('좋아하는 일에 푹','Enjoy their favorite things','好きなことに夢中')],[work,text('일·학업','Work and study','仕事・学業'),'✏️',text('내 일에 집중해요','Focus on work or study','仕事や勉強に集中')],[self,text('나답게','Personal time','自分らしく'),'✨',text('성격과 취향을 따라','Follow their personality','性格や好みに合わせて')]]){const b=button(root,'',()=>show(p));b.classList.add('command-category');const art=document.createElement('span');art.className='command-category-icon';art.textContent=icon;art.setAttribute('aria-hidden','true');const name=document.createElement('b');name.textContent=label;const note=document.createElement('small');note.textContent=hint;b.append(art,name,note)}
 const hobbies=hobbyNames(world,character),intro=document.createElement('div');intro.className='command-hobby-summary';const heading=document.createElement('b'),description=document.createElement('p');heading.textContent=text('좋아하는 취미','Favorite hobbies','好きな趣味');description.textContent=hobbies.length?text('이 중에서 캐릭터가 스스로 골라 즐겨요.','They will choose one of these hobbies.','この中から自分で選んで楽しみます。'):text('아직 등록된 취미가 없어요. 캐릭터 설정에서 취미를 추가하거나, 아래에서 오늘 할 활동을 골라 주세요.','No hobbies saved yet. Add hobbies in character settings, or choose an activity below.','趣味が未登録です。キャラクター設定で追加するか、下から今日の活動を選んでください。');intro.append(heading,description);if(hobbies.length){const tags=document.createElement('div');tags.className='command-hobby-tags';for(const name of hobbies){const tag=document.createElement('span');tag.textContent=name;tags.append(tag)}intro.append(tags)}hobby.append(intro);
 if(hobbies.length){const b=button(hobby,text('내 취미 즐기기','Enjoy my hobby','自分の趣味を楽しむ'));b.classList.add('command-primary');b.dataset.directSimpleAction='relax';b.dataset.lifeTask='hobby_auto'}
 const addTask=(p,t)=>{const b=button(p,t.labels[lang]);b.dataset.directSimpleAction=t.kind;b.dataset.lifeTask=t.id};
 for(const [group,labels] of [['food',['식사·요리','Food and cooking','食事・料理']],['hygiene',['위생','Hygiene','清潔']],['rest',['휴식·개인시간','Rest and personal time','休息・自分の時間']],['groom',['몸단장','Grooming','身支度']],['chores',['집안일·살림','Household chores','家事']],['sleep',['수면','Sleep','睡眠']]]){const p=createPage(text('생활 · ','Daily life · ','生活・')+labels[lang]);button(life,labels[lang],()=>show(p));LIFE_TASKS.filter(t=>t.group===group).forEach(t=>addTask(p,t))}
 const addSimple=(p,kind)=>{const source=simpleButtons.find(b=>b.dataset.directSimpleAction===kind);if(source){const b=source.cloneNode(true);b.className='command-menu-button';p.append(b)}};
 const hobbyOther=document.createElement('h3');hobbyOther.className='command-section-label';hobbyOther.textContent=text('오늘은 직접 골라볼까요?','Choose something for today','今日は自分で選ぶ');hobby.append(hobbyOther);['read','music','game','art','exercise'].forEach(k=>addSimple(hobby,k));['walk','exercise'].forEach(k=>addSimple(move,k));for(const choice of personalChoices(world,character)){const b=button(self,choice.labels[lang]);if(choice.targetId){b.dataset.directSocialAction=choice.kind;b.dataset.autoTarget=choice.targetId}else{b.dataset.directSimpleAction=choice.kind;b.dataset.lifeTask=choice.lifeTask}}
 for(const task of workTasks(character||{})){const b=button(work,task.labels[lang]);b.dataset.directSimpleAction='work';b.dataset.workTask=task.id}addSimple(work,'study');addSimple(work,'research');
 const targetPage=createPage(text('함께할 상대 고르기','Choose a companion','相手を選ぶ'));targetPage.classList.add('command-target-page');if(targets)targetPage.append(targets);else{const p=document.createElement('p');p.textContent=copy.noTarget;targetPage.append(p)}
 const sections=[['대화','Conversation','会話',['talk','debate','gossip','custom_social']],['연락','Keeping in touch','交流を深める',['hangout','comfort','compliment']],['애정','Affection','愛情',['hug','handhold','lean','kiss','kiss_cautious','kiss_reconcile','affection']],['갈등','Conflict','対立',['taunt','insult','argue','fight']],['선물','Gifts','贈り物',[]],['동행','Together','一緒に',['dine','tea','drinks','cook_together','play_together','study_together','read_together','compete']]];
 for(const [ko,en,ja,kinds] of sections){const p=createPage(text('교류 · ','Social · ','交流・')+text(ko,en,ja));button(exchange,text(ko,en,ja),()=>show(p));if(!kinds.length){button(p,text('우편함에서 선물 보내기','Send a gift from the mailbox','郵便箱から贈り物を送る'),()=>{dialog.close();location.hash='tab=mailbox'});continue}const choose=button(p,text('함께할 상대 고르기','Choose a companion','相手を選ぶ'),()=>show(targetPage));choose.classList.add('command-companion');for(const kind of kinds){const b=socialButtons.find(b=>b.dataset.directSocialAction===kind);if(b){b.hidden=false;b.className='command-menu-button';p.append(b)}}}
 if(payment){payment.hidden=false;payment.classList.add('command-payment');const together=pages.find(p=>titles.get(p)===text('교류 · ','Social · ','交流・')+text('동행','Together','一緒に'));together?.append(payment)}
 submit.hidden=true;command.append(submit);
 command.addEventListener('click',e=>{const auto=e.target.closest('[data-auto-target]');if(auto)command.dataset.directTarget=auto.dataset.autoTarget},true);
 command.addEventListener('click',e=>{const target=e.target.closest('button[data-direct-target]');if(target){command.querySelectorAll('.command-companion').forEach(b=>b.textContent=target.textContent.trim());if(history.length)show(history.pop(),false)}const action=e.target.closest('button[data-direct-social-action]');if(action)queueMicrotask(()=>{if(!command.dataset.directTarget){show(targetPage);return}submit.disabled=false;submit.click()})});
 show(root,false);
}
