import {DISCOVERY_TRAITS} from './discovery-traits.js?v=20260909dev305';
// Contrasting reactions grounded in each situation; existing five actions stay available.
const tri=(ko,en,ja)=>({ko,en,ja});
const rows=[
['early',
 ['상대에게 퍼부을 온갖 욕을 미리 생각한다','Rehearse every insult they want to hurl at the other person','相手に浴びせる罵倒を片っ端から考えておく',{planningStyle:2,interference:2,impulseControl:2},'hostile'],
 ['나보다 늦다니, 사고가 난 게 분명하다며 연락부터 한다','Sure that something happened if they are later, call them immediately','自分より遅いなんて事故に違いないとすぐ連絡する',{planningStyle:-2,emotionalSensitivity:1},'worried'],
 ['혼자 있을 시간이 생겼다며 오히려 마음이 놓인다','Feel relieved to have some time alone','一人の時間ができて、むしろほっとする',{socialStyle:-2,interference:-1},'relieved']],
['rain',
 ['이럴 줄 알고 준비해 둔 우산을 꺼낸다','Take out the umbrella they brought in anticipation','こうなると思って用意した傘を出す',{planningStyle:2,impulseControl:-1},'prepared'],
 ['일단 쌍욕부터 퍼붓는다','Start by letting out a string of curses','まず思い切り悪態をつく',{impulseControl:2,aggressionLevel:2},'hostile'],
 ['젖는 것도 싫지만 낯선 사람들과 붙어 있는 건 더 싫어 자리를 뜬다','Leave: getting wet is preferable to being packed with strangers','濡れるのも嫌だが他人と密着する方が嫌で立ち去る',{socialStyle:-2,impulseControl:1},'avoidant']],
['spill',
 ['그러게 조심했어야지, 자업자득이라고 생각한다','Think they should have been careful; it serves them right','気をつければよかったのに、自業自得だと思う',{decisionStyle:-2,interference:-1},'judging'],
 ['끈적한 음료가 번지는 걸 보자 더러워서 스트레스를 받는다','Feel stressed by the sticky mess spreading across the surface','べたつく飲み物が広がるのを見て汚さにストレスを感じる',{neatness:2,emotionalSensitivity:2},'distressed'],
 ['내 물건은 안 젖었으니 신경 쓰지 않는다','Their belongings are dry, so they pay no attention','自分の物は濡れていないので気にしない',{interference:-2,emotionalContagion:-1},'indifferent']],
['parcel',
 ['누가 책임을 떠넘기려는 건 아닌지 의심하고 손대지 않는다','Suspect someone is shifting responsibility and refuse to touch it','責任を押しつけられそうで手を触れない',{interference:-1,emotionalSensitivity:1},'suspicious'],
 ['통행에 방해된다며 옆으로 밀어놓는다','Push it aside because it is in the way','通行の邪魔だと脇へ寄せる',{interference:2,impulseControl:1},'impatient'],
 ['주인이 애타게 찾고 있을까 봐 한동안 곁에서 기다린다','Wait nearby, worried its owner is desperately looking for it','持ち主が必死に探していそうでしばらくそばで待つ',{decisionStyle:2,diligence:1},'caring']],
['lost',
 ['안내판을 만든 사람에게 따지고 싶어 사진부터 찍는다','Photograph the sign, wanting to complain to whoever made it','案内板の作成者に文句を言いたくてまず写真を撮る',{planningStyle:1,interference:2,aggressionLevel:1},'hostile'],
 ['괜히 아는 척했다가 틀릴까 봐 일행 뒤로 물러난다','Hang back rather than risk pretending to know the way','知ったかぶりで間違えるのが怖くて同行者の後ろに下がる',{socialStyle:-1,emotionalSensitivity:1},'anxious'],
 ['길을 잘못 든 김에 새로운 곳을 구경하자고 한다','Suggest exploring somewhere new while they are off route','道を間違えたついでに新しい場所を見ようと言う',{planningStyle:-2,perceptionStyle:1},'curious']],
['change',
 ['내 시간을 우습게 보느냐며 상대에게 따져 묻는다','Demand to know whether the other person values their time','自分の時間を軽く見ているのかと相手を問い詰める',{interference:2,aggressionLevel:2,impulseControl:1},'hostile'],
 ['오히려 잘됐다며 미뤄 둔 일을 꺼낸다','Welcome the change and turn to a postponed task','かえってよかったと後回しの仕事を始める',{diligence:2,planningStyle:1},'practical'],
 ['괜찮다고 답하지만 종일 그 말이 마음에 걸린다','Say it is fine but dwell on it all day','大丈夫と答えるが一日中気にしてしまう',{emotionalExpression:-1,moodPersistence:2},'hurt']],
['gift',
 ['나중에 뭘 부탁하려는 건지부터 생각한다','First wonder what favor they will be asked for later','後で何を頼まれるのかと先に考える',{decisionStyle:-1,emotionalSensitivity:1},'suspicious'],
 ['내 취향도 모르면서 골랐구나 싶어 서운하다','Feel hurt that the giver seems not to know their taste','自分の好みも知らずに選んだのかと寂しくなる',{emotionalSensitivity:2,moodPersistence:1},'hurt'],
 ['부담스러워서 비슷한 가격의 답례부터 찾아본다','Feel indebted and look for a return gift of similar value','負担に感じて同じくらいの値段のお返しを探す',{planningStyle:2,emotionalSensitivity:1},'anxious']],
['noise',
 ['참다 못해 조용히 하라고 소리친다','Lose patience and shout for quiet','我慢できず静かにしろと叫ぶ',{impulseControl:2,aggressionLevel:2},'hostile'],
 ['괜히 시비가 붙을까 봐 아무 말 못 하고 자리를 피한다','Leave without speaking, afraid of starting a fight','揉めるのが怖くて何も言わずその場を離れる',{socialStyle:-1,interference:-1},'avoidant'],
 ['무슨 일인지 궁금해서 소리 나는 쪽을 살핀다','Look toward the noise, curious about what is happening','何が起きたのか気になって音の方を見る',{perceptionStyle:1,interference:1},'curious']],
['queue',
 ['새치기하는 사람이 없나 계속 감시한다','Keep watch for anyone cutting in','割り込む人がいないか監視し続ける',{interference:2,planningStyle:1},'controlling'],
 ['기다리느니 포기하겠다며 바로 돌아선다','Turn away rather than wait','待つくらいなら諦めるとすぐ引き返す',{impulseControl:2,moodPersistence:-1},'impatient'],
 ['뒤에 힘들어 보이는 사람에게 먼저 가라고 한다','Let someone struggling behind them go first','後ろのつらそうな人に先を譲る',{decisionStyle:2,interference:-1},'caring']],
['cat',
 ['털이 옷에 붙을까 봐 먼저 뒤로 물러난다','Step back before fur gets on their clothes','服に毛がつきそうで先に後ずさる',{neatness:2,interference:-1},'avoidant'],
 ['할 일은 잊고 고양이가 떠날 때까지 지켜본다','Forget their errands and watch until the cat leaves','用事を忘れ猫が去るまで眺める',{planningStyle:-2,diligence:-1},'absorbed'],
 ['혼자 있는 게 걱정되어 주변에 주인이 있나 찾아본다','Look for an owner, worried the cat is alone','一匹なのが心配で周囲に飼い主がいないか探す',{decisionStyle:2,diligence:1},'caring']],
['compliment',
 ['빈말인 걸 안다며 오히려 기분이 상한다','Take offense, convinced it is empty flattery','お世辞だと決めつけてむしろ気分を悪くする',{emotionalSensitivity:2,moodPersistence:1},'suspicious'],
 ['당연한 소리라며 별 반응 없이 받아들인다','Accept it without much reaction as an obvious fact','当然のことだと大した反応もなく受け取る',{emotionalExpression:-1,emotionalSensitivity:-1},'confident'],
 ['들킨 것처럼 얼굴이 달아올라 다른 화제로 돌린다','Flush as if caught out and change the subject','見透かされたように顔が熱くなり話題を変える',{socialStyle:-1,emotionalExpression:1},'shy']],
['crowd',
 ['왜 길 한가운데 서 있느냐며 짜증을 낸다','Snap at people for standing in the middle of the way','なぜ道の真ん中に立つのかといら立つ',{aggressionLevel:2,interference:1},'hostile'],
 ['일행의 옷자락을 놓치지 않으려고 꼭 붙어 간다','Stay close to their companion so they do not lose them','同行者を見失わないようぴったりついていく',{emotionalSensitivity:1,planningStyle:1},'anxious'],
 ['아는 사람이 있을까 봐 얼굴을 돌리고 지나간다','Turn their face away in case someone recognizes them','知り合いがいそうで顔をそらして通り過ぎる',{socialStyle:-2,interference:-1},'avoidant']],
['puzzle',
 ['못 풀겠다는 사실이 자존심 상해 끝까지 붙든다','Keep at it because failing wounds their pride','解けないのが悔しくて最後までしがみつく',{moodPersistence:2,diligence:2},'stubborn'],
 ['재미없다며 답부터 확인한다','Check the answer, declaring it boring','つまらないと言って答えから見る',{impulseControl:2,diligence:-1},'impatient'],
 ['함께 푸는 사람이 틀려도 기죽지 않게 맞장구친다','Encourage the other solver even when they get it wrong','一緒に解く人が間違えても落ち込まないよう相づちを打つ',{decisionStyle:2,emotionalContagion:1},'caring']],
['mistake',
 ['누가 봤는지부터 확인하고 모른 척한다','Check who saw it, then pretend nothing happened','誰が見たか確かめて知らないふりをする',{planningStyle:1,emotionalExpression:-2},'concealing'],
 ['작은 실수인데도 하루를 망쳤다고 자책한다','Blame themself as if the small mistake ruined the day','小さな失敗なのに一日が台無しだと自分を責める',{moodPersistence:2,emotionalSensitivity:2},'distressed'],
 ['내 잘못은 맞지만 사과를 요구받으니 괜히 반발한다','Know they are at fault but resent being told to apologize','自分が悪いとは思うが謝れと言われると反発する',{interference:2,impulseControl:2},'defensive']],
['evening',
 ['하루를 허비했다는 생각에 괜히 주변에 날을 세운다','Feel the day was wasted and snap at those nearby','一日を無駄にした気がして周囲にとげとげしくなる',{aggressionLevel:1,moodPersistence:2},'irritable'],
 ['아무 약속도 없다는 사실이 세상 편하다','Feel completely at ease having no plans','約束が何もないことがこの上なく気楽だ',{socialStyle:-2,energyRhythm:-1},'relieved'],
 ['혼자 있기 싫어 연락처를 한참 뒤적인다','Scroll through contacts, not wanting to be alone','一人でいたくなくて連絡先を長く眺める',{socialStyle:2,emotionalSensitivity:1},'lonely']],
['silence',
 ['나만 말해야 하나 싶어 일부러 입을 다문다','Stay silent on purpose, resentful of doing all the talking','自分ばかり話すのかと思いわざと黙る',{interference:1,moodPersistence:1},'resentful'],
 ['말하지 않아도 되는 사이 같아 편안해진다','Relax, feeling they need not fill the silence','話さなくてもいい仲だと感じて落ち着く',{socialStyle:-1,emotionalSensitivity:-1},'comfortable'],
 ['내가 뭘 잘못 말했나 싶어 방금 대화를 되짚는다','Replay the conversation, wondering what they said wrong','何かまずいことを言ったかと会話を振り返る',{emotionalSensitivity:2,moodPersistence:1},'anxious']],
['seat',
 ['남이 앉았던 온기가 남아 있어 앉기 싫어진다','Do not want to sit where someone’s warmth remains','他人のぬくもりが残っていて座りたくなくなる',{neatness:2,emotionalSensitivity:1},'disgusted'],
 ['다른 사람이 눈치 보기 전에 재빨리 앉는다','Sit quickly before anyone else decides to claim it','他の人が迷っているうちに素早く座る',{impulseControl:2,interference:1},'assertive'],
 ['필요한 사람이 있겠지 싶어 서 있는다','Remain standing in case someone needs it more','必要な人がいるだろうと立ったままでいる',{decisionStyle:2,interference:-1},'caring']],
['postcard',
 ['이제 와서 연락하냐며 읽고도 답하지 않는다','Read it but refuse to reply: why contact them only now?','今さら連絡かと思い、読んでも返事をしない',{moodPersistence:2,interference:-1},'resentful'],
 ['별일 없는 안부인데도 숨은 뜻을 찾아 여러 번 읽는다','Reread a simple greeting for hidden meanings','普通の挨拶なのに裏の意味を探して何度も読む',{perceptionStyle:2,emotionalSensitivity:1},'suspicious'],
 ['반가워서 답장을 기다리게 하지 않으려고 바로 쓴다','Reply at once, delighted and unwilling to keep them waiting','うれしくて待たせたくなく、すぐ返事を書く',{socialStyle:1,diligence:1,decisionStyle:1},'warm']],
['scent',
 ['냄새가 거슬려 표정을 숨기지 못한다','Cannot hide their expression at the unpleasant smell','匂いが気になって表情を隠せない',{emotionalSensitivity:2,emotionalExpression:1},'disgusted'],
 ['누가 이 향을 쓰는지 궁금해 슬쩍 돌아본다','Glance around, curious who wears the scent','誰がこの香りを使っているのか気になってそっと振り返る',{perceptionStyle:1,interference:1},'curious'],
 ['옛 기억이 떠올라 하던 말을 잠깐 멈춘다','Pause mid-sentence when an old memory returns','昔の記憶が浮かんで話を少し止める',{moodPersistence:2,emotionalSensitivity:1},'nostalgic']],
['announcement',
 ['왜 이제야 알려 주냐며 불평한다','Complain that they should have announced it sooner','なぜ今ごろ知らせるのかと不満を言う',{interference:1,aggressionLevel:1},'irritable'],
 ['놓친 내용이 있을까 봐 곁사람에게 다시 확인한다','Check with someone nearby in case they missed anything','聞き逃しがありそうで隣の人に確認する',{planningStyle:2,emotionalSensitivity:1},'careful'],
 ['나와 상관없는 것 같아 끝까지 듣지도 않는다','Stop listening when it seems unrelated to them','自分には関係なさそうで最後まで聞かない',{interference:-2,planningStyle:-1},'indifferent']],
['lamp',
 ['눈이 부셔 짜증을 내며 밝기부터 낮춘다','Lower the brightness, irritated by the glare','まぶしさにいら立って明るさから下げる',{emotionalSensitivity:2,interference:1},'irritable'],
 ['불을 끄면 오늘도 끝인 것 같아 괜히 미룬다','Put off switching it off, reluctant to end the day','消すと今日が終わる気がして先延ばしにする',{moodPersistence:2,planningStyle:-1},'reluctant'],
 ['아직 깨어 있는 사람이 있을까 봐 조용히 확인한다','Quietly check whether anyone is still awake','まだ起きている人がいないか静かに確認する',{decisionStyle:2,planningStyle:1},'caring']],
['tag',
 ['이름이 잘못 적혀 있는지부터 꼼꼼하게 확인한다','Carefully check whether the name is spelled correctly','名前が間違っていないか入念に確認する',{planningStyle:2,neatness:1},'careful'],
 ['모르는 사람이 이름을 부를까 봐 뒤집어 놓는다','Turn it over so strangers cannot call them by name','知らない人に名前を呼ばれたくなくて裏返す',{socialStyle:-2,interference:-1},'private'],
 ['남들이 알아보기 좋게 눈에 띄는 곳에 단다','Place it prominently so others can identify them','分かりやすいよう目立つ場所につける',{socialStyle:2,planningStyle:1},'open']],
['coin',
 ['겨우 동전 하나 때문에 시간을 쓰고 싶지 않아 지나간다','Move on, unwilling to spend time on a single coin','硬貨一枚に時間を使いたくなくて通り過ぎる',{diligence:-1,interference:-2},'indifferent'],
 ['잃어버린 사람은 아쉬울 것 같아 주변에 물어본다','Ask around, thinking the owner may miss it','落とした人は困るかもしれないと周りに聞く',{decisionStyle:2,socialStyle:1},'caring'],
 ['손이 더러워질까 봐 휴지를 꺼내 집는다','Use a tissue to pick it up without dirtying their hands','手が汚れそうでティッシュを出して拾う',{neatness:2,planningStyle:1},'particular']],
['newtable',
 ['왜 내 자리만 불편하냐며 바꾸자고 한다','Demand to switch because their seat is uncomfortable','なぜ自分の席だけ不便なのかと替えるよう言う',{interference:2,impulseControl:1},'demanding'],
 ['낯선 사람과 마주 앉는 게 부담스러워 끝자리로 간다','Take an end seat to avoid facing strangers','他人と向かい合うのが負担で端の席へ行く',{socialStyle:-2,emotionalSensitivity:1},'avoidant'],
 ['다른 사람들이 먼저 고를 때까지 기다린다','Wait until everyone else has chosen','他の人が選び終わるまで待つ',{decisionStyle:1,interference:-2},'considerate']]
];
export function expandDiscovery(events){for(const [id,...choices] of rows){const q=events.find(q=>q.id===id);if(!q)throw Error(id);q.choices.push(...choices.map(([ko,en,ja,effects,stance])=>({text:tri(ko,en,ja),effects,stance})));}}

export function calibrateDiscovery(events){
 const add=(id,ko,en,ja,targets)=>events.find(q=>q.id===id).choices.push({text:tri(ko,en,ja),stance:'violent',effects:Object.fromEntries(Object.keys(targets).map(f=>[f,2])),targets});
 add('rain','화를 못 이겨 옆의 빈 의자를 걷어차고 고함을 지른다','Kick an empty chair and shout in a fit of anger','怒りに任せて脇の空いた椅子を蹴り、大声を上げる',{aggressionLevel:94,impulseControl:92,interference:76});
 add('spill','테이블을 거칠게 밀치며 제대로 치우라고 고함친다','Shove the table and shout at them to clean it up','テーブルを乱暴に押し、きちんと片づけろと怒鳴る',{aggressionLevel:91,impulseControl:89,interference:84,decisionStyle:17});
 add('early','도착한 상대 앞에서 가방을 내던지며 난리를 친다','Throw their bag down and cause a scene when the other person arrives','相手が来ると鞄を投げつけるように置き、騒ぎ立てる',{aggressionLevel:88,impulseControl:93,interference:81});
 for(const q of events)for(const choice of q.choices){
  const targets=Object.fromEntries(Object.keys(DISCOVERY_TRAITS).map(f=>[f,null]));
  for(const [field,effect] of Object.entries(choice.effects))targets[field]=typeof effect==='number'?({2:87,1:68,'-1':33,'-2':13}[effect]??50):effect;
  if(choice.stance!=='violent'&&targets.aggressionLevel!==null)targets.aggressionLevel=choice.effects.aggressionLevel===2?29:18;
  if(q.id==='rain'&&choice.stance==='prepared')Object.assign(targets,{planningStyle:91,impulseControl:16});
  if(q.id==='early'&&choice.stance==='hostile')Object.assign(targets,{planningStyle:81,interference:78,impulseControl:69});
  choice.targets={...targets,...choice.targets};
 }
}
