import {normalizeRoleLinks} from './relationship-roles.js?v=20260909dev305';
export const FAMILY_ARCHIVE_VERSION=1;
const text=(v,max)=>String(v||'').trim().slice(0,max);
export function normalizeFamilyArchive(raw={},members=[]){const ids=new Set(members);return {version:1,clanName:text(raw.clanName,80),motto:text(raw.motto,200),history:text(raw.history,8000),heritage:text(raw.heritage,4000),heritages:(Array.isArray(raw.heritages)?raw.heritages:[]).filter(h=>h&&typeof h==='object').slice(0,30).map((h,i)=>({id:text(h.id,60)||String(i),label:text(h.label,120),kind:['object','property','tradition'].includes(h.kind)?h.kind:'object',successorId:ids.has(h.successorId)?h.successorId:'',notes:text(h.notes,500)})).filter(h=>h.label),roleLinks:normalizeRoleLinks({type:'가족',groupMembers:members,roleLinks:raw.roleLinks}).slice(0,150)};}
export function displayPersonalName(parts){const given=text(parts.given,60),family=text(parts.family,60),middle=text(parts.middle,60);return (parts.order==='family-first'?[family,given,middle]:[given,middle,family]).filter(Boolean).join(' ');}
export function copyFamilyArchive(raw,members){return JSON.stringify({format:'drawer-family',version:1,members,archive:normalizeFamilyArchive(raw,members)},null,2);}
export function pasteFamilyArchive(content,members){if(content.length>100000)throw Error('Family file too large');const value=JSON.parse(content);if(value.format!=='drawer-family'||value.version!==1||!Array.isArray(value.members)||value.members.length!==members.length||new Set(value.members).size!==members.length)throw Error('Family member count does not match');const map=new Map(value.members.map((id,i)=>[id,members[i]]));return normalizeFamilyArchive({...value.archive,heritages:(value.archive?.heritages||[]).map(h=>({...h,successorId:map.get(h.successorId)||''})),roleLinks:(value.archive?.roleLinks||[]).map(l=>({...l,from:map.get(l.from),to:map.get(l.to)}))},members);}

export function familyLegacyLine(relation,actor,other,language='ko',seed=0){const ids=[relation.a,relation.b,...(relation.groupMembers||[])],archive=normalizeFamilyArchive(relation.familyArchive,ids),eligible=archive.heritages.filter(h=>!h.successorId||[actor.id,other.id].includes(h.successorId));if(!eligible.length)return null;const h=eligible[Math.abs(seed)%eligible.length],heir=h.successorId===actor.id?actor.name:h.successorId===other.id?other.name:'';const lines=h.kind==='tradition'?[`가족에게 전해지는 ‘${h.label}’의 순서를 되짚다가${heir?`, 다음에 이어 갈 ${heir}의 이름이 적힌 부분에서 잠시 눈길을 멈췄어요.`:' 기억이 다른 부분을 다시 확인했어요.'}`,`They revisit the steps of the family tradition “${h.label}”${heir?`, pausing where ${heir} is named to carry it on.`:', checking the parts they remember differently.'}`,`家族に伝わる「${h.label}」の手順をたどり${heir?`、次に継ぐ${heir}の名前でふと目を留めました。`:'、記憶の違う部分を確かめました。'}`]:[`‘${h.label}’이 적힌 유산 기록을 다시 읽으며${heir?`, ${heir}에게 이어질 몫을 손끝으로 짚어 보았어요.`:' 아직 정해지지 않은 계승자 자리에 눈길을 두었어요.'}`,`They reread the record of “${h.label}”${heir?`, tracing the part intended for ${heir} with a fingertip.`:', looking at the space where a successor has yet to be named.'}`,`「${h.label}」の遺産記録を読み返し${heir?`、${heir}へ継がれる分を指先でたどりました。`:'、まだ決まっていない継承者の欄を見つめました。'}`];return lines[language==='en'?1:language==='ja'?2:0];}
