import {state,active,updateCharacter,save} from './state.js?v=20260909dev305';
import {displayPersonalName} from './family-archive.js?v=20260909dev305';
export const ownsFamilyPack=info=>info?.entitlements?.familyLegacy===true||(info?.entitlements?.purchases||[]).includes('family_story');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function openFamilyNameEditor(character=active(),onSaved=()=>{}){
 if(!character||!ownsFamilyPack(window.ParallelCityAuth?.getInfo?.()))return;
 const c=character,t=(ko,en,ja)=>({ko,en,ja}[state.uiLanguage]||ko),p=c.nameParts||{given:c.name,family:'',middle:'',order:'given-first'};
 const surnames=[...new Set([...(state.familySurnames||[]),...Object.values(state.characters).map(x=>x.nameParts?.family),p.family].filter(Boolean))];
 const d=document.createElement('dialog');d.className='family-name-dialog directory-create-dialog';d.innerHTML=`<form><h2>${t('이름과 성','Name and surname','名前と姓')}</h2><label>${t('이름','Given name','名')}<input name="given" maxlength="40" value="${esc(p.given)}" required></label><label>${t('성','Surname','姓')}<select name="surname"><option value="">${t('성 없음','No surname','姓なし')}</option>${surnames.map(s=>`<option ${s===p.family?'selected':''}>${esc(s)}</option>`).join('')}</select></label><div class="family-surname-add"><input name="newSurname" maxlength="40" aria-label="${t('새 성','New surname','新しい姓')}"><button type="button" data-add-surname>${t('성 추가','Add surname','姓を追加')}</button></div><label>${t('미들네임 · 선택','Middle name · optional','ミドルネーム・任意')}<input name="middle" maxlength="40" value="${esc(p.middle)}"></label><label>${t('표시 순서','Display order','表示順')}<select name="order"><option value="given-first">${t('이름 · 미들네임 · 성','Given · Middle · Surname','名・ミドルネーム・姓')}</option><option value="family-first">${t('성 · 이름 · 미들네임','Surname · Given · Middle','姓・名・ミドルネーム')}</option></select></label><p data-preview></p><p role="status"></p><footer><button type="button" data-close>${t('닫기','Close','閉じる')}</button><button type="submit">${t('적용','Apply','適用')}</button></footer></form>`;
 const f=d.querySelector('form'),field=n=>f.elements.namedItem(n),status=d.querySelector('[role=status]');field('order').value=p.order||'given-first';
 const parts=()=>({given:field('given').value.trim(),family:field('surname').value,middle:field('middle').value.trim(),order:field('order').value});
 const preview=()=>d.querySelector('[data-preview]').textContent=displayPersonalName(parts());f.oninput=preview;preview();
 d.querySelector('[data-add-surname]').onclick=()=>{const value=field('newSurname').value.trim();if(!value)return;if(![...field('surname').options].some(o=>o.value===value))field('surname').add(new Option(value,value));field('surname').value=value;field('newSurname').value='';preview();};
 d.querySelector('[data-close]').onclick=()=>d.close();d.onclose=()=>d.remove();
 f.onsubmit=e=>{e.preventDefault();if(!ownsFamilyPack(window.ParallelCityAuth?.getInfo?.())||state.characters[c.id]!==c){d.close();return;}const value=parts(),name=displayPersonalName(value);if(!name||name.length>40){status.textContent=t('표시 이름은 1~40자로 입력해 주세요.','Use 1–40 characters for the display name.','表示名は1〜40文字で入力してください。');return;}const before={name:c.name,nameParts:c.nameParts},oldNames=state.familySurnames;updateCharacter(c.id,{name,nameParts:value},false);state.familySurnames=[...new Set([...(oldNames||[]),value.family].filter(Boolean))];if(!save(true)){Object.assign(c,before);state.familySurnames=oldNames;status.textContent=t('저장하지 못했어요. 다시 시도해 주세요.','Could not save. Please retry.','保存できませんでした。再試行してください。');return;}d.close();onSaved();};document.body.append(d);d.showModal();
}
export function bindFamilyNames(refresh){
 if(!ownsFamilyPack(window.ParallelCityAuth?.getInfo?.()))return;
 for(const input of document.querySelectorAll('[data-field="name"]')){const c=active();if(!c)continue;input.readOnly=true;input.setAttribute('aria-haspopup','dialog');input.title=({ko:'이름·성 편집',en:'Edit name and surname',ja:'名前・姓を編集'}[state.uiLanguage]||'');input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();openFamilyNameEditor(c,refresh)}};input.onclick=()=>openFamilyNameEditor(c,refresh);}
}
