// Contextual guides never navigate or execute edits on the user's behalf.
let stop=null,current='';
export function stopContextualGuide(){stop?.();stop=null;current=''}
const routes={
 relationship:[['[data-tab="relationship"]','관계 화면에서 두 주민을 골라요.','Choose two residents in Relationships.','関係画面で二人を選びます。'],['[data-open-view-dialog]','시선은 한 사람이 다른 사람을 어떻게 생각하는지예요.','A view is how one person sees another.','視線は一人が相手をどう思うかです。'],['[data-view-source],[data-view-target]','A → B와 B → A는 달라요. 한쪽 시선을 열어 보세요.','A → B differs from B → A. Open one view.','A → BとB → Aは別です。片方の視線を開いてみましょう。']],
 home:[['[data-room-key]','방을 골라 보세요.','Choose a room.','部屋を選んでみましょう。'],['[data-home-edit],[data-open-room-editor]','방 정보에서 편집할 수 있어요.','Use room information to edit it.','部屋情報から編集できます。'],['[data-room-name],[data-add-room-furniture]','방 이름을 바꾸거나 가구를 하나 놓아 보세요.','Rename a room or place a piece of furniture.','部屋名を変えるか家具を一つ置いてみましょう。']],
 catalog:[['[data-dict-add],[data-add-catalog]','추가를 눌러 새 항목을 만들어요.','Add a new entry.','追加で新しい項目を作ります。'],['[data-dict-field="name"],[data-catalog-field="name"]','이름과 원하는 정보를 채워 주세요.','Enter its name and details.','名前と好きな情報を入力します。'],['[data-dict-save],[data-catalog-save]','저장을 누르면 사전에 등록돼요.','Save to register it in the dictionary.','保存すると辞典に登録されます。']],
 mailbox:[['[data-mail-folder="compose"],[data-player-mail]','쓰기에서 편지를 작성해요.','Write a letter in Compose.','書く画面で手紙を作ります。'],['[data-player-mail] select[name="targetId"]','받을 캐릭터를 고르세요.','Choose the recipient character.','受け取るキャラクターを選びます。'],['[data-mail-gift-picker]','사전에서 선물을 고를 수도 있어요. 내용을 확인한 뒤 직접 보내 주세요.','You can attach a dictionary gift. Review and send the letter yourself.','辞典から贈り物も選べます。内容を確かめて送ってください。']],
 routine:[['[data-add-routine-day],[data-add-routine]','주간 일정의 한 칸을 골라요.','Choose a weekly schedule slot.','週間予定の枠を選びます。'],['[data-routine-character],.routine-sheet-backdrop select','캐릭터와 장소를 지정해요.','Choose a character and location.','キャラクターと場所を指定します。'],['[data-routine-save]','시간을 확인한 뒤 일정을 저장해 주세요.','Check the time, then save the schedule.','時間を確認して予定を保存します。']],
 full:[['input[type="range"][data-field]','성향을 원하는 방향으로 조절할 수 있어요.','Adjust a trait to your preference.','好みに合わせて性格を調整できます。'],['[data-discovery-lock]','자물쇠를 잠그면 질문으로 이 설정이 바뀌지 않아요.','Lock the padlock to protect this setting from questions.','鍵を閉めると質問でこの設定が変わらなくなります。']],
 groups:[['[data-group-slots],.multiplayer-slot-summary,.shared-residents-screen','슬롯은 이 멀티에서 사용할 수 있는 주민 자리예요.','Slots are resident spaces available in this multiplayer village.','スロットはこのマルチ村の住民枠です。'],['[data-group-rules],[data-group-manage="rules"]','만들기와 편집 권한은 방장이 정한 규칙을 따라요.','Creation and editing follow the host’s rules.','作成・編集はホストのルールに従います。'],['[data-group-catalog-publish],[data-group-manage="catalog"]','개인 사전과 공유 사전은 달라요. 이 안내에서는 데이터를 바꾸지 않아요.','Personal and shared dictionaries are separate. This guide makes no changes.','個人辞典と共有辞典は別です。この案内ではデータを変更しません。']]
};
export function contextualGuide(tab,state){
 const route=tab==='character'&&document.querySelector('[data-discovery-lock]')?'full':tab;
 if(stop&&current!==route){stop();stop=null;current=''}
 if(!routes[route]||route==='relationship'&&state.order.length<2)return false;
 const key='drawer-village-feature-tour-v2-'+route;if(localStorage.getItem(key)==='done')return true;if(stop)return true;
 if(document.querySelector('dialog[open]')&&!['full','home','routine'].includes(route))return true;
 current=route;let step=Number(localStorage.getItem(key))||0,frame=0,target=null,layerDialog=null;const lang={ko:1,en:2,ja:3}[state.uiLanguage]||1;
 const card=document.createElement('aside');card.className='intro-tour';card.setAttribute('popover','manual');card.setAttribute('aria-label',['','화면 도움말','Screen guide','画面ガイド'][lang]);const text=document.createElement('p'),nav=document.createElement('nav');card.append(text,nav);document.body.append(card);
 const end=()=>{localStorage.setItem(key,'done');stop?.();stop=null;current=''};
 const next=()=>{step++;if(step>=routes[route].length)return end();localStorage.setItem(key,String(step));paint()};
 const completion={relationship:'view-opened',home:'room-edited',catalog:'catalog-saved',mailbox:'mail-sent',routine:'routine-saved',full:'trait-locked'};
 const advanceFromControl=e=>{if(route==='groups'||step>=routes[route].length-1||!e.target.closest?.(routes[route][step][0]))return;if(e.type==='click'&&e.target.matches('input,select,textarea'))return;if(e.type==='change'&&!String(e.target.value||'').trim())return;next()};document.addEventListener('click',advanceFromControl);document.addEventListener('change',advanceFromControl);
 const signal=e=>{if(e.detail?.name===completion[route])end()};window.addEventListener('drawer-tutorial',signal);
 function paint(){text.textContent=routes[route][step][lang];nav.replaceChildren();if(step<routes[route].length-1||route==='groups'){const b=document.createElement('button');b.textContent=step===routes[route].length-1?['','확인했어요','Got it','確認しました'][lang]:['','다음','Next','次へ'][lang];b.onclick=next;nav.append(b)}const skip=document.createElement('button');skip.textContent=['','안내 그만 보기','End guide','案内を終了'][lang];skip.onclick=end;nav.append(skip)}
 function position(){const nextTarget=[...document.querySelectorAll(routes[route][step][0])].find(e=>e.getBoundingClientRect().width&&!e.closest('[hidden]'));if(nextTarget!==target){target?.classList.remove('intro-tour-target');target=nextTarget;target?.classList.add('intro-tour-target')}const r=target?.getBoundingClientRect(),h=window.visualViewport?.height||innerHeight,ch=card.offsetHeight;card.style.top=Math.max(8,r&&r.top>ch+20?r.top-ch-10:h-ch-12)+'px';const topDialog=[...document.querySelectorAll('dialog[open]')].at(-1)||null;if(topDialog!==layerDialog){layerDialog=topDialog;if(card.matches(':popover-open'))card.hidePopover()}if(card.showPopover&&!card.matches(':popover-open'))card.showPopover();frame=requestAnimationFrame(position)}
 stop=()=>{cancelAnimationFrame(frame);window.removeEventListener('drawer-tutorial',signal);document.removeEventListener('click',advanceFromControl);document.removeEventListener('change',advanceFromControl);target?.classList.remove('intro-tour-target');card.remove()};paint();position();return true;
}
