import {state} from "./state.js?v=20260906dev235";

const esc=value=>String(value??"").replace(/[&<>"]/g,character=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[character]));
const COPY={
  ko:{title:"그룹",intro:"친구들과 같은 그룹에 캐릭터와 집을 모아 함께 마을을 만들어요.",login:"그룹 멀티는 Google 로그인 후 사용할 수 있어요.",loginButton:"Google 로그인",create:"새 그룹 만들기",join:"초대 코드로 참여",name:"그룹 이름",code:"초대 코드",createButton:"그룹 만들기",joinButton:"참여하기",loading:"그룹 정보를 불러오는 중…",empty:"아직 참여한 그룹이 없어요.",residents:"그룹 주민",homes:"방문 가능한 집",members:"멤버와 역할",rules:"그룹 규칙",towns:"그룹 마을",addCharacter:"내 캐릭터 입주",addHome:"내 집 공개",remove:"그룹에서 내보내기",unpublish:"공개 취소",visit:"놀러가기",back:"돌아가기",owner:"그룹장",manager:"관리자",operator:"운영자",member:"멤버",memberLimit:"멤버 1인당 캐릭터",operatorLimit:"운영자 1인당 캐릭터",managerLimit:"관리자 1인당 캐릭터",saveRules:"규칙 저장",newTown:"마을 추가",townName:"새 마을 이름",leave:"그룹 나가기",originalSafe:"여기서 내보내도 계정의 원본 캐릭터와 집은 삭제되지 않아요.",noResidents:"아직 입주한 캐릭터가 없어요.",noHomes:"아직 공개된 집이 없어요.",rooms:"방",residing:"거주 캐릭터",homeVisits:"멤버의 집 방문 허용",selectGroup:"그룹 선택"},
  en:{title:"Groups",intro:"Build shared towns by bringing characters and homes together with friends.",login:"Sign in with Google to use group multiplayer.",loginButton:"Sign in with Google",create:"Create a group",join:"Join with invite code",name:"Group name",code:"Invite code",createButton:"Create group",joinButton:"Join",loading:"Loading groups…",empty:"You have not joined a group yet.",residents:"Group residents",homes:"Homes to visit",members:"Members and roles",rules:"Group rules",towns:"Group towns",addCharacter:"Move in my character",addHome:"Share my home",remove:"Remove from group",unpublish:"Stop sharing",visit:"Visit",back:"Back",owner:"Owner",manager:"Manager",operator:"Operator",member:"Member",memberLimit:"Characters per member",operatorLimit:"Characters per operator",managerLimit:"Characters per manager",saveRules:"Save rules",newTown:"Add town",townName:"New town name",leave:"Leave group",originalSafe:"Removing an item here never deletes the original character or home from its owner's account.",noResidents:"No characters live here yet.",noHomes:"No homes are shared yet.",rooms:"Rooms",residing:"Residents",homeVisits:"Allow member home visits",selectGroup:"Select group"},
  ja:{title:"グループ",intro:"友だちとキャラクターや家を持ち寄り、一緒に村を作れます。",login:"グループ機能はGoogleログイン後に利用できます。",loginButton:"Googleでログイン",create:"新しいグループ",join:"招待コードで参加",name:"グループ名",code:"招待コード",createButton:"グループを作成",joinButton:"参加する",loading:"グループ情報を読み込み中…",empty:"参加中のグループはまだありません。",residents:"グループの住民",homes:"訪問できる家",members:"メンバーと役割",rules:"グループのルール",towns:"グループの村",addCharacter:"自分のキャラクターを入居",addHome:"自分の家を公開",remove:"グループから外す",unpublish:"公開をやめる",visit:"遊びに行く",back:"戻る",owner:"グループ長",manager:"管理者",operator:"運営者",member:"メンバー",memberLimit:"メンバー1人のキャラクター数",operatorLimit:"運営者1人のキャラクター数",managerLimit:"管理者1人のキャラクター数",saveRules:"ルールを保存",newTown:"村を追加",townName:"新しい村の名前",leave:"グループを退出",originalSafe:"ここから外しても、所有者アカウントの元キャラクターや家は削除されません。",noResidents:"入居中のキャラクターはまだいません。",noHomes:"公開中の家はまだありません。",rooms:"部屋",residing:"住民",homeVisits:"メンバーの家への訪問を許可",selectGroup:"グループを選択"}
};
const copy=()=>COPY[state.uiLanguage]||COPY.ko;
const roleLabel=(role,text)=>text[role]||role;
const localAvatar=character=>{
  const source=character?.icon||character?.photo;
  return source?`<img src="${esc(source)}" alt="">`:`<span>${esc((character?.name||"?").slice(0,1))}</span>`;
};
const sharedAvatar=resident=>resident.icon?`<img src="${esc(resident.icon)}" alt="">`:`<span>${esc((resident.name||"?").slice(0,1))}</span>`;

export function renderGroups(){
  const text=copy(),auth=window.ParallelCityAuth?.getInfo?.(),api=window.DrawerVillageGroups,snapshot=api?.getSnapshot?.()||{};
  if(!auth?.user)return `<section class="groups-page groups-login"><header><small>MULTIPLAYER</small><h1>${text.title}</h1><p>${text.intro}</p></header><article><span aria-hidden="true">🏘️</span><p>${text.login}</p><button type="button" class="primary" data-google-login>${text.loginButton}</button></article></section>`;
  const group=snapshot.group,groups=snapshot.groups||[];
  const entryForms=`<div class="group-entry-grid"><form data-group-create><h2>${text.create}</h2><label>${text.name}<input name="name" maxlength="40" required></label><button class="primary" type="submit">${text.createButton}</button></form><form data-group-join><h2>${text.join}</h2><label>${text.code}<input name="code" maxlength="16" autocomplete="off" autocapitalize="characters" required></label><button class="primary" type="submit">${text.joinButton}</button></form></div>`;
  if(snapshot.loading&&!groups.length)return `<section class="groups-page"><header><small>MULTIPLAYER</small><h1>${text.title}</h1><p>${text.loading}</p></header>${entryForms}</section>`;
  if(!group)return `<section class="groups-page"><header><small>MULTIPLAYER</small><h1>${text.title}</h1><p>${text.intro}</p></header>${entryForms}<p class="group-empty-copy">${text.empty}</p></section>`;
  const myMember=(snapshot.members||[]).find(member=>member.uid===auth.user.uid),myRole=myMember?.role||(group.ownerUid===auth.user.uid?"owner":"member"),manager=["owner","manager"].includes(myRole);
  const towns=Array.isArray(group.towns)?group.towns:[],selectedTownId=snapshot.selectedTownId||towns[0]?.id||"";
  const residents=(snapshot.residents||[]).filter(item=>!selectedTownId||item.townId===selectedTownId),homes=(snapshot.homes||[]).filter(item=>!selectedTownId||item.townId===selectedTownId);
  const myResidentIds=new Set((snapshot.residents||[]).filter(item=>item.ownerUid===auth.user.uid).map(item=>item.sourceCharacterId));
  const myHomeIds=new Set((snapshot.homes||[]).filter(item=>item.ownerUid===auth.user.uid).map(item=>item.sourceHomeId));
  const characterOptions=state.order.map(id=>state.characters[id]).filter(Boolean).map(character=>`<button type="button" data-group-add-resident="${esc(character.id)}" ${myResidentIds.has(character.id)?"disabled":""}>${localAvatar(character)}<span><b>${esc(character.name)}</b><small>${esc(character.jobTitle||character.job||"")}</small></span><em>${myResidentIds.has(character.id)?"✓":"＋"}</em></button>`).join("");
  const homeOptions=Object.values(state.homes||{}).map(home=>`<button type="button" data-group-publish-home="${esc(home.id)}" ${myHomeIds.has(home.id)?"disabled":""}><span aria-hidden="true">🏠</span><b>${esc(home.name||"")}</b><em>${myHomeIds.has(home.id)?"✓":"＋"}</em></button>`).join("");
  const residentCards=residents.map(resident=>{
    const removable=resident.ownerUid===auth.user.uid||manager;
    return `<article class="group-resident-card"><span class="group-avatar">${sharedAvatar(resident)}</span><div><b>${esc(resident.name)}</b><small>${esc(resident.job||"")}</small><em>${esc(resident.ownerName||"")}</em></div>${removable?`<button type="button" data-group-remove-resident="${esc(resident.id)}">${text.remove}</button>`:""}</article>`;
  }).join("")||`<p class="group-empty-copy">${text.noResidents}</p>`;
  const visiting=(snapshot.homes||[]).find(home=>home.id===snapshot.visitingHomeId);
  const homeCards=homes.map(home=>{
    const removable=home.ownerUid===auth.user.uid||manager;
    return `<article class="group-home-card"><div class="group-home-picture">${home.exteriorImage?`<img src="${esc(home.exteriorImage)}" alt="">`:`<span aria-hidden="true">🏠</span>`}</div><div><b>${esc(home.name)}</b><small>${esc(home.ownerName||"")} · ${esc(home.kind||"")}</small><p>${text.residing} · ${esc((home.residentNames||[]).join(" · ")||"-")}</p><p>${text.rooms} · ${esc((home.roomNames||[]).join(" · ")||"-")}</p></div><nav>${group.rules?.allowHomeVisits!==false?`<button type="button" data-group-visit-home="${esc(home.id)}">${text.visit}</button>`:""}${removable?`<button type="button" data-group-remove-home="${esc(home.id)}">${text.unpublish}</button>`:""}</nav></article>`;
  }).join("")||`<p class="group-empty-copy">${text.noHomes}</p>`;
  const memberCards=(snapshot.members||[]).map(member=>{
    const locked=member.uid===group.ownerUid||!manager;
    return `<article class="group-member-card"><span>${esc((member.displayName||"?").slice(0,1))}</span><b>${esc(member.displayName||member.uid.slice(0,8))}</b>${locked?`<small>${roleLabel(member.role,text)}</small>`:`<select data-group-member-role="${esc(member.uid)}">${["member","operator","manager"].map(role=>`<option value="${role}" ${role===member.role?"selected":""}>${roleLabel(role,text)}</option>`).join("")}</select>`}${manager&&member.uid!==group.ownerUid?`<button type="button" data-group-remove-member="${esc(member.uid)}">×</button>`:""}</article>`;
  }).join("");
  const rules=group.rules||{};
  return `<section class="groups-page" data-group-id="${esc(group.id)}"><header class="group-page-heading"><div><small>MULTIPLAYER GROUP</small><h1>${esc(group.name)}</h1><p>${text.intro}</p></div><label>${text.selectGroup}<select data-group-select>${groups.map(item=>`<option value="${esc(item.id)}" ${item.id===group.id?"selected":""}>${esc(item.name)}</option>`).join("")}</select></label><div class="group-invite-code"><small>${text.code}</small><button type="button" data-group-copy-code="${esc(group.inviteCode||"")}">${esc(api?.inviteDisplay?.(group.inviteCode)||group.inviteCode||"-")}</button></div></header>
    <nav class="group-town-tabs">${towns.map(town=>`<button type="button" data-group-town="${esc(town.id)}" class="${town.id===selectedTownId?"on":""}">🏘️ ${esc(town.name)}</button>`).join("")}</nav>
    ${visiting?`<article class="group-visit-view"><button type="button" data-group-visit-home="">← ${text.back}</button><div>${visiting.exteriorImage?`<img src="${esc(visiting.exteriorImage)}" alt="">`:`<span aria-hidden="true">🏠</span>`}</div><h2>${esc(visiting.name)}</h2><p>${esc(visiting.ownerName||"")} · ${esc(visiting.kind||"")}</p><dl><div><dt>${text.residing}</dt><dd>${esc((visiting.residentNames||[]).join(" · ")||"-")}</dd></div><div><dt>${text.rooms}</dt><dd>${esc((visiting.roomNames||[]).join(" · ")||"-")}</dd></div></dl></article>`:""}
    <div class="group-main-grid"><section><header><h2>${text.residents}</h2><details><summary>${text.addCharacter}</summary><div class="group-local-picker">${characterOptions}</div></details></header><div class="group-resident-grid">${residentCards}</div></section><section><header><h2>${text.homes}</h2><details><summary>${text.addHome}</summary><div class="group-local-picker group-home-picker">${homeOptions}</div></details></header><div class="group-home-list">${homeCards}</div></section></div>
    <p class="group-original-safety">🔒 ${text.originalSafe}</p>
    <div class="group-admin-grid"><section><h2>${text.members}</h2><div class="group-member-list">${memberCards}</div></section>${manager?`<section><h2>${text.rules}</h2><form data-group-rules><label>${text.memberLimit}<input type="number" name="memberCharacterLimit" min="1" max="100" value="${Number(rules.memberCharacterLimit)||20}"></label><label>${text.operatorLimit}<input type="number" name="operatorCharacterLimit" min="1" max="100" value="${Number(rules.operatorCharacterLimit)||100}"></label><label>${text.managerLimit}<input type="number" name="managerCharacterLimit" min="1" max="100" value="${Number(rules.managerCharacterLimit)||100}"></label><label class="group-check"><input type="checkbox" name="allowHomeVisits" ${rules.allowHomeVisits!==false?"checked":""}>${text.homeVisits}</label><button class="primary" type="submit">${text.saveRules}</button></form><form data-group-add-town><label>${text.townName}<input name="name" maxlength="40" required></label><button type="submit">${text.newTown}</button></form></section>`:`<section><h2>${text.rules}</h2><dl class="group-rule-summary"><div><dt>${text.memberLimit}</dt><dd>${Number(rules.memberCharacterLimit)||20}</dd></div><div><dt>${text.operatorLimit}</dt><dd>${Number(rules.operatorCharacterLimit)||100}</dd></div><div><dt>${text.managerLimit}</dt><dd>${Number(rules.managerCharacterLimit)||100}</dd></div></dl></section>`}</div>
    ${myRole!=="owner"?`<button type="button" class="group-leave-button" data-group-leave>${text.leave}</button>`:""}${entryForms}
  </section>`;
}

export function groupErrorMessage(error){
  const language=state.uiLanguage||"ko",code=error?.code||"";
  const messages={
    ko:{"groups/login-required":"Google 로그인이 필요해요.","groups/name-required":"그룹 이름을 입력해 주세요.","groups/code-invalid":"초대 코드를 다시 확인해 주세요.","groups/code-not-found":"사용할 수 없는 초대 코드예요.","groups/manager-required":"그룹장 또는 관리자만 할 수 있어요.","groups/already-resident":"이미 이 그룹에 입주한 캐릭터예요.","groups/resident-limit":`이 그룹에서 허용한 캐릭터 수는 ${error?.limit||""}명이에요.`,"groups/owner-fixed":"그룹장의 역할은 바꿀 수 없어요.","groups/owner-cannot-leave":"그룹장은 그룹을 나갈 수 없어요."},
    en:{"groups/login-required":"Google sign-in is required.","groups/name-required":"Enter a group name.","groups/code-invalid":"Check the invite code.","groups/code-not-found":"That invite code is unavailable.","groups/manager-required":"Only the owner or a manager can do that.","groups/already-resident":"That character already lives in this group.","groups/resident-limit":`This group allows ${error?.limit||"the configured number of"} characters for your role.`,"groups/owner-fixed":"The owner's role cannot be changed.","groups/owner-cannot-leave":"The owner cannot leave the group."},
    ja:{"groups/login-required":"Googleログインが必要です。","groups/name-required":"グループ名を入力してください。","groups/code-invalid":"招待コードを確認してください。","groups/code-not-found":"利用できない招待コードです。","groups/manager-required":"グループ長または管理者のみ操作できます。","groups/already-resident":"このキャラクターはすでに入居しています。","groups/resident-limit":`この役割で入居できるのは${error?.limit||"設定された人数"}人までです。`,"groups/owner-fixed":"グループ長の役割は変更できません。","groups/owner-cannot-leave":"グループ長は退出できません。"}
  };
  return messages[language]?.[code]||error?.message||({en:"The group action failed.",ja:"グループ操作に失敗しました。",ko:"그룹 작업을 완료하지 못했어요."}[language]);
}
