import {state,save,recordCharacterInteraction} from './state.js?v=20260908dev271';
import {proposalSettings} from './groups.js?v=20260908dev271';
import {buildSharedWorld} from './shared-world.js?v=20260908dev271';
export const mt=(ko,en,ja)=>({ko,en,ja}[state.uiLanguage]||ko);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let folder='inbox',page=0,showCharacterLetters=false;
const snapshot=()=>window.DrawerVillageGroups?.getSnapshot?.()||{};
const storageKey=()=> 'drawer-player-mail:'+ (window.ParallelCityAuth?.getInfo?.()?.user?.uid||'guest');
const localLetters=()=>{try{return JSON.parse(localStorage.getItem(storageKey())||'[]')}catch{return []}};
const status=p=>p.awaitingOthers?mt('다른 참여자 답변 대기','Waiting for other participants','ほかの参加者の返答待ち'):p.status==='pending'?mt('답변 대기','Awaiting response','返答待ち'):p.status==='accepted'?mt('수락됨','Accepted','承認済み'):mt('거절됨','Declined','辞退済み');
function summary(p){return p.kind==='schedule'?mt('일정 제안','Schedule proposal','予定の提案'):p.kind==='characterGroup'?mt('캐릭터 그룹 제안','Character group proposal','キャラクターグループの提案'):p.kind==='admission'?mt('입주 신청','Move-in application','入居申請'):p.kind==='cohabitation'?mt('동거 제안','Shared-home proposal','同居提案'):mt('관계 제안','Relationship proposal','関係の提案')}
export function renderMailbox(legacy){
 const s=snapshot(),shared=!!s.activeGroupId,proposals=folder==='sent'?s.outgoingProposals||[]:s.incomingProposals||[],letters=shared?(folder==='sent'?s.outgoingMail||[]:s.incomingMail||[]):localLetters();
 const rows=[...proposals.map(p=>({...p,proposal:true})),...letters].sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)),slice=rows.slice(page*20,page*20+20);
 const cards=slice.map(p=>`<button type="button" class="mail-row" data-mail-open="${esc(p.id)}" data-mail-proposal="${!!p.proposal}"><small>${esc(p.proposal?summary(p):p.gift?mt('선물','Gift','贈り物'):mt('편지','Letter','手紙'))} · ${p.proposal?status(p):mt('전달됨','Delivered','配達済み')}</small><b>${esc(p.proposal?p.patch?.title||p.patch?.name||p.type:p.subject)}</b><span>${esc(p.sourceName||mt('나','Me','自分'))} → ${esc(p.targetName)}</span><p>${esc(p.proposal?mt('내용을 확인하고 답변할 수 있어요.','Open to review the details and respond.','内容を確認して返答できます。'):p.body)}</p></button>`).join('');
 return `<section class="mail-center"><div class="mail-center-heading"><button type="button" data-tab="observe">←</button><h1>${mt('우편함','Mailbox','郵便箱')}</h1><span>${esc(shared?s.group?.name:mt('내 마을','My town','自分の村'))}</span></div><nav class="mail-folders">${[['inbox',mt('받은 우편','Inbox','受信')],['sent',mt('보낸 우편','Sent','送信済み')],['compose',mt('쓰기','Compose','作成')]].map(([id,label])=>`<button type="button" data-mail-folder="${id}" aria-pressed="${folder===id}">${label}</button>`).join('')}</nav>${folder==='compose'?compose(s):`<div class="mail-list">${cards||`<p>${mt('표시할 우편이 없어요.','No mail to display.','表示する手紙はありません。')}</p>`}</div><nav class="mail-pagination"><button data-mail-page="-1" ${page===0?'disabled':''}>‹</button><span>${page+1}</span><button data-mail-page="1" ${(page+1)*20>=rows.length?'disabled':''}>›</button></nav>${folder==='inbox'?`<details class="mail-character-letters" ${showCharacterLetters?'open':''}><summary>${mt('캐릭터의 편지와 부탁','Character letters and requests','キャラクターからの手紙とお願い')}</summary>${showCharacterLetters?legacy():''}</details>`:''}`}</section>`;
}
const mailCatalog=world=>Object.fromEntries([...new Set([...Object.keys(state.catalog||{}),...Object.keys(world.catalog||{})])].map(k=>[k,[...new Map([...(state.catalog?.[k]||[]),...(world.catalog?.[k]||[])].map(i=>[i.id,i])).values()]]));
function compose(s){
 const world=s.activeGroupId?buildSharedWorld(s,state.uiLanguage):state,uid=window.ParallelCityAuth?.getInfo?.()?.user?.uid,all=Object.values(world.characters),mine=all.filter(c=>!s.activeGroupId||c.ownerUid===uid);
 const options=items=>items.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join(''),items=Object.entries(mailCatalog(world)).filter(([k])=>['food','drink','flower','misc','fashion','perfume','book','toy'].includes(k)).flatMap(([kind,rows])=>(rows||[]).map(item=>({kind,...item})));
 return `<form data-player-mail><label>${mt('보내는 이','From','差出人')}<select name="sourceId"><option value="">${mt('나','Me','自分')}</option>${options(mine)}</select></label><label>${mt('받는 캐릭터','To character','宛先のキャラクター')}<select name="targetId" required>${options(all)}</select></label><label>${mt('제목','Subject','件名')}<input name="subject" maxlength="80" required></label><label>${mt('내용','Message','本文')}<textarea name="body" maxlength="2000" rows="5"></textarea></label><label>${mt('함께 보낼 선물','Gift enclosure','同封する贈り物')}<select name="gift"><option value="">${mt('선물 없이 보내기','No gift','贈り物なし')}</option>${items.map(i=>`<option value="${esc(i.kind+'|'+i.id)}">${esc(i.name)}</option>`).join('')}</select></label><p>${mt('선물은 받는 캐릭터의 보유 물품에 추가돼요.','Gifts are added to the recipient’s inventory.','贈り物は受取人の所持品に追加されます。')}</p><button type="submit" ${all.length?'':'disabled'}>${mt('보내기','Send','送信')}</button></form>`;
}
export function bindMailbox(render,toast){
 const root=document.querySelector('.mail-center');if(!root)return;
 root.querySelector('.mail-character-letters')?.addEventListener('toggle',e=>{if(e.currentTarget.open&&!showCharacterLetters){showCharacterLetters=true;render()}});
 root.querySelectorAll('[data-mail-folder]').forEach(b=>b.onclick=()=>{folder=b.dataset.mailFolder;page=0;render()});
 root.querySelectorAll('[data-mail-page]').forEach(b=>b.onclick=()=>{page=Math.max(0,page+Number(b.dataset.mailPage));render()});
 root.querySelectorAll('[data-mail-open]').forEach(b=>b.onclick=()=>openLetter(b.dataset.mailOpen,b.dataset.mailProposal==='true',render,toast));
 root.querySelector('[data-player-mail]')?.addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{
  const data=Object.fromEntries(new FormData(e.currentTarget)),s=snapshot(),world=s.activeGroupId?buildSharedWorld(s,state.uiLanguage):state,[kind,itemId]=data.gift.split('|'),item=mailCatalog(world)?.[kind]?.find(i=>i.id===itemId),target=world.characters[data.targetId];if(!target||data.sourceId===data.targetId)throw Error(mt('서로 다른 캐릭터를 골라 주세요.','Choose different characters.','別のキャラクターを選んでください。'));
  if(s.activeGroupId)await window.DrawerVillageGroups.sendMail({...data,gift:item?{kind,item:{id:item.id,name:item.name,image:item.image||''}}:null,requestId:crypto.randomUUID()});
  else{if(item){if(data.sourceId)recordCharacterInteraction({type:'gift',actorId:data.sourceId,targetId:data.targetId,itemKind:kind,itemId});else{target.inventory??={};target.inventory[kind]??=[];if(!target.inventory[kind].includes(itemId))target.inventory[kind].push(itemId);save(true)}}const rows=localLetters();rows.push({id:crypto.randomUUID(),...data,sourceName:world.characters[data.sourceId]?.name||mt('나','Me','自分'),targetName:target.name,gift:item?{kind,item:{id:item.id,name:item.name}}:null,createdAt:Date.now()});localStorage.setItem(storageKey(),JSON.stringify(rows.slice(-300)))}
  folder='sent';page=0;toast(mt('우편을 보냈어요.','Mail sent.','送信しました。'));render();
 }catch(err){toast(err.message)}finally{button.disabled=false}});
}
function openLetter(id,proposal,render,toast){
 const s=snapshot(),p=(proposal?[...(s.incomingProposals||[]),...(s.outgoingProposals||[])]:s.activeGroupId?[...(s.incomingMail||[]),...(s.outgoingMail||[])]:localLetters()).find(p=>p.id===id);if(!p)return;
 const uid=window.ParallelCityAuth?.getInfo?.()?.user?.uid,dialog=document.createElement('dialog');dialog.className='mail-reader';
 const schedule=p.kind==='schedule'?`<p>${esc(p.patch.title)} · ${esc(p.patch.date||p.patch.days?.map(d=>mt(['일','월','화','수','목','금','토'][d],['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][d],['日','月','火','水','木','金','土'][d])).join(' · '))}</p><p>${esc(p.patch.start)}–${esc(p.patch.end)}</p><p>${esc(p.patch.notes)}</p>`:'';
 dialog.innerHTML=`<div class="mail-reader-heading"><h2>${esc(proposal?summary(p):p.subject)}</h2><button type="button" data-close-mail>×</button></div><p>${esc(p.sourceName)} → ${esc(p.targetName)}</p>${proposal?`<b>${esc(p.patch?.name||p.type||'')}</b><p>${status(p)}</p>${schedule}${proposalSettings(p,s.residents||[])}${p.reason?`<blockquote>${esc(p.reason)}</blockquote>`:''}`:`<p class="mail-body">${esc(p.body)}</p>${p.gift?`<p>🎁 ${esc(p.gift.item.name)}</p>`:''}`}${proposal&&p.status==='pending'&&p.recipientUid===uid?`<div class="mail-response"><button data-accept-mail>${mt('수락하기','Accept','承認する')}</button><button data-decline-mail>${mt('거절하기','Decline','辞退する')}</button><form data-decline-form hidden><label>${mt('거절 사유 (선택)','Reason (optional)','理由（任意）')}<textarea name="reason" maxlength="500" rows="3"></textarea></label><button type="submit">${mt('거절 답변 보내기','Send decline','辞退の返答を送る')}</button></form></div>`:''}`;
 document.body.append(dialog);dialog.querySelector('[data-close-mail]').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();dialog.querySelector('details')?.setAttribute('open','');
 const respond=async(accept,reason='')=>{dialog.querySelectorAll('button').forEach(b=>b.disabled=true);try{await window.DrawerVillageGroups.respond({proposalId:id,accept,reason});dialog.close();render()}catch(err){toast(err.message);dialog.querySelectorAll('button').forEach(b=>b.disabled=false)}};
 dialog.querySelector('[data-accept-mail]')?.addEventListener('click',()=>respond(true));dialog.querySelector('[data-decline-mail]')?.addEventListener('click',()=>{dialog.querySelector('[data-decline-form]').hidden=false;dialog.querySelector('textarea').focus()});dialog.querySelector('form')?.addEventListener('submit',e=>{e.preventDefault();respond(false,new FormData(e.currentTarget).get('reason'))});dialog.showModal();
}
