import {proposalCopy} from './proposal-copy.js?v=20260909dev305';
import {runBackgroundAction} from './background-actions.js?v=20260909dev305';
import {mailWasRead,markMailRead} from './mail-read-state.js?v=20260909dev305';
import {bindMailRecipients} from './mail-recipients.js?v=20260909dev305';
import {createContactMailbox} from './notification-mail.js?v=20260909dev305';
import {accountStorage} from './account-storage.js?v=20260909dev305';
import {chooseCatalog} from './settings-transfer.js?v=20260909dev305';
import {state,save,recordCharacterInteraction} from './state.js?v=20260909dev305';
import {proposalSettings} from './groups.js?v=20260909dev305';
import {buildSharedWorld} from './shared-world.js?v=20260909dev305';
export const mt=(ko,en,ja)=>({ko,en,ja}[state.uiLanguage]||ko);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function returnMail(p){if(p.kind!=='return')return p;return {...p,subject:mt('캐릭터가 내 마을로 돌아왔습니다.','Your characters returned home.','キャラクターが自分の村に戻りました。'),body:mt(`${p.groupName||'멀티 마을'}에서 떠나 내 마을로 돌아왔습니다. 캐릭터 탭에서 확인해 주세요.`,`Your characters left ${p.groupName||'the multiplayer group'} and returned to your town. Check the Characters tab.`,`${p.groupName||'マルチの村'}を離れ、自分の村へ戻りました。キャラクタータブでご確認ください。`)}}
function senderImage(p,s){if(p.asResponse)return p.responderPhoto||(s.members||[]).find(m=>(m.uid||m.id)===p.recipientUid)?.photoURL||'';if(p.senderPhoto)return p.senderPhoto;const c=state.characters[p.sourceId||p.characterId]||(s.residents||[]).find(c=>c.id===(p.sourceId||p.characterId));if(c){let profile={};try{profile=JSON.parse(c.profileJson||'{}')}catch{}return profile.icon||c.icon||profile.photo||c.photo||''}if(p.sourceId||p.characterId)return '';return (s.members||[]).find(m=>(m.uid||m.id)===p.senderUid)?.photoURL||(!p.senderUid||p.senderUid===window.ParallelCityAuth?.getInfo?.()?.user?.uid?window.ParallelCityAuth?.getInfo?.()?.user?.photoURL:'')||''}
export function letterWatermark(image){return image?`<span class="mail-watermark-clip" aria-hidden="true"><img class="mail-watermark" src="${esc(image)}" alt=""></span>`:''}
let lastMailSources=[];
const mailSources=()=>{const s=snapshot();return [window.ParallelCityAuth?.getInfo?.()?.user?.uid,s.incomingMail,s.outgoingMail,s.incomingProposals,s.outgoingProposals]};
export const mailboxNeedsRefresh=()=>mailSources().some((value,index)=>value!==lastMailSources[index]);
let folder='inbox' ,page=0,redraw=()=>{},announce=()=>{};
function openNotificationMail(){const target=window.DrawerVillageMailTarget,s=snapshot();if(!target?.id||state.activeTab!=='mailbox')return;const proposal=[...(s.incomingProposals||[]).filter(p=>!p.appliedByAuthority),...(s.outgoingProposals||[])].some(p=>p.id===target.id),mail=[...(s.incomingMail||[]),...(s.outgoingMail||[])].some(p=>p.id===target.id);if(!proposal&&!mail)return;window.DrawerVillageMailTarget=null;document.querySelectorAll('.mail-reader[open]').forEach(d=>d.close());openLetter(target.id,proposal,redraw,announce,target.groupId)}
window.addEventListener('drawer-village-groups',openNotificationMail);
const snapshot=()=>window.DrawerVillageGroups?.getSnapshot?.()||{};
const storageKey=()=> 'drawer-player-mail:'+ (window.ParallelCityAuth?.getInfo?.()?.user?.uid||'guest');
const localLetters=()=>{try{return JSON.parse(localStorage.getItem(storageKey())||'[]')}catch{return []}};
const status=p=>p.awaitingOthers?mt('다른 참여자 답변 대기','Waiting for other participants','ほかの参加者の返答待ち'):p.status==='pending'?mt('답변 대기','Awaiting response','返答待ち'):p.status==='accepted'?mt('수락됨','Accepted','承認済み'):mt('거절됨','Declined','辞退済み');
function summary(p){return p.kind==='schedule'?mt('일정 제안','Schedule proposal','予定の提案'):p.kind==='characterGroup'?mt('캐릭터 그룹 제안','Character group proposal','キャラクターグループの提案'):p.kind==='admission'?mt('입주 신청','Move-in application','入居申請'):p.kind==='cohabitation'?mt('동거 제안','Shared-home proposal','同居提案'):mt('관계 제안','Relationship proposal','関係の提案')}
export function proposalTitle(p){return proposalCopy(p,mt).title}
export function proposalBody(p){return proposalCopy(p,mt).body}
export function mailboxRows(selectedFolder='inbox'){
 const folder=selectedFolder;
 const s=snapshot(),shared=!!s.activeGroupId,uid=window.ParallelCityAuth?.getInfo?.()?.user?.uid,proposals=folder==='sent'?s.outgoingProposals||[]:[...(s.incomingProposals||[]).filter(p=>!p.appliedByAuthority),...(s.outgoingProposals||[]).filter(p=>p.respondedAt&&!p.awaitingOthers).map(p=>({...p,asResponse:true,createdAt:p.respondedAt}))],letters=folder==='sent'?[...(s.outgoingMail||[]),...localLetters()]:(s.incomingMail||[]).filter(p=>p.senderUid!==uid);
 const contacts=folder==='inbox'?createContactMailbox(accountStorage).due(null).map(m=>({...m,contact:true,subject:m.title,createdAt:m.at,sourceId:m.extra.characterId,sourceName:state.characters[m.extra.characterId]?.name})):[];
 const q=state.dailyQuestion;if(folder==='inbox'&&q&&!q.answered&&!q.mailId)contacts.push({id:'daily',daily:true,subject:mt('도착한 편지','A letter for you','届いた手紙'),sourceId:q.characterId,sourceName:state.characters[q.characterId]?.name,createdAt:Date.now()});
 const rows=[...proposals.map(p=>({...p,proposal:true})),...contacts,...letters.filter((p,i,rows)=>!p.announcement||!p.dispatchId||rows.findIndex(x=>x.dispatchId===p.dispatchId)===i)].filter(p=>folder==='sent'||!p.createdAt||p.createdAt>Date.now()-30*86400000).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));return rows;
}
export function unreadMailCount(){return mailboxRows().filter(p=>!mailWasRead(p)&&!p.answered).length}
export function renderMailbox(){
 lastMailSources=mailSources();
 const s=snapshot(),rows=mailboxRows(folder),pageSize=Math.max(1,Math.floor((window.innerHeight-310)/100));page=Math.min(page,Math.max(0,Math.ceil(rows.length/pageSize)-1));const totalPages=Math.max(1,Math.ceil(rows.length/pageSize)),slice=rows.slice(page*pageSize,page*pageSize+pageSize);
 const cards=slice.map(returnMail).map(p=>`<button type="button" class="mail-row" ${p.contact?`data-open-contact-mail="${esc(p.id)}"`:p.daily?'data-open-daily-question':`data-mail-open="${esc(p.id)}"`} data-mail-group="${esc(p.groupId||'')}" data-mail-proposal="${!!p.proposal}"><span class="mail-sender-art ${(p.senderKind==='character'||(!p.proposal&&(p.sourceId||p.characterId)))?"is-character":"is-user"}">${senderImage(p,s)?`<img src="${esc(senderImage(p,s))}" alt="">`:'✉'}</span><span class="mail-row-copy"><small>${esc(new Date(p.createdAt||Date.now()).toLocaleDateString(state.uiLanguage==='ja'?'ja-JP':state.uiLanguage==='en'?'en-US':'ko-KR'))}</small><b>${esc(p.proposal?proposalTitle(p):p.subject)}</b><p>${esc(p.proposal?proposalBody(p):p.body)}</p></span><span class="mail-read-label">${p.proposal?status(p):p.answered?mt('답변 완료','Answered','回答済み'):mailWasRead(p)?mt('읽음','Read','既読'):mt('안 읽음','Unread','未読')}</span></button>`).join('');
 return `<section class="mail-center"><div class="mail-center-heading"><button type="button" class="mail-back" data-tab="observe" aria-label="${mt('뒤로','Back','戻る')}"><img src="./assets/home-ui/back.png" alt=""></button><h1><img src="./assets/home-ui/mailbox.png" alt="">${mt('우편함','Mailbox','郵便箱')}</h1><span>${mt('모든 마을의 우편','Mail from every world','すべての村の手紙')}</span></div><nav class="mail-folders">${[['inbox',mt('받은 우편','Inbox','受信')],['sent',mt('보낸 우편','Sent','送信済み')],['compose',mt('쓰기','Compose','作成')]].map(([id,label])=>`<button type="button" data-mail-folder="${id}" aria-pressed="${folder===id}">${label}</button>`).join('')}</nav><p class="mail-retention">${mt('받은 우편은 30일 뒤 삭제돼요.','Received mail is deleted after 30 days.','受信した手紙は30日後に削除されます。')}</p><div class="mail-paper">${folder==='compose'?compose(s):`<div class="mail-list">${cards||`<p>${mt('표시할 우편이 없어요.','No mail to display.','表示する手紙はありません。')}</p>`}</div><nav class="mail-pagination"><button data-mail-page="-1" ${page===0?'disabled':''}>‹ ${mt('이전','Previous','前へ')}</button><span>${page+1} / ${totalPages}</span><button data-mail-page="1" ${(page+1)*pageSize>=rows.length?'disabled':''}>${mt('다음','Next','次へ')} ›</button></nav>`}</div></section>`;
}
const mailCatalog=world=>Object.fromEntries([...new Set([...Object.keys(state.catalog||{}),...Object.keys(world.catalog||{})])].map(k=>[k,[...new Map([...(state.catalog?.[k]||[]),...(world.catalog?.[k]||[])].map(i=>[i.id,i])).values()]]));
function compose(s){
 const world=s.activeGroupId?buildSharedWorld(s,state.uiLanguage):state,uid=window.ParallelCityAuth?.getInfo?.()?.user?.uid,all=Object.values(world.characters),mine=all.filter(c=>!s.activeGroupId||c.ownerUid===uid);
 const options=items=>items.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join(''),items=Object.entries(mailCatalog(world)).filter(([k])=>['food','drink','flower','misc','fashion','perfume','book','toy'].includes(k)).flatMap(([kind,rows])=>(rows||[]).map(item=>({kind,...item})));
 return `<form data-player-mail><label>${mt('보내는 이','From','差出人')}<select name="sourceId"><option value="">${mt('나','Me','自分')}</option>${options(mine)}</select></label><label>${mt('받는 이','To','宛先')}<select name="recipientKind"><option value="character">${mt('캐릭터 선택','Choose a character','キャラクターを選ぶ')}</option>${s.activeGroupId?`<option value="user">${mt('유저 선택','Choose a user','ユーザーを選ぶ')}</option><option value="all">${mt('멀티그룹 전원','Everyone in the group','グループ全員')}</option>`:''}</select><select name="targetId" required>${options(all)}${s.activeGroupId?`<optgroup label="${mt('유저','Members','ユーザー')}">${(s.members||[]).filter(m=>(m.uid||m.id)!==uid).map(m=>`<option value="user:${esc(m.uid||m.id)}">${esc(m.displayName||m.name||mt('구성원','Member','メンバー'))}</option>`).join('')}${s.group?.ownerUid===uid||(s.members||[]).some(m=>(m.uid||m.id)===uid&&['owner','manager','operator'].includes(m.role))?`<option value="announcement">${mt('전체 구성원에게 공지','Announce to all members','全メンバーへお知らせ')}</option>`:''}</optgroup>`:''}</select></label><label>${mt('제목','Subject','件名')}<input name="subject" maxlength="80" required></label><label>${mt('내용','Message','本文')}<textarea name="body" maxlength="500" rows="5"></textarea></label><label>${mt('함께 보낼 선물','Gift enclosure','同封する贈り物')}<select name="gift" hidden aria-hidden="true" tabindex="-1"><option value="">${mt('선물 없이 보내기','No gift','贈り物なし')}</option>${items.map(i=>`<option value="${esc(i.kind+'|'+i.id)}">${esc(i.name)}</option>`).join('')}</select><button type="button" class="mail-gift-picker" data-mail-gift-picker>${mt('사전에서 선물 고르기','Choose a gift from the dictionary','辞典から贈り物を選ぶ')}</button><span data-mail-gift-preview></span><button type="button" class="mail-gift-picker" data-mail-gift-clear hidden>${mt('선물 빼기','Remove gift','贈り物を外す')}</button></label><p>${mt('보내는 캐릭터를 고르면 상대에게 걸어가 선물을 전해요. 선물은 받는 캐릭터의 보유 물품에 추가돼요.','Choose a sending character to walk over and deliver the gift. It is added to the recipient’s inventory.','差出人のキャラクターが歩いて贈り物を届けます。贈り物は受取人の所持品に追加されます。')}</p><button type="submit" ${all.length||s.activeGroupId?'':'disabled'}>${mt('보내기','Send','送信')}</button></form>`;
}
let composeRecipient='';
let mailboxVisible=false;
export function composeAnnouncement(render){composeRecipient='announcement';folder='compose';page=0;if(location.hash==='#tab=mailbox'){state.activeTab='mailbox';render()}else location.hash='tab=mailbox'}
export function bindMailbox(render,toast){
 redraw=render;announce=toast;
 const root=document.querySelector('.mail-center');if(!root){mailboxVisible=false;return}queueMicrotask(openNotificationMail);const entering=!mailboxVisible;mailboxVisible=true;void window.DrawerVillageGroups?.refreshMailbox?.(entering).catch(()=>{if(entering)toast(mt('새 우편을 확인하지 못했어요. 우편함을 다시 열어 주세요.','Could not check new mail. Please reopen the mailbox.','新しい手紙を確認できませんでした。郵便箱を開き直してください。'))});

 root.querySelectorAll('[data-mail-folder]').forEach(b=>b.onclick=()=>{folder=b.dataset.mailFolder;page=0;render()});
 root.querySelectorAll('[data-mail-page]').forEach(b=>b.onclick=()=>{page=Math.max(0,page+Number(b.dataset.mailPage));render()});
 root.querySelectorAll('[data-mail-open]').forEach(b=>b.onclick=()=>openLetter(b.dataset.mailOpen,b.dataset.mailProposal==='true',render,toast,b.dataset.mailGroup));
 const form=root.querySelector('[data-player-mail]');if(form){if(composeRecipient)form.elements.targetId.value=composeRecipient;const recipient=()=>{const user=form.elements.recipientKind.value!=='character';for(const key of ['sourceId','gift']){form.elements[key].disabled=user;if(user)form.elements[key].value=''}};form.elements.targetId.addEventListener('change',()=>{composeRecipient=form.elements.targetId.value;recipient()});form.elements.gift.addEventListener('change',()=>{if(form.elements.gift.value&&!form.elements.sourceId.value){const option=[...form.elements.sourceId.options].find(o=>o.value&&o.value!==form.elements.targetId.value);if(option)form.elements.sourceId.value=option.value}});bindMailRecipients(form,snapshot(),mt,()=>{recipient();form.querySelector('[type=submit]').disabled=form.elements.targetId.disabled||!form.elements.targetId.value;form.querySelector('[data-mail-gift-picker]').disabled=form.elements.gift.disabled},composeRecipient);recipient();const giftButton=form.querySelector('[data-mail-gift-picker]');const paint=()=>{const [kind,id]=form.elements.gift.value.split('|'),world=snapshot().activeGroupId?buildSharedWorld(snapshot(),state.uiLanguage):state,item=mailCatalog(world)[kind]?.find(i=>i.id===id),preview=form.querySelector('[data-mail-gift-preview]');preview.innerHTML=item?`${item.image?`<img src="${esc(item.image)}" alt="">`:''}<b>${esc(item.name)}</b>`:'';form.querySelector('[data-mail-gift-clear]').hidden=!item;giftButton.disabled=form.elements.gift.disabled};form.elements.targetId.addEventListener('change',paint);giftButton.onclick=async()=>{const s=snapshot(),world=s.activeGroupId?buildSharedWorld(s,state.uiLanguage):state,catalog=Object.fromEntries(Object.entries(mailCatalog(world)).filter(([kind])=>['food','drink','flower','misc','fashion','perfume','book','toy'].includes(kind)));const picked=await chooseCatalog(catalog,false,{single:true});if(picked){const [kind,items]=Object.entries(picked)[0];form.elements.gift.value=kind+'|'+items[0].id;form.elements.gift.dispatchEvent(new Event('change'));paint()}};form.querySelector('[data-mail-gift-clear]').onclick=()=>{form.elements.gift.value='';paint()};paint()}
 root.querySelector('[data-player-mail]')?.addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;const data=Object.fromEntries(new FormData(e.currentTarget)),s=snapshot(),account=window.ParallelCityAuth?.getInfo?.()?.user?.uid,requestId=crypto.randomUUID();folder='sent';page=0;render();void runBackgroundAction('mail:'+requestId,async()=>{
  if(window.ParallelCityAuth?.getInfo?.()?.user?.uid!==account)throw Error('Account changed');if(data.recipientKind!=='character'){const userTarget=data.targetId.startsWith('user:'),parts=data.targetId.split(':'),groupId=userTarget?parts[1]:data.recipientKind.slice(6);await window.DrawerVillageGroups.sendMail({...data,groupId,audience:userTarget?'member':'announcement',targetUid:userTarget?parts.slice(2).join(':'):'',recipientScope:data.targetId==='announcement'?'all':data.targetId,requestId});folder='sent';render();return}const world=s.activeGroupId?buildSharedWorld(s,state.uiLanguage):state,[kind,itemId]=(data.gift||'').split('|'),item=mailCatalog(world)?.[kind]?.find(i=>i.id===itemId),target=world.characters[data.targetId];if(!target||data.sourceId===data.targetId)throw Error(mt('서로 다른 캐릭터를 골라 주세요.','Choose different characters.','別のキャラクターを選んでください。'));
  if(s.activeGroupId)await window.DrawerVillageGroups.sendMail({...data,groupId:s.activeGroupId,gift:item?{kind,item:{id:item.id,name:item.name,image:item.image||''}}:null,requestId});
  else{if(item){if(data.sourceId)recordCharacterInteraction({type:'gift',actorId:data.sourceId,targetId:data.targetId,itemKind:kind,itemId});else{target.inventory??={};target.inventory[kind]??=[];if(!target.inventory[kind].includes(itemId))target.inventory[kind].push(itemId);save(true)}}const rows=localLetters();rows.push({id:crypto.randomUUID(),...data,sourceName:world.characters[data.sourceId]?.name||mt('나','Me','自分'),targetName:target.name,gift:item?{kind,item:{id:item.id,name:item.name}}:null,createdAt:Date.now()});localStorage.setItem(storageKey(),JSON.stringify(rows.slice(-300)))}
  folder='sent';page=0;toast(mt('우편을 보냈어요.','Mail sent.','送信しました。'));render();
 });});
}
function openLetter(id,proposal,render,toast,groupId){
 const s=snapshot(),found=(proposal?[...(s.incomingProposals||[]).filter(p=>!p.appliedByAuthority),...(s.outgoingProposals||[])]:[...(s.incomingMail||[]),...(s.outgoingMail||[]),...localLetters()]).find(p=>p.id===id&&(!groupId||p.groupId===groupId||!p.groupId&&s.activeGroupId===groupId));if(!found)return;const p={...returnMail(found)};if(proposal)p.asResponse=folder==='inbox'&&p.senderUid===window.ParallelCityAuth?.getInfo?.()?.user?.uid&&!!p.respondedAt;
 const markRead=folder==='inbox',readScope=accountStorage.scope;
 const uid=window.ParallelCityAuth?.getInfo?.()?.user?.uid,dialog=document.createElement('dialog');dialog.className='mail-reader mail-letter';
 const schedule=p.kind==='schedule'?`<p>${esc(p.patch?.title)} · ${esc(p.patch?.date||p.patch?.days?.map(d=>mt(['일','월','화','수','목','금','토'][d],['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][d],['日','月','火','水','木','金','土'][d])).join(' · '))}</p><p>${esc(p.patch?.start)}–${esc(p.patch?.end)}</p><p>${esc(p.patch?.notes)}</p>`:'';
 dialog.innerHTML=`${!proposal&&p.sourceId?letterWatermark(senderImage(p,s)):""}<div class="mail-letter-content"><div class="mail-reader-heading"><h2>${esc(proposal?proposalTitle(p):p.subject)}</h2><button type="button" data-close-mail>×</button></div><div class="mail-address"><span>${mt('보낸 이','From','差出人')}<b>${esc(proposal?(p.asResponse?p.responderDisplayName:p.senderUid===uid?mt('나','Me','自分'):p.senderDisplayName)||mt('구성원','Member','メンバー'):p.sourceName||mt('나','Me','自分'))}</b></span><span>${mt('받는 이','To','宛先')}<b>${esc(proposal?(p.asResponse||p.recipientUid===uid?mt('나','Me','自分'):p.recipientDisplayName||mt('구성원','Member','メンバー')):p.targetName||'')}</b></span></div>${proposal?`<p class="mail-body">${esc(proposalBody(p))}</p><p class="mail-proposal-status">${status(p)}</p>${schedule}${proposalSettings(p,s.residents||[])}`:`<p class="mail-body">${esc(p.body)}</p>${p.gift?`<p>🎁 ${esc(p.gift.item?.name||p.gift.name||"")}</p>`:''}`}${proposal&&p.status==='pending'&&p.recipientUid===uid?`<div class="mail-response"><button data-accept-mail>${mt('수락하기','Accept','承認する')}</button><button data-decline-mail>${mt('거절하기','Decline','辞退する')}</button><form data-decline-form hidden><label>${mt('거절 사유 (선택)','Reason (optional)','理由（任意）')}<textarea name="reason" maxlength="500" rows="3"></textarea></label><button type="submit">${mt('거절 답변 보내기','Send decline','辞退の返答を送る')}</button></form></div>`:''}</div>`;
 if(p.senderUid&&(p.senderUid!==uid||p.asResponse)&&p.groupId){const safety=document.createElement('button');safety.type='button';safety.dataset.userSafety=p.id;safety.dataset.safetyKind=proposal?'proposal':'mail';safety.dataset.safetyGroup=p.groupId;safety.textContent=mt('신고·계정 차단','Report / block account','通報・アカウントブロック');dialog.querySelector('.mail-letter-content').append(safety)}
 document.body.append(dialog);dialog.querySelector('[data-close-mail]').onclick=()=>dialog.close();dialog.onclose=()=>{dialog.remove();render()};dialog.querySelector('details')?.setAttribute('open','');
 const respond=(accept,reason='')=>{dialog.querySelectorAll('button').forEach(b=>b.disabled=true);dialog.close();void runBackgroundAction('response:'+id,async()=>{if(window.ParallelCityAuth?.getInfo?.()?.user?.uid!==uid)throw Error('Account changed');await window.DrawerVillageGroups.respond({groupId:p.groupId||s.activeGroupId,proposalId:id,accept,reason});if(state.activeTab==='mailbox')render()})};
 dialog.querySelector('[data-accept-mail]')?.addEventListener('click',()=>respond(true));dialog.querySelector('[data-decline-mail]')?.addEventListener('click',()=>{dialog.querySelector('[data-decline-form]').hidden=false;dialog.querySelector('textarea').focus()});dialog.querySelector('form')?.addEventListener('submit',e=>{e.preventDefault();respond(false,new FormData(e.currentTarget).get('reason'))});dialog.showModal();
 // Display the letter before a full-device receipt write can trigger snapshot compression.
 if(markRead)requestAnimationFrame(()=>setTimeout(()=>{if(accountStorage.scope===readScope)markMailRead(p)},0));
}
