import {needsAt,needLabel} from './life-needs.js';
import {relationMetrics,RELATION_METRICS} from './relationship-metrics.js';
import {recommendedContextActions,contextGroups} from './context-actions.js?v=20260909dev305';
export function occupantPanel({world,character,actor,canSelect,onSelect,execute,close,openActivities}){
 const lang=world.uiLanguage||'ko',tr=(ko,en,ja)=>({ko,en,ja}[lang]||ko),root=document.createElement('section');root.className='occupant-life-panel';
 const self=actor?.id===character.id,head=document.createElement('header'),title=document.createElement('h3');title.textContent=self?tr('지금의 욕구','Current needs','今の欲求'):tr('두 사람의 관계','Their relationship','二人の関係');head.append(title);
 if(canSelect){const crown=document.createElement('button');crown.type='button';crown.className='occupant-crown';crown.dataset.occupantCrown=character.id;crown.setAttribute('aria-pressed',String(self));crown.setAttribute('aria-label',self?tr('현재 기준 캐릭터','Current viewpoint character','現在の基準キャラクター'):tr('이 캐릭터를 기준으로','Use this character as viewpoint','このキャラクターを基準にする'));crown.innerHTML='<svg viewBox="0 0 32 26" aria-hidden="true"><path d="M3 5 10 11 16 2 22 11 29 5 26 22H6Z"/><path d="M7 18H25"/></svg>';const text=document.createElement('span');text.textContent=self?tr('기준','Viewpoint','基準'):tr('기준으로','Use viewpoint','基準に');crown.append(text);crown.onclick=()=>onSelect(character.id);head.append(crown)}root.append(head);
 const metrics=self?needsAt(character):actor?relationMetrics(world,actor.id,character.id):null;
 if(metrics){const grid=document.createElement('div');grid.className='occupant-meter-grid';for(const [key,value] of Object.entries(metrics)){const row=document.createElement('label'),name=document.createElement('span'),meter=document.createElement('meter'),score=document.createElement('b');name.textContent=self?needLabel(key,lang):RELATION_METRICS[key][{ko:0,en:1,ja:2}[lang]||0];meter.min=0;meter.max=100;meter.value=value;meter.setAttribute('aria-label',name.textContent);score.textContent=Math.round(value)+'/100';row.append(name,meter,score);grid.append(row)}root.append(grid)}
 const hint=document.createElement('p');hint.className='occupant-panel-hint';hint.textContent=self?(character.needsFixed?tr('욕구가 현재 값으로 고정되어 있어요.','Needs are frozen at their current values.','欲求は現在の値で固定されています。'):tr('100에 가까울수록 충분히 충족된 상태예요.','Closer to 100 means more satisfied.','100に近いほど満たされた状態です。')):actor?`${actor.name} → ${character.name}`:tr('왕관으로 기준 캐릭터를 선택해 주세요.','Choose a viewpoint character with the crown.','王冠で基準キャラクターを選んでください。');root.append(hint);
 if(!self&&actor){const target={type:'person',id:character.id},actions=document.createElement('div'),status=document.createElement('p');actions.className='occupant-actions';status.setAttribute('role','status');
  const paint=(items,back)=>{actions.replaceChildren();if(back){const b=document.createElement('button');b.textContent=tr('‹ 뒤로','‹ Back','‹ 戻る');b.onclick=back;actions.append(b)}for(const action of items){const b=document.createElement('button');b.type='button';b.dataset.occupantAction=action.kind;b.textContent=action.label[lang]||action.label.ko;b.onclick=async()=>{actions.querySelectorAll('button').forEach(b=>b.disabled=true);status.textContent=tr('행동을 준비하고 있어요…','Preparing…','準備しています…');try{if(await execute(actor.id,action,target))close();else status.textContent=tr('지금은 이 행동을 할 수 없어요.','This action is not available now.','今はこの行動ができません。')}catch(e){status.textContent=e.message}finally{actions.querySelectorAll('button').forEach(b=>b.disabled=false)}};actions.append(b)}};
  const initial=()=>{paint(recommendedContextActions(target,world,actor));const more=document.createElement('button');more.textContent=tr('다른 상호작용','More interactions','ほかの交流');more.className='occupant-actions-more';more.onclick=()=>{actions.replaceChildren();for(const group of contextGroups(target,actor)){const b=document.createElement('button');b.textContent=group.label[lang]||group.label.ko;b.onclick=()=>paint(group.actions,initial);actions.append(b)}};actions.append(more)};initial();root.append(actions,status);
 }
 if(openActivities&&(self||actor)){const all=document.createElement('button');all.type='button';all.className='occupant-actions-more';all.dataset.occupantAllActivities='';all.textContent=tr('모든 할 일 보기','All activities','すべての行動');all.onclick=()=>{close();openActivities(self?character.id:actor.id)};root.append(all)}
 return root;
}
