import {renderCourt} from './court-ui.js';
import {state} from './state.js?v=20260909dev305';
const t=(ko,en,ja)=>({ko,en,ja}[state.uiLanguage]||ko),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const image=p=>/^(https?:|data:image\/(png|jpeg|webp);|\.\/)/i.test(p||'')?p:'./assets/home-ui/profile-placeholder.png';
export async function gameLobby(body,{groups,selected,call,current,open,setup,join,manage}){
 body.innerHTML=`<form class="plaza-invite"><label>${t('멀티 초대 코드','Multiplayer invite code','マルチ招待コード')}<input name="code" required maxlength="80" autocomplete="off"></label><button>${t('참여하기','Join','参加')}</button></form><nav class="plaza-tabs"></nav><section class="plaza-paper"><header><b data-lobby-count></b><select data-game-sort aria-label="${t('정렬','Sort','並べ替え')}"><option value="recent">${t('최신순','Newest','新しい順')}</option><option value="seats">${t('빈자리순','Open seats','空席順')}</option></select></header><div class="plaza-game-grid"></div><p role="status"></p><button data-court-open>${t('궁정 이야기 · 그룹 배경','Court stories · group setting','宮廷の物語・グループ背景')}</button><button data-game-create-open>${t('놀이 열기','Host a game','ゲームを開く')}</button><button data-game-multi>${t('멀티 만들기 · 관리','Create / manage multiplayer','マルチの作成・管理')}</button></section>`;
 body.querySelector('[data-court-open]').onclick=()=>renderCourt(body,{groups,selected,back:()=>gameLobby(body,{groups,selected,call,current,open,setup,join,manage}),current});
 const tabs=body.querySelector('.plaza-tabs'),grid=body.querySelector('.plaza-game-grid'),status=body.querySelector('[role=status]');let revision=0,entries=[];const live=()=>current()&&grid.isConnected;
 body.querySelector('.plaza-invite').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{await join(new FormData(e.target).get('code'))}catch{if(current()){status.textContent=t('초대 코드와 로그인 상태를 확인해 주세요.','Check your invite code and sign-in status.','招待コードとログイン状態を確認してください。');button.disabled=false}}};
 body.querySelector('[data-game-multi]').onclick=manage;
 function paint(){const sort=body.querySelector('[data-game-sort]').value;const games=[...entries].sort((a,b)=>sort==='seats'?(b.capacity-b.players.length)-(a.capacity-a.players.length):b.createdAt-a.createdAt);body.querySelector('[data-lobby-count]').textContent=t(`진행·모집 중 ${games.length}개`,`${games.length} active games`,`開催中・募集中 ${games.length}件`);grid.innerHTML=games.map(g=>`<button class="plaza-game-tile" data-game="${esc(g.id)}" data-group="${esc(g.groupId)}"><img src="${esc(image(g.host?.photo))}" alt=""><b>${esc(g.name)}</b><small>${esc(g.groupName)}</small><small>${g.status==='playing'?t('진행 중','Playing','進行中'):t('모집 중','Recruiting','募集中')} · ${g.players.length}/${g.capacity}</small></button>`).join('');grid.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>open(b.dataset.group,b.dataset.game));grid.querySelectorAll('img').forEach(i=>i.onerror=()=>{i.onerror=null;i.src='./assets/home-ui/profile-placeholder.png'})}
 async function select(id){selected=id;const token=++revision;entries=[];tabs.innerHTML=[{id:'',name:t('전체','All','すべて')},...groups].map(g=>`<button aria-pressed="${g.id===id}" data-filter="${esc(g.id)}">${esc(g.name)}</button>`).join('');tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>select(b.dataset.filter));status.textContent=t('불러오는 중…','Loading…','読み込み中…');paint();const queue=(id?groups.filter(g=>g.id===id):groups).slice();let failed=false;await Promise.all(Array.from({length:Math.min(3,queue.length)},async()=>{while(queue.length){const group=queue.shift();try{const data=await call('readGames',{groupId:group.id});if(!live()||token!==revision)return;entries.push(...data.games.filter(g=>['playing','recruiting'].includes(g.status)).map(g=>({...g,groupId:group.id,groupName:group.name})));paint()}catch{failed=true}}}));if(live()&&token===revision)status.textContent=failed?t('일부 게임을 불러오지 못했어요. 마을 탭을 눌러 다시 확인해 주세요.','Some games could not load. Select a village to retry.','一部のゲームを読み込めませんでした。村を選んで再試行してください。'):entries.length?'':t('아직 열린 놀이가 없어요. 함께할 멀티를 선택해 열어 보세요.','No games yet. Choose a multiplayer village to host one.','まだゲームはありません。マルチの村を選んで開いてみましょう。')}
 body.querySelector('[data-game-sort]').onchange=paint;body.querySelector('[data-game-create-open]').onclick=()=>setup(selected||groups[0]?.id||'');await select(selected);
}
export function gameSetup(body,data,{back,submit,saveConsent}){
 body.innerHTML=`<button data-setup-back>${t('게임 목록','Game list','ゲーム一覧')}</button><form class="game-create plaza-setup"><label>${t('게임 이름','Game name','ゲーム名')}<input name="name" maxlength="60" required value="${t('마피아 놀이','Mafia game','マフィアゲーム')}"></label><div class="plaza-setup-row"><label>${t('게임 유형','Game type','ゲームの種類')}<select disabled><option>${t('마피아 게임','Mafia game','マフィアゲーム')}</option></select></label><label>${t('게임 인원','Players','参加人数')}<select name="capacity">${[4,5,6,7,8,9,10].map(n=>`<option ${n===5?'selected':''}>${n}</option>`).join('')}</select></label></div><label>${t('참가 캐릭터','Your character','参加キャラクター')}<select name="character" required>${data.characters.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}</select></label><p>${t('선택한 마을의 내 캐릭터로 참가해요.','Join as one of your characters in the selected village.','選んだ村の自分のキャラクターで参加します。')}</p><label>${t('무대가 될 마을','Village stage','舞台の村')}<select name="town">${(data.towns||[]).map(v=>`<option value="${esc(v.id)}">${esc(v.name)}</option>`).join('')}</select></label><dl class="plaza-rules"><dt>${t('마피아','Mafia','マフィア')}</dt><dd><select name="mafiaCount" aria-label="${t('마피아 수','Mafia count','マフィア人数')}"><option>1</option><option>2</option><option>3</option></select></dd>${[['moveSeconds',t('이동 선택','Choose destination','移動先の選択')],['actionSeconds',t('건물 안 행동','Action inside','建物内の行動')],['meetingSeconds',t('회의 최대 시간','Maximum meeting time','会議の制限時間')]].map(([key,label])=>`<dt>${label}</dt><dd><select name="${key}" aria-label="${label}">${(key==='meetingSeconds'?[60,120,180,300,600]:[15,30,45,60,90,120]).map(n=>`<option value="${n}" ${n===(key==='meetingSeconds'?300:45)?'selected':''}>${n}${t('초',' sec','秒')}</option>`).join('')}</select></dd>`).join('')}</dl><p role="status" data-game-status></p><button ${!data.manager||!data.characters.length?'disabled':''}>${t('게임 열기','Create game','ゲームを開く')}</button></form><details class="plaza-consent"><summary>${t('내 캐릭터 자동 참가 설정','My characters’ automatic participation','自分のキャラクターの自動参加設定')}</summary><form class="game-create" data-game-consent>${data.characters.map(c=>`<label class="plaza-npc"><input type="checkbox" name="character" value="${esc(c.id)}" ${data.consent.includes(c.id)?'checked':''}>${esc(c.name)}</label>`).join('')}<p>${t('다음에 개설되는 놀이에서만 적용돼요.','Applies to future games.','次に開かれるゲームから適用されます。')}</p><button>${t('설정 저장','Save settings','設定を保存')}</button><p role="status"></p></form></details>`;
 body.querySelector('[data-game-consent]').onsubmit=async e=>{e.preventDefault();const f=e.target,b=f.querySelector('button');b.disabled=true;try{await saveConsent(new FormData(f).getAll('character'));f.querySelector('[role=status]').textContent=t('저장했어요.','Saved.','保存しました。')}catch{f.querySelector('[role=status]').textContent=t('저장하지 못했어요. 다시 시도해 주세요.','Could not save. Try again.','保存できませんでした。再試行してください。')}finally{b.disabled=false}};
 function capacity(){const max=Math.floor((Number(body.querySelector('[name=capacity]').value)-1)/2),select=body.querySelector('[name=mafiaCount]');for(const option of select.options)option.disabled=Number(option.value)>max;if(Number(select.value)>max)select.value=String(max);}
 capacity();body.querySelector('[data-setup-back]').onclick=back;body.querySelector('[name=capacity]').onchange=capacity;body.querySelector('form').onsubmit=e=>{e.preventDefault();submit(new FormData(e.target))};
}
export function liveActionMap(g,p){
 const period=[t('아침','Morning','朝'),t('점심','Afternoon','昼'),t('저녁','Evening','夕方')][Math.floor((g.actionTick||0)/2)];
 return `<section class="plaza-action-map"><header><img src="${esc(image(p.photo))}" alt=""><b>${esc(p.name)}</b><span>${g.day}${t('일차',' · day','日目')} · ${period}</span><strong data-live-clock></strong></header><div class="plaza-map-locations">${g.locations.map((l,i)=>`<button type="button" data-action-location="${esc(l.id)}" style="left:${18+(i%3)*31}%;top:${22+Math.floor(i/3)*25}%"><img src="./assets/home-ui/home.png" alt=""><small>${esc(l.name)}</small></button>`).join('')}</div><div class="plaza-map-choice"><b data-selected-place>${esc(g.locations.find(l=>l.id===p.place)?.name||'')}</b><label>${t('장소','Place','場所')}<select name="place0">${g.locations.map(l=>`<option value="${esc(l.id)}" ${l.id===p.place?'selected':''}>${esc(l.name)}</option>`).join('')}</select></label><label>${t('행동','Action','行動')}<select name="kind0"><option value="task">${t('임무 하기','Work on a task','任務をする')}</option><option value="investigate">${t('흔적 조사하기','Investigate traces','痕跡を調べる')}</option><option value="move">${t('이동하기','Move','移動する')}</option>${p.role==='mafia'?`<option value="sabotage">${t('방해하기','Sabotage','妨害する')}</option><option value="tag">${t('술래 지목','Tag','指名する')}</option>`:''}</select></label></div></section>`;
}
