import {state,save} from './state.js?v=20260909dev305';
import {buildSharedWorld} from './shared-world.js?v=20260909dev305';
import {preparedFoods,foodRemaining,foodSpoiled,actOnFood} from './prepared-food.js';
import {savedRecipeById} from './cooking.js';
import {recipeName} from './recipe-localizations.js';
import {recipeIcon} from './cooking-display.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const tr=(language,ko,en,ja)=>({ko,en,ja}[language]||ko);
export function roomFoodMarkup(world,homeId,room,now=Date.now()){
 return preparedFoods(world).filter(({dish})=>dish.homeId===homeId&&dish.room===room&&dish.storage!=='fridge').map(({dish},index)=>{const recipe=savedRecipeById(dish.recipeId),spoiled=foodSpoiled(dish,now),name=recipe?recipeName(recipe,world.uiLanguage):dish.recipeId;return `<button type="button" class="prepared-food ${spoiled?'is-spoiled':''}" data-prepared-food="${esc(dish.id)}" style="left:${dish.x}%;top:${dish.y}%;--food-shift:${index%4*8}px" aria-label="${esc(name+(spoiled?' · '+tr(world.uiLanguage,'상했어요','Spoiled','傷んでいます'):''))}"><span>${recipeIcon(recipe||{})}</span>${spoiled?'<i aria-hidden="true">〰️</i>':''}</button>`}).join('');
}
function context(){const s=window.DrawerVillageGroups?.getSnapshot?.(),snapshot=s?.activeGroupId&&s.group?s:null;return {world:snapshot?buildSharedWorld(snapshot,state.uiLanguage):state,snapshot}}
const node=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n};
export function openPreparedFood(dishId){
 const initial=context(),uid=window.ParallelCityAuth?.getInfo?.()?.user?.uid,groupId=initial.snapshot?.activeGroupId||'',{world}=initial,lang=state.uiLanguage,text=(ko,en,ja)=>tr(lang,ko,en,ja),found=preparedFoods(world).find(x=>x.dish.id===dishId);if(!found)return;
 const {dish}=found,recipe=savedRecipeById(dish.recipeId),home=world.homes[dish.homeId],d=node('dialog');d.className='career-dialog';const head=node('header'),close=node('button','×');close.onclick=()=>d.close();head.append(node('h2',recipe?recipeName(recipe,lang):dish.recipeId),close);d.append(head);const body=node('section');body.className='career-body';d.append(body);
 const remaining=foodRemaining(dish),hours=Math.ceil(remaining/(dish.storage==='fridge'?.25:1)/3600000);body.append(node('p',remaining?text(`약 ${hours}시간 후 상해요.`,`Spoils in about ${hours} hours.`,`約${hours}時間後に傷みます。`):text('상한 음식이에요. 버릴 수 있어요.','This food has spoiled. You can discard it.','傷んだ料理です。捨てられます。')));
 const actor=node('select');actor.setAttribute('aria-label',text('캐릭터','Character','キャラクター'));for(const c of Object.values(world.characters).filter(c=>(!initial.snapshot||c.ownerUid===uid)&&(c.homeId===home.id||c.residences?.some(r=>r.homeId===home.id))))actor.add(new Option(c.name,c.id,false,c.id===world.activeId));body.append(actor);
 const room=node('select');room.setAttribute('aria-label',text('옮길 방','Destination room','移動先の部屋'));for(const [key,value]of Object.entries(home.rooms||{}))room.add(new Option(value.name||key,key,false,key===dish.room));body.append(room);
 const surface=node('select');surface.setAttribute('aria-label',text('놓을 곳','Surface','置く場所'));const surfaces=()=>{surface.replaceChildren(new Option(text('방 안','In the room','部屋の中'),''));for(const p of home.rooms[room.value]?.furniturePlacements||[])if(/카운터|조리대|식탁|탁자|counter|table/i.test(p.item||''))surface.add(new Option(p.item,p.id,false,p.id===dish.furnitureId))};room.onchange=surfaces;surfaces();body.append(surface);
 const status=node('p');status.setAttribute('role','status');let busy=false;
 const run=async action=>{if(busy||!actor.value)return;const fresh=context();if((fresh.snapshot?.activeGroupId||'')!==groupId||window.ParallelCityAuth?.getInfo?.()?.user?.uid!==uid)return d.close();busy=true;body.querySelectorAll('button').forEach(b=>b.disabled=true);try{const options={room:room.value,furnitureId:action==='move'?surface.value:''};if(fresh.snapshot)await window.DrawerVillageGroups.command({kind:'food',characterId:actor.value,dishId,action,options});else{const previous=structuredClone(fresh.world.characters);try{actOnFood(fresh.world,actor.value,dishId,action,options);if(!await save(true))throw Error('save-failed')}catch(e){Object.assign(fresh.world.characters,previous);throw e;}}d.close();window.dispatchEvent(new Event('drawer-money-updated'));}catch(e){status.textContent=e.message==='food-fridge'?text('선택한 방에 냉장고가 필요해요.','The selected room needs a refrigerator.','選択した部屋に冷蔵庫が必要です。'):text('음식 상태와 권한을 확인한 뒤 다시 시도해 주세요.','Check the food and your access, then retry.','料理の状態と権限を確認し、再試行してください。');busy=false;buttons();}};
 const controls=node('nav');body.append(controls,status);const buttons=()=>{controls.replaceChildren();for(const [action,ko,en,ja]of [['eat','먹기','Eat','食べる'],['move','옮기기','Move','移動'],['fridge','냉장고에 넣기','Refrigerate','冷蔵庫に入れる'],['discard','버리기','Discard','捨てる']]){const b=node('button',text(ko,en,ja));b.type='button';b.disabled=!actor.value||action==='eat'&&!remaining||action==='discard'&&actor.value!==found.owner.id;b.onclick=()=>run(action);controls.append(b)}};actor.onchange=buttons;buttons();d.onclose=()=>d.remove();document.body.append(d);d.showModal();return d;
}
if(globalThis.document)document.addEventListener('click',event=>{const b=event.target.closest?.('[data-prepared-food]');if(!b)return;event.preventDefault();event.stopImmediatePropagation();openPreparedFood(b.dataset.preparedFood)},true);
