import {runBackgroundAction} from './background-actions.js?v=20260909dev285';
import {createCharacter,emptyWorld,runIsolatedWorld} from './state.js?v=20260909dev285';
import {withTownEditDraft,stageTownEdit,commitTownEdit,townEditDraft,discardTownEdit} from './town-edit-draft.js?v=20260909dev285';
import {bindSharedHome} from './shared-home-editor.js?v=20260909dev285';
import {residentText} from './shared-residents.js?v=20260909dev285';
import {sharedSelection,withSharedWorld,decodeShared,buildSharedWorld} from './shared-world.js?v=20260909dev285';
import {state} from './state.js?v=20260909dev285';
import {renderGroupRelations} from './groups.js?v=20260909dev285';
const messages={"다른 구성원이 먼저 수정했어요. 새 배치를 확인한 뒤 다시 시도해 주세요.":["Another member edited this town. Refresh the layout and try again.","他のメンバーが先に編集しました。配置を確認してもう一度お試しください。"],"저장하지 못했어요":["Could not save.","保存できませんでした。"],"건물 편집 권한이 필요해요":["Building editing permission is required.","建物の編集権限が必要です。"],"내 캐릭터의 시선만 설정할 수 있어요":["You can only edit your own character’s viewpoint.","自分のキャラクターの視線だけを設定できます。"],"관계 제안을 보냈어요":["Relationship proposal sent.","関係の提案を送りました。"],"저장했어요":["Saved.","保存しました。"],"이 항목의 공유 편집 연결은 준비 중이에요":["Shared editing for this item is not available yet.","この項目の共有編集は準備中です。"],"이 시선 설정을 초기화할까요?":["Reset this viewpoint?","この視線設定を初期化しますか？"],"이 건물을 삭제할까요?":["Delete this building?","この建物を削除しますか？"],"삭제할까요?":["Delete this item?","削除しますか？"],"내 마을":["My town","自分のタウン"]};
const tr=text=>messages[text]?.[{en:0,ja:1}[state.uiLanguage]]||text;
const api=()=>window.DrawerVillageGroups, snapshot=()=>withTownEditDraft(api()?.getSnapshot?.()),uid=()=>window.ParallelCityAuth?.getInfo?.()?.user?.uid;
export const activeShared=()=>{const s=snapshot();return s?.activeGroupId&&s.group?s:null};
export const canEditShared=s=>['owner','manager','operator'].includes(s.members?.find(m=>(m.uid||m.id)===uid())?.role||s.role||(s.group?.ownerUid===uid()?'owner':''));
const town=s=>s.group.towns?.find(t=>t.id===s.selectedTownId)||s.group.towns?.[0];
let serial=Promise.resolve();
function enqueue(run,toast){const next=serial.then(run);serial=next.catch(e=>toast(e.code==='groups/edit-conflict'?'다른 구성원이 먼저 수정했어요. 새 배치를 확인한 뒤 다시 시도해 주세요.':e.message||e.code||'저장하지 못했어요'));return next.catch(()=>false)}
function applyTown(s,result){if(result.town&&activeShared()?.activeGroupId===s.activeGroupId){const current=snapshot();current.group.towns=current.group.towns.map(t=>t.id===result.town.id?result.town:t);current.group.buildingRevision=result.revision}}
export function bindSharedUi({bindRoomGeometry,render,toast:notify,setMode,setPanel,setPlacement,openMap,openShape,openRelation,openGroup,openRoutine,openMonthly,newRoutine,newMonthly}){
 const toast=value=>notify(value==='character-slot-required'?residentText('남은 캐릭터 슬롯이 없어요.','No character slots available.','空きキャラクタースロットがありません。'):value==='resident-limit'?residentText('이 그룹의 캐릭터 정원에 도달했어요.','This group’s character limit has been reached.','このグループのキャラクター上限に達しました。'):tr(value));
 const s=activeShared();if(!s)return;const root=document.querySelector('.relationship-page,.mobile-town-shell,.home-page,.routine-shell');if(!root)return;
 if(root.matches('.home-page'))bindSharedHome(root,s,render,toast,bindRoomGeometry);
 if(root.matches('.mobile-town-shell')&&townEditDraft(s)){const cancel=document.createElement('button');cancel.type='button';cancel.disabled=!!townEditDraft(s).saving;cancel.className='home-native-pill';cancel.innerHTML='<span>'+residentText('편집 취소','Cancel edits','編集を取り消す')+'</span>';cancel.onclick=()=>{if(!discardTownEdit(s))return;setMode('');setPlacement();render()};root.querySelector('[data-mobile-town-decoration-mode]')?.parentElement.append(cancel)}
 const select=sharedSelection(s),owned=id=>canEditShared(s)||s.residents?.find(r=>r.id===id)?.ownerUid===uid();
 const stop=e=>{e.preventDefault();e.stopImmediatePropagation()};
 const stage=(action,input)=>{if(townEditDraft(s)?.saving)return Promise.resolve(false);if(!canEditShared(s)){toast('건물 편집 권한이 필요해요');return Promise.resolve(false)}stageTownEdit(snapshot(),action,input);render();return Promise.resolve(true)};
 const saveBuilding=(id,patch={},extra={})=>stage('saveBuilding',{id,patch,...extra});
 const saveView=(sourceId,targetId,field,value,reset=false)=>enqueue(async()=>{if(!owned(sourceId))throw Error('내 캐릭터의 시선만 설정할 수 있어요');await api().saveView({sourceId,targetId,field,value,reset});const current=activeShared();if(current?.activeGroupId!==s.activeGroupId)return;current.perceptions??=[];let p=current.perceptions.find(p=>p.sourceId===sourceId&&p.targetId===targetId);if(!p){p={sourceId,targetId};current.perceptions.push(p)}p.viewJson=JSON.stringify(reset?{}:{...decodeShared(p.viewJson),[field]:value});},toast);

 const saveItem=(kind,id,patch={},extra={})=>kind==='place'?saveBuilding(id,Object.fromEntries(Object.entries(patch).filter(([k])=>!['x','y'].includes(k))),{...('x' in patch?{x:patch.x}:{}),...('y' in patch?{y:patch.y}:{}),...extra}):stage(kind==='home'?'saveHomePlacement':'saveDecoration',{id,patch,...extra});
 const saveTown=patch=>stage('saveTown',{patch});
 const finish=()=>enqueue(async()=>{root.querySelectorAll('input,select,textarea,button').forEach(el=>el.disabled=true);const result=await commitTownEdit(snapshot(),api());if(result){applyTown(s,result);const current=api().getSnapshot();for(const home of result.homes||[]){const old=current.homes.find(h=>h.id===home.id);if(old)Object.assign(old,home);else current.homes.push(home)}}history.undo=[];history.redo=[];setPlacement();setMode('');toast('저장했어요');render()},toast).then(result=>{if(result===false)render();return result});
 const itemFor=el=>el?.dataset.place?['place',town(snapshot()).places.find(p=>p.id===el.dataset.place)]:el?.dataset.homeMap?['home',snapshot().homes.find(h=>h.id===el.dataset.homeMap)]:['decoration',town(snapshot()).decorations?.find(d=>d.id===el?.dataset.townDecoration)];
 const history=select.history??={undo:[],redo:[]};
 root.querySelectorAll('[data-town-placement-command=undo],[data-town-placement-command=redo]').forEach(el=>el.disabled=!canEditShared(s)||!history[el.dataset.townPlacementCommand].length);
 function moveItem(kind,item,patch){const before=Object.fromEntries(Object.keys(patch).map(k=>[k,item[k]??(['mapX','mapY','x','y'].includes(k)?50:['scale','mapScale','imageScale'].includes(k)?1:['flipX','mapFlipX'].includes(k)?false:0)]));saveItem(kind,item.id,patch).then(ok=>{if(ok!==false){history.undo.push({kind,id:item.id,before,after:patch});history.redo=[];render()}})}
 function official(){const dialog=document.createElement('dialog');dialog.className='directory-create-dialog shared-official-dialog';dialog.innerHTML=renderGroupRelations(snapshot());document.body.append(dialog);dialog.querySelector('[data-shared-dialog-close]').onclick=()=>dialog.close();dialog.onclose=()=>{dialog.remove();render()};dialog.querySelector('[data-group-proposal]')?.addEventListener('submit',e=>{e.preventDefault();const input=Object.fromEntries(new FormData(e.currentTarget));enqueue(async()=>{await api().propose(input);dialog.close();toast('관계 제안을 보냈어요')},toast)});dialog.querySelectorAll('[data-group-response]').forEach(form=>form.onsubmit=e=>{e.preventDefault();enqueue(async()=>{await api().respond({proposalId:form.dataset.groupResponse,accept:e.submitter?.name==='accept',reason:form.elements.reason.value});dialog.close()},toast)});dialog.showModal()}
 root.querySelectorAll('[data-character-view]').forEach(el=>el.disabled=!owned(el.dataset.source));
 if(root.matches('.routine-shell')&&!owned(buildSharedWorld(s,state.uiLanguage).activeId))root.querySelectorAll('[data-add-routine],[data-add-routine-day],[data-add-monthly-routine],[data-edit-routine],[data-edit-monthly-routine],[data-delete-routine],[data-delete-monthly-routine],[data-add-anniversary],[data-edit-anniversary]').forEach(b=>b.disabled=true);
 root.querySelectorAll('[data-edit-rel],[data-edit-character-group]').forEach(b=>{const item=b.dataset.editRel?s.relationships?.find(x=>x.id===b.dataset.editRel):s.characterGroups?.find(x=>x.id===b.dataset.editCharacterGroup);if(item)b.disabled=![item.a,item.b,...(item.memberIds||[]),...(item.groupMembers||[])].some(owned)});
 root.addEventListener('click',e=>{
  const el=e.target.closest('button,[data-building-detail-open]');if(!el)return;
  if(el.matches('[data-routine-character]')){stop(e);select.routineCharacter=el.dataset.routineCharacter;render();return}
  if(el.matches('[data-add-routine],[data-add-routine-day],[data-add-monthly-routine],[data-edit-routine],[data-edit-monthly-routine]')){stop(e);withSharedWorld(snapshot(),()=>{const c=state.characters[state.activeId];if(!owned(c.id)){toast(residentText('내 캐릭터를 선택해서 제안해 주세요.','Select your own character to propose a schedule.','自分のキャラクターを選んで提案してください。'));return}const monthly=el.matches('[data-add-monthly-routine],[data-edit-monthly-routine]'),id=el.dataset.editRoutine||el.dataset.editMonthlyRoutine||'',draft=id?null:(monthly?newMonthly():newRoutine());if(draft&&el.dataset.addRoutineDay!==undefined)draft.day=Number(el.dataset.addRoutineDay);(monthly?openMonthly:openRoutine)(id,draft,(patch,targetId,close)=>enqueue(async()=>{const result=await api().propose({kind:'schedule',patch,targetId});close();toast(result.status==='accepted'?residentText('일정을 설정했어요.','Schedule saved.','予定を設定しました。'):residentText('일정 제안을 보냈어요. 우편함에서 답변을 확인해 주세요.','Schedule proposed. Check your mailbox for responses.','予定を提案しました。返答は郵便箱で確認できます。'));render()},toast));const dialog=document.querySelector('.routine-sheet-backdrop');const label=()=>{const others=[...dialog.querySelectorAll('[name=withId]:checked')].some(x=>!owned(x.value));dialog.querySelector('[data-routine-save]').textContent=others?residentText(id?'수정 제안하기':'일정 제안하기',id?'Propose changes':'Propose schedule',id?'変更を提案':'予定を提案'):residentText('설정하기','Save schedule','予定を設定')};dialog.addEventListener('change',label);label()});return}
  if(el.matches('[data-delete-routine],[data-delete-monthly-routine]')){stop(e);const key=(el.dataset.deleteRoutine||el.dataset.deleteMonthlyRoutine).split(':')[0],schedule=s.schedules?.find(x=>x.id===key);if(!schedule){toast(residentText('원본 일정은 내 마을에서 수정해 주세요.','Edit original schedules in your personal town.','元の予定は自分の村で編集してください。'));return}enqueue(async()=>{await api().propose({kind:'schedule',targetId:key,patch:{...schedule,cancelled:true}});toast(residentText('일정 취소를 제안했어요.','Schedule cancellation proposed.','予定の取り消しを提案しました。'))},toast);return}
  if(el.matches('[data-add-anniversary],[data-edit-anniversary]')){stop(e);withSharedWorld(snapshot(),()=>{const draft=newMonthly();draft.type='가족 일정';openMonthly('',draft,(patch,targetId,close)=>enqueue(async()=>{await api().propose({kind:'schedule',patch,targetId});close();render()},toast))});return}
  if(el.matches('[data-relationship-character]')){stop(e);select[el.dataset.relationshipCharacter]=el.dataset.characterId;render();return}
  if(el.matches('[data-open-official-relations]')){stop(e);root.querySelector('[data-official-relation-dialog]')?.showModal();return}
  if(el.matches('[data-open-character-groups]')){stop(e);root.querySelector('[data-character-group-list-dialog]')?.showModal();return}
  if(el.matches('[data-add-rel],[data-edit-rel],[data-add-character-group],[data-edit-character-group]')){stop(e);root.querySelectorAll('dialog[open]').forEach(d=>d.close());const isGroup=el.matches('[data-add-character-group],[data-edit-character-group]'),id=el.dataset.editRel||el.dataset.editCharacterGroup||'';withSharedWorld(snapshot(),()=>(isGroup?openGroup:openRelation)(id,(patch,targetId)=>enqueue(async()=>{if(activeShared()?.activeGroupId!==s.activeGroupId)throw Error('Group changed');const result=await api().propose({kind:isGroup?'characterGroup':'relationship',patch,targetId});toast(result.status==='accepted'?'저장했어요':'관계 제안을 보냈어요');render();return true},toast)));return}
  if(el.matches('[data-delete-rel],[data-delete-character-group],[data-delete-group]')){stop(e);return}
  if(el.matches('[data-open-relationship-map]')){stop(e);withSharedWorld(s,openMap);return}
  if(el.matches('[data-open-view-dialog]')){stop(e);const dialog=root.querySelector(`[data-view-dialog="${CSS.escape(el.dataset.openViewDialog)}"]`);if(dialog){dialog.onclose=()=>serial.then(render);dialog.showModal()}return}
  if(el.matches('[data-reset-character-view]')){stop(e);const [a,b]=el.dataset.resetCharacterView.split(':');if(owned(a)&&confirm(tr('이 시선 설정을 초기화할까요?')))saveView(a,b,'overall','',true).then(render);return}
  if(el.matches('[data-add-town-home],[data-add-home]')){stop(e);const id='home-'+crypto.randomUUID();saveItem('home',id,{}, {create:true}).then(ok=>{if(ok===false)return;if(root.matches('.home-page'))api().visitHome(id);else{setMode('buildings');setPanel('home:'+id);render()}});return}
  if(el.matches('[data-home-select]')){stop(e);api().visitHome(el.dataset.homeSelect);return}
  if(el.matches('[data-home-floor],[data-home-floor-step]')){stop(e);const id=el.dataset.homeId||s.visitingHomeId||s.homes[0]?.id,h=s.homes.find(h=>h.id===id),layout=decodeShared(h?.layoutJson);select.floors??={};select.floors[id]=Math.max(1,Math.min(Math.max(Number(layout.floorCount)||1,...Object.values(layout.rooms||{}).map(r=>Number(r.floor)||1)),el.dataset.homeFloor?Number(el.dataset.homeFloor):(select.floors[id]||1)+Number(el.dataset.homeFloorStep)));render();return}
  if(el.matches('[data-home-edit]')){stop(e);return}
  if(el.matches('[data-shared-residents]')){stop(e);select.residentDetail='';select.residentForm='';setMode('residents');setPanel('residents');render();return}
  if(el.matches('[data-shared-resident-detail]')){stop(e);select.residentDetail=el.dataset.sharedResidentDetail;select.residentForm='';render();return}
  if(el.matches('[data-resident-apply]')){stop(e);select.residentForm='admission';render();return}
  if(el.matches('[data-resident-cohabit]')){stop(e);select.residentForm='cohabitation';render();return}
  if(el.matches('[data-resident-visit]')){stop(e);api().visitHome(el.dataset.residentVisit);location.hash='tab=home';return}
  if(el.matches('[data-resident-refresh]')){stop(e);enqueue(()=>api().refreshResidents(),toast);return}
  if(el.matches('[data-resident-remove]')){stop(e);if(confirm(residentText('이 캐릭터를 그룹에서 퇴거시킬까요?','Move this character out of the group?','このキャラクターをグループから退去させますか？')))enqueue(async()=>{await api().removeResident(el.dataset.residentRemove);select.residentDetail='';render()},toast);return}
  if(el.matches('[data-shared-proposals]')){stop(e);location.hash='tab=mailbox';return}
  if(el.matches('[data-editor-save],[data-town-save]')||el.matches('[data-mobile-town-decoration-mode]')&&root.dataset.townMode==='decorations'){stop(e);el.disabled=true;finish().finally(()=>el.disabled=false);return}
  if(el.matches('[data-world-transport]')){stop(e);const mode=el.dataset.worldTransport,modes=town(snapshot()).transportModes||[];saveTown({transportModes:modes.includes(mode)?modes.filter(m=>m!==mode):[...modes,mode]});return}
  if(el.matches('[data-place-stock],[data-place-audience]')){stop(e);const field=el.hasAttribute('data-place-stock')?'stock':'audiences',id=el.dataset.placeStock||el.dataset.placeAudience,p=town(snapshot()).places.find(p=>p.id===id),value=el.dataset.itemId||el.dataset.value,list=p[field]||[];saveBuilding(id,{[field]:list.includes(value)?list.filter(v=>v!==value):[...list,value]});return}
  if(el.matches('[data-building-shape-open],[data-home-building-shape]')){stop(e);const kind=el.hasAttribute('data-home-building-shape')?'home':'place',id=el.dataset.homeBuildingShape||el.dataset.buildingShapeOpen;withSharedWorld(snapshot(),()=>openShape(id,kind,patch=>saveItem(kind,id,patch)));return}
  if(el.matches('[data-add-town-decoration]')){stop(e);const id='decoration-'+crypto.randomUUID();saveItem('decoration',id,{kind:el.dataset.addTownDecoration,name:el.dataset.decorationLabel,emoji:el.querySelector('span')?.textContent||'✨',x:50,y:50}).then(()=>{setPlacement('decoration',id);render()});return}
  if(el.matches('[data-delete-home],[data-building-recovery],[data-place-interior-image],[data-clear-place-interior-image],[data-image-url],[data-add-town],[data-delete-town],[data-world-image],[data-world-bg-upload]')){stop(e);toast('이 항목의 공유 편집 연결은 준비 중이에요');return}
  if(el.matches('[data-building-browser-open],[data-building-detail-open]')){stop(e);if(root.dataset.townMode==='decorations'){const [kind,item]=itemFor(el);if(item){setPlacement(kind,item.id);render()}return}const id=el.dataset.buildingBrowserOpen||el.dataset.buildingDetailOpen;setMode('buildings');setPanel(id);setPlacement();render();return}
  if(el.matches('[data-add-place]')){stop(e);const id='building-'+crypto.randomUUID();saveBuilding(id,{}, {name:'새 건물',type:'상점',x:50,y:50}).then(()=>{setMode('buildings');setPanel(id);render()});return}
  if(el.matches('[data-delete-place]')){stop(e);if(confirm(tr('이 건물을 삭제할까요?')))saveBuilding(el.dataset.deletePlace,{}, {remove:true});return}
  if(el.matches('[data-town-placement-command]')){stop(e);const command=el.dataset.townPlacementCommand;
   if(command==='done'){setPlacement();render();return}
   if(command==='undo'||command==='redo'){const from=history[command],entry=from.at(-1);if(entry)saveItem(entry.kind,entry.id,command==='undo'?entry.before:entry.after).then(ok=>{if(ok!==false){from.pop();history[command==='undo'?'redo':'undo'].push(entry);render()}});return}
   const [kind,item]=itemFor(root.querySelector('.placement-selected'));if(!item)return;
   if(command==='delete'){if(kind!=='home'&&confirm(tr('삭제할까요?')))saveItem(kind,item.id,{}, {remove:true});return}
   const scale=kind==='home'?'mapScale':kind==='place'?'imageScale':'scale',flip=kind==='home'?'mapFlipX':'flipX';
   const patch=command==='smaller'||command==='larger'?{[scale]:Math.max(.1,Math.min(4,(item[scale]||1)+(command==='larger'?.1:-.1)))}:command==='flip'?{[flip]:!item[flip]}:command==='front'||command==='back'?{mapZ:Math.max(-100,Math.min(1000,(item.mapZ||10)+(command==='front'?1:-1)))}:null;
   if(patch)moveItem(kind,item,patch);return
  }
 },true);
  root.querySelector('[data-resident-search]')?.addEventListener('input',e=>root.querySelectorAll('[data-resident-name]').forEach(card=>card.hidden=!card.dataset.residentName.includes(e.target.value.toLocaleLowerCase())));
 root.querySelector('[data-create-shared-resident]')?.addEventListener('submit',e=>{stop(e);const form=e.currentTarget;if(form.dataset.pending)return;form.dataset.pending='1';const data=Object.fromEntries(new FormData(form)),id=crypto.randomUUID(),groupId=s.activeGroupId,townId=town(s).id,account=uid();form.querySelector('button[type=submit]').disabled=true;select.residentForm='';render();void runBackgroundAction('create-resident:'+id,async()=>{
  if(uid()!==account)throw Error('Account changed');const world=emptyWorld(),seed=runIsolatedWorld(world,()=>{const id=createCharacter(5);return {profile:structuredClone(state.characters[id]),home:structuredClone(state.homes[id])}});
  if(data.code.trim()){const result=await api().readCharacterCode(data.code);Object.assign(seed.profile,result.character);delete seed.profile.days}
  if(data.name.trim())seed.profile.name=data.name.trim();if(!data.code.trim()){seed.profile.job=data.job||'무직';seed.profile.ageGroup=data.ageGroup}
  for(const [field,key] of [['icon','iconFile'],['photo','photoFile']]){const file=data[key];if(file?.size)seed.profile[field]=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)})}
  const result=await api().createResident({id,groupId,townId,...seed});if(activeShared()?.activeGroupId===groupId){select.residentDetail=result.id;render()}
 })});
 root.querySelector('[data-residence-request]')?.addEventListener('submit',e=>{stop(e);const form=e.currentTarget,input=Object.fromEntries(new FormData(form));enqueue(async()=>{const result=await(form.dataset.residenceRequest==='admission'?api().requestAdmission(input.characterId):api().requestCohabitation(input));select.residentForm='';select.residentDetail='';toast(residentText(result.status==='accepted'?'적용했어요':'제안을 보냈어요',result.status==='accepted'?'Applied':'Proposal sent',result.status==='accepted'?'反映しました':'提案を送りました'));render()},toast)});
 root.addEventListener('change',e=>{
  const el=e.target;
  if(el.matches('[data-view-source],[data-view-target]')){stop(e);select[el.hasAttribute('data-view-source')?'source':'target']=el.value;render();return}
  if(el.matches('[data-character-view]')){stop(e);saveView(el.dataset.source,el.dataset.target,el.dataset.viewField,el.value);return}
  if(el.matches('[data-place-field]')){stop(e);const field=el.dataset.placeField;saveBuilding(el.dataset.placeId,field==='type'?{}:{[field]:['spicy','sweet'].includes(field)||el.type==='number'||el.type==='range'?Number(el.value):el.value},field==='type'?{type:el.value}:{});return}
  if(el.matches('[data-home-field],[data-home-name]')){stop(e);const field=el.dataset.homeField||'name';if(field==='townId')return;saveItem('home',el.dataset.homeId,{[field]:el.type==='range'?Number(el.value):el.value});return}
  const attr=[...el.attributes].find(a=>a.name.startsWith('data-world-'));if(attr){stop(e);const key=attr.name.slice(11).replace(/-([a-z])/g,(_,c)=>c.toUpperCase());saveTown({[key]:el.type==='checkbox'?el.checked:el.value})}
 },true);
 root.addEventListener('input',e=>{if(e.target.matches('[data-place-field],[data-home-field],[data-home-name],[data-world-name],[data-world-description]'))e.stopImmediatePropagation()},true);
 root.addEventListener('pointerdown',e=>{if(e.target.matches('[data-place-field]'))e.stopImmediatePropagation()},true);
 if(root.matches('.mobile-town-shell')){
  if(!canEditShared(s)){root.querySelectorAll('[data-place-field],[data-home-field],[data-home-name],[data-world-name],[data-world-description],[data-add-place],[data-delete-place],[data-mobile-town-decoration-mode]').forEach(el=>el.disabled=true);root.querySelectorAll('input,select,textarea,[data-world-transport]').forEach(el=>{if([...el.attributes].some(a=>/^data-(world-|home-|place-)/.test(a.name)))el.disabled=true})}
  root.querySelectorAll('[data-home-field="townId"],[data-place-field="townId"],[data-add-town],[data-delete-town]').forEach(el=>el.disabled=true);
  root.querySelectorAll('.town-edit .place').forEach(el=>{el.onpointerdown=null;if(!canEditShared(s)||!['buildings','decorations'].includes(root.dataset.townMode))return;
   el.onpointerdown=e=>{if(e.button!==0||townEditDraft(s)?.saving)return;e.preventDefault();e.stopPropagation();const [kind,item]=itemFor(el);if(!item)return;
    const xKey=kind==='home'?'mapX':'x',yKey=kind==='home'?'mapY':'y',rect=el.parentElement.getBoundingClientRect(),start={x:e.clientX,y:e.clientY};let x=item[xKey]??50,y=item[yKey]??50,moved=false;el.setPointerCapture(e.pointerId);
    el.onpointermove=move=>{const dx=move.clientX-start.x,dy=move.clientY-start.y;if(Math.abs(dx)+Math.abs(dy)<5&&!moved)return;moved=true;x=Math.max(5,Math.min(95,(item[xKey]??50)+dx/rect.width*100));y=Math.max(5,Math.min(95,(item[yKey]??50)+dy/rect.height*100));x=Math.max(6,Math.min(94,Math.round(x/2)*2));y=Math.max(7,Math.min(94.5,Math.round(y/3.5)*3.5));el.style.left=x+'%';el.style.top=y+'%'};
    el.onpointerup=()=>{el.onpointermove=null;el.onpointerup=null;setPlacement(kind,item.id);if(moved){el.addEventListener('click',stop,{once:true,capture:true});moveItem(kind,item,{[xKey]:x,[yKey]:y})}else render()};
    el.onpointercancel=()=>{el.onpointermove=null;el.onpointerup=null;render()};
   }
  });
 }
 if(root.matches('.mobile-town-shell')&&townEditDraft(s)?.saving)root.querySelectorAll('input,select,textarea,button').forEach(el=>el.disabled=true);
}
