// Approved public display data only. No account or payment data.
export const SUPPORTER_CREDITS={
  "version": 1,
  "updatedAt": "2026-09-14",
  "entries": [
    {
      "id": "3d01fed2-c35c-497d-a8a8-52fcd10fe844",
      "name": "제논",
      "visibility": "named",
      "color": "#594b3f",
      "color2": "#594b3f",
      "font": "default",
      "effect": "plain",
      "background": "none",
      "animate": false,
      "size": 18.12,
      "weight": 1,
      "seconds": 5
    },
    {
      "id": "274d61b2-7da1-4aea-a50a-7561e783c885",
      "name": "Q",
      "visibility": "named",
      "color": "#594b3f",
      "color2": "#594b3f",
      "font": "default",
      "effect": "plain",
      "background": "none",
      "animate": false,
      "size": 18.12,
      "weight": 1,
      "seconds": 5
    },
    {
      "id": "ca7d67bb-9d23-4c9a-b9af-ed76e963cedf",
      "name": "모리모",
      "visibility": "named",
      "color": "#594b3f",
      "color2": "#594b3f",
      "font": "default",
      "effect": "plain",
      "background": "none",
      "animate": false,
      "size": 18.12,
      "weight": 1,
      "seconds": 5
    },
    {
      "id": "48418b1d-b2fc-4d16-8b3d-de20d254bb6f",
      "name": "주검",
      "visibility": "named",
      "color": "#594b3f",
      "color2": "#594b3f",
      "font": "default",
      "effect": "plain",
      "background": "none",
      "animate": false,
      "size": 18.36,
      "weight": 1,
      "seconds": 5
    },
    {
      "id": "b521d412-1201-40b6-ba0c-5c987fdeac33",
      "name": "스토",
      "visibility": "named",
      "color": "#594b3f",
      "color2": "#594b3f",
      "font": "default",
      "effect": "plain",
      "background": "none",
      "animate": false,
      "size": 18.24,
      "weight": 1,
      "seconds": 5
    },
    {
      "id": "b54bec03-a3d7-46f6-80d2-66c99c1987d3",
      "name": "신부(not bride)",
      "visibility": "named",
      "color": "#594b3f",
      "color2": "#594b3f",
      "font": "default",
      "effect": "plain",
      "background": "none",
      "animate": false,
      "size": 18.12,
      "weight": 1,
      "seconds": 5
    },
    {
      "id": "6b8cedf8-18cf-4ef9-b954-a4ef1dabd35c",
      "name": "고스트다이브",
      "visibility": "named",
      "color": "#594b3f",
      "color2": "#594b3f",
      "font": "default",
      "effect": "plain",
      "background": "none",
      "animate": false,
      "size": 18.12,
      "weight": 1,
      "seconds": 5
    }
  ]
};
