const texts={ko:{title:'신고·계정 차단',report:'신고하기',block:'계정 차단',unblock:'차단 해제',manage:'차단한 계정 관리',close:'닫기',cancel:'취소',reason:'신고 사유',details:'추가 설명 (선택)',sent:'신고가 접수됐어요. 제작자가 확인합니다.',blocked:'계정을 차단했어요.',error:'처리하지 못했어요. 다시 시도해 주세요.',empty:'차단한 계정이 없어요.',confirm:'이 계정의 모든 캐릭터와 우편을 숨기고, 서로 우편·제안·직접 상호작용을 할 수 없게 합니다. 다른 멀티 그룹에서도 적용됩니다.',reasons:['괴롭힘·불쾌한 행동','부적절한 성적 콘텐츠','폭력적인 콘텐츠','혐오·차별','스팸·사기','기타'],loading:'불러오는 중…',reporting:'신고를 보내는 중…'},en:{title:'Report or block account',report:'Report',block:'Block account',unblock:'Unblock',manage:'Blocked accounts',close:'Close',cancel:'Cancel',reason:'Reason',details:'Details (optional)',sent:'Report received. The creator will review it.',blocked:'Account blocked.',error:'Could not complete this. Please retry.',empty:'No blocked accounts.',confirm:'Hide this account’s characters and mail, and prevent mail, proposals and directed interactions in both directions across all multiplayer groups.',reasons:['Harassment','Sexual content','Violence','Hate or discrimination','Spam or fraud','Other'],loading:'Loading…',reporting:'Sending report…'},ja:{title:'通報・アカウントブロック',report:'通報する',block:'アカウントをブロック',unblock:'ブロック解除',manage:'ブロックしたアカウント',close:'閉じる',cancel:'キャンセル',reason:'通報理由',details:'説明（任意）',sent:'通報を受け付けました。制作者が確認します。',blocked:'アカウントをブロックしました。',error:'処理できませんでした。再試行してください。',empty:'ブロックしたアカウントはありません。',confirm:'このアカウントの全キャラクターと手紙を非表示にし、互いの手紙・提案・直接の交流を制限します。ほかのマルチグループにも適用されます。',reasons:['嫌がらせ','不適切な性的内容','暴力','差別・ヘイト','スパム・詐欺','その他'],loading:'読み込み中…',reporting:'通報を送信中…'}};
const copy=()=>texts[document.documentElement.lang]||texts.ko;
let owner='',blocked=[],loaded=false,pending=null;const hidden=new Set();
const uid=()=>window.ParallelCityAuth?.getInfo?.()?.user?.uid||'';
const el=(tag,text,parent)=>{const node=document.createElement(tag);if(text)node.textContent=text;parent?.append(node);return node};
function dialog(title){const d=el('dialog',null,document.body);d.className='user-safety-dialog';const h=el('header',null,d);el('h2',title,h);const close=el('button','×',h);close.type='button';close.setAttribute('aria-label',copy().close);close.onclick=()=>d.close();d.addEventListener('close',()=>d.remove(),{once:true});d.showModal();return d}
function refresh(){window.dispatchEvent(new Event('drawer-village-groups'))}
async function load(force=false){const current=uid();if(current!==owner){owner=current;blocked=[];hidden.clear();loaded=false;pending=null}if(!current)return;if(pending)return pending;if(loaded&&!force)return;pending=window.DrawerVillageGroups.readSafety().then(data=>{if(uid()===current){blocked=data.blocked||[];loaded=true;refresh()}}).finally(()=>{pending=null});return pending}
let filterKeys=[],filtered=null;
function filterSnapshot(s){if(uid()!==owner||!blocked.length&&!hidden.size)return s;const keys=[owner,blocked,hidden.size,s.activeGroupId,s.members,s.residents,s.incomingMail,s.incomingProposals,s.outgoingProposals,s.homes];if(filtered&&keys.every((x,i)=>x===filterKeys[i]))return {...s,...filtered};filterKeys=keys;const ids=new Set(blocked.map(x=>x.uid));const visible=x=>!ids.has(x.uid||x.ownerUid||x.senderUid)&&!hidden.has((x.groupId||s.activeGroupId)+':'+x.id);filtered={members:s.members?.filter(visible),residents:s.residents?.filter(visible),incomingMail:s.incomingMail?.filter(visible),incomingProposals:s.incomingProposals?.filter(x=>visible(x)&&!ids.has(x.recipientUid)),outgoingProposals:s.outgoingProposals?.filter(x=>!ids.has(x.recipientUid)),homes:s.homes?.map(x=>ids.has(x.ownerUid)?{...x,image:'',exteriorImage:'',name:'',layoutJson:'{}'}:x)};return {...s,...filtered}}
async function openAction(input){const c=copy(),d=dialog(c.title),scope=uid();el('p',c.confirm,d);const status=el('p','',d);status.setAttribute('role','status');const block=el('button',c.block,d),report=el('button',c.report,d);const run=async(button,fn)=>{button.disabled=true;try{if(scope!==uid())throw Error();await fn()}catch{status.textContent=c.error}finally{button.disabled=false}};
block.onclick=()=>run(block,async()=>{const data=await window.DrawerVillageGroups.setUserBlock({...input,block:true});if(scope!==uid())return;blocked=data.blocked||[];owner=scope;loaded=true;d.close();document.querySelectorAll('dialog.mail-letter').forEach(x=>x.close());refresh()});
report.onclick=()=>{report.hidden=true;const form=el('form',null,d),label=el('label',c.reason,form),select=el('select',null,label);select.required=true;el('option','—',select).value='';['harassment','sexual','violence','hate','spam','other'].forEach((key,i)=>el('option',c.reasons[i],select).value=key);const details=el('textarea',null,el('label',c.details,form));details.maxLength=500;details.rows=4;const send=el('button',c.report,form);send.type='submit';const requestId=crypto.randomUUID();form.onsubmit=e=>{e.preventDefault();run(send,async()=>{status.textContent=c.reporting;await window.DrawerVillageGroups.reportContent({...input,reason:select.value,details:details.value,requestId});if(scope!==uid())return;form.remove();hidden.add(input.groupId+':'+input.targetId);status.textContent=c.sent;document.querySelectorAll('dialog.mail-letter').forEach(x=>x.close());refresh()})}};
}
async function manage(){const c=copy(),d=dialog(c.manage),scope=uid(),body=el('div',c.loading,d);const draw=()=>{body.replaceChildren();if(!blocked.length)el('p',c.empty,body);for(const item of blocked){const row=el('div',null,body);row.className='safety-block-row';el('span',item.name||item.uid.slice(0,8),row);const b=el('button',c.unblock,row);b.onclick=async()=>{b.disabled=true;try{const data=await window.DrawerVillageGroups.setUserBlock({block:false,targetUid:item.uid});if(scope!==uid())return;blocked=data.blocked||[];draw();refresh()}catch{b.disabled=false;el('p',c.error,body)}}}};try{await load(true);if(scope===uid())draw()}catch{body.textContent=c.error}}
export function installUserSafety(){window.DrawerVillageSafety={filterSnapshot,load};document.addEventListener('click',event=>{const b=event.target.closest('[data-user-safety],[data-safety-manage]');if(!b)return;event.preventDefault();if(b.hasAttribute('data-safety-manage'))void manage();else void openAction({kind:b.dataset.safetyKind||'member',targetId:b.dataset.userSafety,groupId:b.dataset.safetyGroup||window.DrawerVillageGroups?.getSnapshot?.()?.activeGroupId})});window.addEventListener('drawer-village-auth-busy',()=>{if(window.DrawerVillageGroups)void load().catch(()=>{})});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&window.DrawerVillageGroups)void load(true).catch(()=>{})});}
