const assert=require('node:assert/strict');
const {createDiscoveryAccess}=require('../functions/discovery-access');
function mockDB(){let rows=new Map(),queue=Promise.resolve();const snap=(r,data)=>({id:r.id,ref:r,exists:data!==undefined,data:()=>structuredClone(data)});const ref=path=>({path,id:path.split('/').at(-1),collection:name=>ref(path+'/'+name),doc:name=>ref(path+'/'+name),get:async()=>snap(ref(path),rows.get(path)),where:(key,op,value)=>query(path,[[key,op,value]]),limit:n=>query(path,[],n)});const query=(path,conditions=[],limit=1000)=>({where:(...c)=>query(path,[...conditions,c],limit),limit:n=>query(path,conditions,n),get:async()=>{const docs=[...rows].filter(([p,v])=>p.startsWith(path+'/')&&p.split('/').length===path.split('/').length+1&&conditions.every(([k,op,w])=>op==='=='?v[k]===w:false)).slice(0,limit).map(([p,v])=>snap(ref(p),v));return {docs,size:docs.length,empty:!docs.length}}});return {collection:ref,put:(p,v)=>rows.set(p,structuredClone(v)),get:p=>rows.get(p),runTransaction:fn=>{const job=queue.then(async()=>{const pending=new Map(rows);let writing=false;const tx={get:async r=>{assert.equal(writing,false,'all reads before writes');return snap(r,pending.get(r.path))},set:(r,v,o)=>{writing=true;pending.set(r.path,o?.merge?{...pending.get(r.path),...structuredClone(v)}:structuredClone(v))},create:(r,v)=>{assert(!pending.has(r.path));tx.set(r,v)},update:(r,v)=>{assert(pending.has(r.path));tx.set(r,v,{merge:true})}};const result=await fn(tx);rows=pending;return result});queue=job.catch(()=>{});return job}}}
(async()=>{const db=mockDB();let now=100000000;const service=createDiscoveryAccess({db,clock:()=>now});
const uses=await Promise.all(['character-a','character-b','multiplayer-c'].map(requestId=>service.use('u',{requestId})));
assert.equal(uses.filter(r=>r.granted).length,1);assert((await service.use('u',{requestId:'character-a'})).granted);
assert((await service.use('other',{requestId:'a'})).granted);now+=599999;assert(!(await service.use('u',{requestId:'new'})).granted);now++;assert((await service.use('u',{requestId:'new'})).granted);
db.put('users/premium',{entitlements:{adFree:true}});await service.use('premium',{requestId:'first'});now+=59999;assert(!(await service.use('premium',{requestId:'second'})).granted);now++;assert((await service.use('premium',{requestId:'second'})).granted);assert.equal((await service.read('premium')).interval,60000);
const rewards=require('../functions/discovery-rewards').createDiscoveryRewards({db,clock:()=>now,random:()=> 'ticket-a'});const ticket=await rewards.prepareAd('u',{platform:'android'});const callback={user_id:'u',custom_data:ticket.ticketId,transaction_id:'tx-a',timestamp:String(now),ad_unit:ticket.adUnit,reward_amount:'1'};
await assert.rejects(()=>rewards.rewardAd({...callback,user_id:'other'}));assert.equal((await service.read('u')).rewardCredits,0);await rewards.rewardAd(callback);await rewards.rewardAd(callback);assert.equal((await service.read('u')).rewardCredits,1);assert((await service.use('u',{requestId:'reward-question'})).granted);assert.equal((await service.read('u')).rewardCredits,0);assert(!(await service.use('u',{requestId:'no-extra'})).granted);
const refund=require('../functions/diamond-refunds').playRefund;db.put('playPurchases/adfree',{uid:'premium',productId:'ad_free',quantity:1,orderId:'qa-order'});await refund(db,{orderId:'qa-order',voidedTimeMillis:String(now)});await refund(db,{orderId:'qa-order',voidedTimeMillis:String(now)});assert.equal((await service.read('premium')).interval,600000);assert.equal(db.get('playPurchases/adfree').revoked,true);
console.log('PASS440 signed-callback service: wrong account rejected, one credit, duplicate callback idempotent, atomic consumption, premium 60-second cooldown');
const {storyQuestions}=await import('../story-events.js');const {variedDiscoveryPool}=await import('../discovery-question-pool.js');const d=new Date(),day=n=>new Date(d.getFullYear(),d.getMonth(),d.getDate()-n).toLocaleDateString('en-CA');
const c={storyDays:Object.fromEntries([0,1,2].map(n=>[day(n),{home:true,outside:false}])),discovery:{recent:['story:home:'+day(0)],answered:[]},storyResponses:[{id:'story:home:'+day(1),at:Date.now()-86400000}]};assert(!storyQuestions(c).some(q=>q.id.startsWith('story:home:')));
assert.deepEqual(variedDiscoveryPool(c,[{id:'story:home:'+day(0),story:true}],[{id:'ordinary'}]).map(q=>q.id),['ordinary']);
console.log('PASS439 account-wide 10-minute server gate: concurrent characters/devices, retry, account isolation, expiry; repeated home topic suppression and mixed question pool');
})().catch(e=>{console.error(e);process.exitCode=1});
