import assert from 'node:assert/strict';
import {needsAt,advanceNeeds,urgentNeed,relationshipPolicy} from '../life-needs.js';
const now=Date.now(),c={autonomousActivityBlocks:['sleep','eating','toilet'],lifeNeeds:{sleep:4,hunger:3,toilet:2,hygiene:90,social:90,updatedAt:now-3600000}};
assert.deepEqual(Object.values(needsAt(c,now)).slice(0,3),[100,100,100]);advanceNeeds(c,{},now);assert.equal(c.lifeNeeds.toilet,100);assert.equal(urgentNeed(c,now),'');
c.autonomousActivityBlocks=[];c.lifeNeeds={sleep:90,hunger:10,toilet:90,hygiene:90,social:90,updatedAt:now};assert.equal(urgentNeed(c,now),'hunger');advanceNeeds(c,{title:'Eating a meal',needKey:'hunger'},now+1);advanceNeeds(c,{title:'Eating a meal',needKey:'hunger'},now+600001);assert(c.lifeNeeds.hunger>40);assert.equal(urgentNeed(c,now+600001),'hunger');
assert.equal(relationshipPolicy([{relationshipChangeMode:'fixed'}],{relationshipChangeMode:'dynamic'}),'dynamic');
await import('../server-life.mjs');const {state,createCharacter,runIsolatedWorld}=await import('../state.js?v=20260909dev305');const {eventFor}=await import('../simulation.js?v=20260909dev305');
const id=createCharacter(),person=state.characters[id],date=new Date();date.setHours(2,0,0,0);person.wake='07:00';person.sleep='23:00';person.lifeNeeds={sleep:90,hunger:90,toilet:5,hygiene:90,social:90,updatedAt:date.getTime()};const scene=eventFor(person,date);assert.equal(scene.needKey,'toilet',JSON.stringify(scene));assert.equal(scene.room,'bath');assert.equal(scene.lifeTaskId,'toilet');assert(!scene.withId);assert(Object.values(person.days).some(day=>day.entries.some(e=>e.needKey==='toilet')));
console.log('PASS415: banned needs stay 100; urgent needs drive a solo bathroom action and log; recovery continues; global relationship policy overrides legacy per-character settings');
