import assert from 'node:assert/strict';
import {RECIPES} from '../recipes.js';
import {recipeAllowed,cookingProgress,finishCooking,cookingLevel,canStartCooking} from '../cooking.js';
import {placeCookedFood,actOnFood,foodRemaining,foodSpoiled,FOOD_LIFETIME} from '../prepared-food.js';
import {advanceNeeds,needsAt} from '../life-needs.js';
import {mealWindow} from '../automatic-cooking.js';
import {backgroundMusicSource,TOWN_BACKGROUNDS} from '../town-background.js';
const now=Date.now(),normal=RECIPES.find(r=>r.cuisine==='korean'&&r.level===1),fantasy=RECIPES.find(r=>r.cuisine==='fantasy'),medieval=RECIPES.find(r=>r.cuisine==='medieval');
assert(!recipeAllowed({},fantasy));for(const r of RECIPES.filter(r=>r.cuisine!=='fantasy'))assert(recipeAllowed({era:'medieval'},r),'No era-based food restriction: '+r.id);
assert(cookingProgress({recipeVersion:472,recipeId:fantasy.id,startedAt:now,endsAt:now+10000},now));
assert.equal(Object.keys(TOWN_BACKGROUNDS).length,2);assert(backgroundMusicSource({backgroundSetting:'arkenwald'}).includes('arkenwald'));
const c={id:'a',homeId:'h',cooking:{experience:30,active:{id:'dish-one',recipeId:normal.id,recipeVersion:472,startedAt:now-1000,endsAt:now,homeId:'h',room:'kitchen'}}},other={id:'b',homeId:'h'},w={characters:{a:c,b:other},homes:{h:{id:'h',rooms:{kitchen:{type:'kitchen',furniturePlacements:[{id:'table',item:'식탁',x:30,y:50},{id:'fridge',item:'냉장고'}]},living:{type:'living',furniturePlacements:[]}}}}};
assert.equal(canStartCooking(w,c,medieval.id,now),'cooking-dlc');assert(finishCooking(w,c,now));assert.equal(cookingLevel(c),4,'existing level preserved');assert(!finishCooking(w,c,now));assert.equal(c.cooking.dishes.length,1);assert.equal(c.cooking.inventory[normal.id],1);
const dish=c.cooking.dishes[0];assert.equal(dish.furnitureId,'table');assert.equal(foodRemaining(dish,now+3600000),17*3600000);
actOnFood(w,c.id,dish.id,'fridge',{room:'kitchen'},now+3600000);assert.equal(foodRemaining(dish,now+5*3600000),16*3600000);
actOnFood(w,c.id,dish.id,'move',{room:'living'},now+5*3600000);assert.equal(foodRemaining(dish,now+6*3600000),15*3600000);
assert.throws(()=>actOnFood(w,other.id,dish.id,'discard',{},now),/food-owner/);
assert.throws(()=>actOnFood(w,c.id,dish.id,'fridge',{room:'living'},now),/food-fridge/);
assert(foodSpoiled(dish,now+30*3600000));assert.throws(()=>actOnFood(w,c.id,dish.id,'eat',{},now+30*3600000),/food-spoiled/);
actOnFood(w,c.id,dish.id,'discard',{},now+30*3600000);assert.equal(c.cooking.inventory[normal.id],0);
placeCookedFood(w,c,{id:'meal-two',recipeId:normal.id,endsAt:now,homeId:'h',room:'kitchen'});c.cooking.inventory[normal.id]=1;other.lifeNeeds={hunger:5,updatedAt:now};actOnFood(w,other.id,'meal-two','eat',{},now);assert.equal(other.lifeNeeds.hunger,70);assert.equal(c.cooking.dishes.length,0);assert.throws(()=>actOnFood(w,other.id,'meal-two','eat',{},now),/food-missing/);
const person={id:'p',lifeNeeds:{toilet:10,updatedAt:now}};advanceNeeds(person,{needKey:'toilet',recoveryEndsAt:now+10000},now+1);assert(needsAt(person,now+5000).toilet>45);advanceNeeds(person,{kind:'rest'},now+5000);assert(needsAt(person,now+10000).toilet<55,'interruption keeps earned recovery without continued recovery');
const done={id:'q',lifeNeeds:{toilet:10,updatedAt:now}};advanceNeeds(done,{needKey:'toilet',recoveryEndsAt:now+10000},now+1);assert(needsAt(done,now+10000).toilet>89);assert(needsAt(done,now+60000).toilet<91,'no over-credit after action ends');
const slow={id:'p',needSettings:{frequency:{hunger:.25}},lifeNeeds:{hunger:80,updatedAt:now}},fast={...slow,needSettings:{frequency:{hunger:2}}};assert(needsAt(slow,now+3600000).hunger>needsAt(fast,now+3600000).hunger);
assert.notEqual(needsAt({id:'p',lifeNeeds:{hunger:80,updatedAt:now}},now+3600000).hunger,needsAt({id:'q',lifeNeeds:{hunger:80,updatedAt:now}},now+3600000).hunger);
assert.equal(mealWindow(new Date(2026,8,23,3).getTime(),'a'),null);assert.equal(mealWindow(new Date(2026,8,23,13).getTime(),'a').slot,'lunch');
console.log('PASS476: fantasy retained but unavailable, unrestricted food by era, DLC gate, food lifecycle/authorization/idempotency, XP migration, need recovery and pacing, meal windows');
