import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium,webkit}=require('C:/Users/김세은/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=process.cwd(),out=resolve('tmp/qa-bed418');await mkdir(out,{recursive:true});
const server=createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname,file=resolve(root,'.'+(path==='/'?'/index.html':path));if(!file.startsWith(root))throw Error();let body=await readFile(path==='/auth.js'?resolve(root,'scripts/ios-preview-auth.mjs'):file);if(path==='/views.js')body=body.toString()+'\nexport {homeLifePersonMarkup,homeBedForegroundStatusMarkup,roomFurnitureOverlayMarkup};';if(path==='/simulation.js')body=body.toString()+'\nexport {sleepingNow,buildScene};';res.setHeader('Content-Type',({'.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.html':'text/html','.png':'image/png','.svg':'image/svg+xml'})[extname(file)]||'application/octet-stream');res.end(body)}catch{res.writeHead(404).end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const origin=`http://127.0.0.1:${server.address().port}`,engine=process.argv.includes('--webkit')?'webkit':'chromium';const browser=await (engine==='webkit'?webkit.launch({headless:true}):chromium.launch({channel:'chrome',headless:true}));

try{const page=await browser.newPage({viewport:{width:384,height:832},serviceWorkers:'block'});await page.route('**/*',r=>r.request().url().startsWith(origin)?r.continue():r.abort());await page.goto(origin);await page.waitForFunction(()=>window.DrawerVillageNavigation);
 await page.evaluate(async()=>{window.g=await import('/state.js?v=20260909dev305');window.v=await import('/views.js?v=20260909dev305');window.h=await import('/home-editor-ui.js');const id=g.createCharacter();window.c=g.state.characters[id];c.icon='./assets/home-ui/phone.png';c.name='잠자는 캐릭터';document.querySelectorAll('dialog[open]').forEach(d=>d.close());document.body.innerHTML='<main class="home-page"><section class="room" style="position:relative;width:360px;height:660px;--furniture-cell-w:90px;--furniture-cell-h:85px;background:#b99c75"></section></main>';});
 for(const rotation of [0,90,270]){await page.evaluate(rotation=>{const bed={id:'single',item:'1인 침대',x:50,y:45,scale:1,rotation,layer:1},room={name:'침실',furniturePlacements:[bed]},states=new Map([['single','under-cover']]),el=document.querySelector('.room');el.innerHTML=v.roomFurnitureMarkup('h','bedroom',room,false,states)+v.roomFurnitureOverlayMarkup(room,states)+'<div class="room-people has-home-life" style="position:absolute;inset:0">'+v.homeLifePersonMarkup(c,{title:'자는 중',sleeping:true},{phase:'using',furnitureId:'single',item:'1인 침대',x:50,y:45},room,'bedroom',0,0,{bedPlacement:bed,bedState:'under-cover'})+'</div>';},rotation);await page.locator('.couple-bed-base').evaluate(i=>i.decode());await page.evaluate(()=>h.fitCoupleBedOccupants(document));await page.evaluate(()=>new Promise(requestAnimationFrame));const geom=await page.evaluate(()=>{const bed=document.querySelector('.couple-bed-base').getBoundingClientRect(),person=document.querySelector('.home-person-visual').getBoundingClientRect();return {bed:{x:bed.x,y:bed.y,w:bed.width,h:bed.height},person:{x:person.x,y:person.y,w:person.width,h:person.height},base:document.querySelector('.room-furniture-item').querySelectorAll('.couple-bed-quilt').length,overlay:document.querySelectorAll('.room-couple-bed-overlay .couple-bed-quilt').length}});assert.equal(geom.base,0);assert.equal(geom.overlay,1);assert(geom.person.x>=geom.bed.x-5&&geom.person.x<geom.bed.x+geom.bed.w,JSON.stringify(geom));await page.evaluate(()=>document.querySelectorAll('dialog[open]').forEach(d=>d.close()));await page.screenshot({path:out+'/'+engine+'-single-'+rotation+'.png'});}
 const catalog=await page.evaluate(()=>{const home={id:'catalog',rooms:{bedroom:{}}};return h.homeFurnitureDrawer(home,'ko')});assert(catalog.includes('data-home-furniture-category="living"'));assert(catalog.includes('data-home-furniture-category="kitchen"'));assert(!catalog.includes('data-home-furniture-type='));
 console.log('PASS417 single bed shared base/character/quilt pipeline in front/right/left; room-category discovery.');
}finally{await browser.close();server.closeAllConnections();server.close()}
