import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(process.cwd()+'/package.json'),{chromium,webkit}=require('C:/Users/김세은/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=process.cwd();
const server=createServer(async(req,res)=>{try{const p=new URL(req.url,'http://localhost').pathname,f=resolve(root,'.'+(p==='/'?'/index.html':p));let b=await readFile(p==='/auth.js'?resolve('scripts/ios-preview-auth.mjs'):f);if(p==='/app.js')b=Buffer.from(b.toString()+'\nwindow.photoQA={openBuildingShapeDialog,openRoomEditor,cropImage,render};');res.setHeader('Content-Type',({'.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.html':'text/html','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml'})[extname(f)]||'application/octet-stream');res.end(b)}catch{res.writeHead(404).end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const origin=`http://127.0.0.1:${server.address().port}`,browser=await (process.argv.includes('--webkit')?webkit.launch({headless:true}):chromium.launch({channel:'chrome',headless:true}));
try{
 const p=await browser.newPage({viewport:{width:360,height:792},serviceWorkers:'block'}),errors=[];p.setDefaultTimeout(10000);p.on('pageerror',e=>errors.push(e.message));
 await p.addInitScript(()=>window.DRAWER_VILLAGE_ECONOMY_ENABLED=true);
 await p.route('**/*',r=>(r.request().url().startsWith(origin)||/^(blob:|data:)/.test(r.request().url()))?r.continue():r.abort());
 await p.goto(origin+'/?native-preview=1');await p.waitForFunction(()=>window.photoQA);
 await p.evaluate(async()=>{window.g=await import('/state.js?v=20260909dev305');window.career=await import('/career-ui.js');document.querySelector('.drawer-title')?.remove();document.documentElement.classList.remove('title-visible');g.state.activeId=g.createCharacter();window.DrawerVillageNavigation.go('observe');document.querySelectorAll('dialog[open]').forEach(d=>d.close());window.photoQA.render()});
 await p.addLocatorHandler(p.locator('dialog.page-guide[open]'),async()=>p.locator('dialog.page-guide[open]').evaluate(d=>d.close()));

 await p.evaluate(async()=>{window.food=await import('/prepared-food.js');window.cook=await import('/cooking-ui.js');window.recipes=(await import('/recipes.js')).RECIPES;window.dashboard=await import('/career-dashboard.js');window.money=await import('/character-money.js');window.salary=await import('/salary.js');const c=g.state.characters[g.state.activeId];money.ensureWallet(c);salary.assignEmployment(g.state,c,'builtin-office','rank-1',Date.now(),money.moneyEntry,{frequency:'weekly'});g.state.routines[c.id]=[{id:'shift',type:'업무',day:new Date().getDay(),start:'17:00',end:'00:00'}];dashboard.openCareerDashboard(g.state,c)});
 await p.getByRole('heading',{name:'출근 일정',exact:true}).waitFor();assert.equal(await p.locator('.career-weekdays .scheduled').count(),1);assert.match(await p.locator('.career-dashboard').innerText(),/주급/);await p.waitForTimeout(350);await p.screenshot({path:'tmp/career-dashboard476.png'});
 await p.getByRole('button',{name:'직업 설정 · 전체설정 3페이지',exact:true}).click();await p.getByLabel('직업 종류',{exact:true}).waitFor();const position=await p.getByLabel('직업 종류',{exact:true}).boundingBox();assert(position.y<600);await p.waitForTimeout(350);await p.screenshot({path:'tmp/career-book476.png'});
 await p.evaluate(()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close());cook.openCooking(g.state.activeId)});assert.equal(await p.locator('option[value="fantasy"]').count(),0);assert.equal(await p.locator('option[value="medieval"]').count(),0);assert.equal(await p.locator('[data-recipe-id^="fantasy"]').count(),0);await p.screenshot({path:'tmp/cooking476.png'});
 await p.evaluate(async()=>{document.querySelector('.cooking-dialog').close();const c=g.state.characters[g.state.activeId],home=g.state.homes[c.homeId];const room=Object.entries(home.rooms).find(([key,r])=>(r.type||key)==='kitchen');room[1].furniturePlacements??=[];room[1].furniturePlacements.push({id:'fridge-test',item:'냉장고',x:10,y:60});c.cooking??={inventory:{}};c.cooking.inventory??={};const recipe=recipes.find(r=>r.cuisine==='korean');c.cooking.inventory[recipe.id]=1;food.placeCookedFood(g.state,c,{id:'test-dish',recipeId:recipe.id,homeId:home.id,room:room[0],endsAt:Date.now()});g.state.activeHomeId=home.id;window.DrawerVillageNavigation.go('home');window.photoQA.render()});
 await p.locator('[data-prepared-food="test-dish"]').waitFor();await p.waitForTimeout(350);await p.screenshot({path:'tmp/food-home476.png'});await p.locator('[data-prepared-food="test-dish"]').click();await p.getByRole('button',{name:'냉장고에 넣기',exact:true}).click();await p.waitForFunction(()=>g.state.characters[g.state.activeId].cooking.dishes[0].storage==='fridge');
 await p.evaluate(()=>cook.openCooking(g.state.activeId));await p.locator('[data-prepared-food="test-dish"]').click();await p.getByRole('button',{name:'먹기',exact:true}).click();await p.waitForFunction(()=>g.state.characters[g.state.activeId].cooking.dishes.length===0);
 await p.evaluate(async()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close());const life=await import('/life-settings.js');const d=document.createElement('dialog');d.className='career-dialog';d.append(life.lifeSettingsFields(g.state.characters[g.state.activeId],'ko').root);document.body.append(d);d.showModal()});await p.getByLabel('허기 빈도',{exact:true}).selectOption('0.25');await p.screenshot({path:'tmp/needs476.png'});

 await p.evaluate(()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close());const c=g.state.characters[g.state.activeId],stamp=Date.now(),home=g.state.homes[c.homeId],room=Object.keys(home.rooms).find(k=>home.rooms[k].type==='bath'||k==='bath');Object.assign(c,{wake:'00:00',sleep:'00:00',lifeNeeds:{sleep:90,hunger:90,toilet:0,hygiene:90,social:90,updatedAt:stamp}});g.state.routines[c.id]=[];g.directCharacterActivity(c.id,'wash',{lifeTask:'toilet',now:stamp,scenes:{[c.id]:{home:true,room,visitHomeId:c.homeId}}});const d=g.state.characterDirectives[c.id];d.journey.segments=[];d.journey.arrivesAt=stamp;d.endsAt=stamp+10000;window.DrawerVillageNavigation.go('home');window.photoQA.render()});
 await p.getByRole('progressbar',{name:'활동 진행률'}).first().waitFor();await p.waitForTimeout(1200);const value=Number(await p.getByRole('progressbar',{name:'활동 진행률'}).first().getAttribute('aria-valuenow'));assert(value>=8&&value<60);await p.screenshot({path:'tmp/progress476.png'});await p.waitForTimeout(10000);assert.equal(await p.getByRole('progressbar',{name:'활동 진행률'}).count(),0);
 for(const [lang,title]of [['en','Work schedule'],['ja','勤務予定']]){await p.evaluate(lang=>{g.state.uiLanguage=lang;dashboard.openCareerDashboard(g.state,g.state.characters[g.state.activeId])},lang);await p.getByRole('heading',{name:title,exact:true}).waitFor();await p.screenshot({path:'tmp/career476-'+lang+'.png'});await p.locator('.career-dashboard').evaluate(d=>d.close())}
 assert.deepEqual(errors,[]);console.log('PASS476 browser: independent dashboard, page3 editor visible, fantasy hidden, food placement/refrigeration/eating, need controls; '+(process.argv.includes('--webkit')?'WebKit':'Chrome'));
}finally{await browser.close();server.close()}
