import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium,webkit}=require('C:/Users/김세은/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=process.cwd(),out=resolve('qa-mail390');await mkdir(out,{recursive:true});
const server=createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname,file=resolve(root,'.'+(path==='/'?'/index.html':path));if(!file.startsWith(root))throw Error();let body=await readFile(path==='/auth.js'?resolve(root,'scripts/ios-preview-auth.mjs'):file);if(path==='/app.js')body=body.toString()+'\nexport {openHomeOccupantSheet};';if(path==='/views.js')body=body.toString()+'\nexport {homeLifePersonMarkup,homeBedForegroundStatusMarkup};';if(path==='/simulation.js')body=body.toString()+'\nexport {sleepingNow,buildScene,sharedFurnitureScene,homeActivityPoolFor};';res.setHeader('Content-Type',({'.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.html':'text/html','.png':'image/png','.svg':'image/svg+xml'})[extname(file)]||'application/octet-stream');res.end(body)}catch{res.writeHead(404).end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const origin=`http://127.0.0.1:${server.address().port}`,engine=process.argv.includes('--webkit')?'webkit':'chromium';const browser=await (engine==='webkit'?webkit.launch({headless:true}):chromium.launch({channel:'chrome',headless:true}));

try{const page=await browser.newPage({viewport:{width:384,height:820},serviceWorkers:'block'});await page.route('**/*',r=>r.request().url().startsWith(origin)?r.continue():r.abort());await page.goto(origin+'/?native-preview=1');await page.waitForFunction(()=>window.DrawerVillageNavigation);await page.evaluate(async()=>{window.g=await import('/state.js?v=20260909dev305');window.rl=await import('/relationship-letters.js');window.vo=await import('/speech-reviewed.js');window.ss=await import('/speech-styles.js?v=20260909dev305');window.a=g.createCharacter(20);window.b=g.createCharacter(20);g.state.characters[a].name='가람';g.state.characters[b].name='나래';g.state.characters[a].speechStyle='경상도 사투리';g.state.characters[a].ageGroup=g.state.characters[b].ageGroup='성인';g.state.relationships={};g.state.relationshipDevelopment={};for(let i=0;i<5;i++)g.recordAutomaticRelationshipMoment([a,b],'friend:'+i,1,false);g.save(true)});
assert.equal(await page.evaluate(()=>Object.keys(g.state.relationships).length),0);assert.equal(await page.evaluate(()=>rl.relationshipLetters(g.state).length),1);
const check=await page.evaluate(()=>{const p=rl.relationshipLetters(g.state)[0];const n=rl.respondRelationshipLetter(g.state,p.id,'later',1000);const pending=p.status==='pending';const done=rl.respondRelationshipLetter(g.state,p.id,'accept');const repeated=rl.respondRelationshipLetter(g.state,p.id,'accept');return {pending,ok:done.ok,repeat:repeated.ok,type:Object.values(g.state.relationships)[0].type}});assert.deepEqual(check,{pending:true,ok:true,repeat:false,type:'친구'});
await page.evaluate(()=>{const c=g.state.characters[a];c.relationshipChangeMode='fixed';const before=JSON.stringify(g.state.relationshipDevelopment);g.recordAutomaticRelationshipMoment([a,b],'locked',1,false);if(before!==JSON.stringify(g.state.relationshipDevelopment))throw Error('Fixed mutated');c.relationshipChangeMode='dynamic';g.updateRelationship(Object.values(g.state.relationships)[0].id,{conflict:85,intimacy:20});const r=Object.values(g.state.relationshipDevelopment)[0];r.metrics.trust=10;g.recordAutomaticRelationshipMoment([a,b],'fight',-1,false,'fight');g.save(true);window.fixture={a,b};});assert.equal(await page.evaluate(()=>rl.relationshipLetters(g.state).at(-1).kind),'절교');
await page.evaluate(()=>window.DrawerVillageNavigation.go('mailbox'));await page.locator('[data-mail-folder="inbox"]').click();await page.evaluate(()=>document.querySelectorAll('dialog[open]').forEach(d=>d.close()));await page.locator('[data-mail-open]').first().click();await page.locator('[data-relationship-reply="decline"]').waitFor();await page.screenshot({path:resolve(out,engine+'-letter.png')});await page.locator('[data-close-mail]').click();assert.equal(await page.evaluate(()=>rl.relationshipLetters(g.state).at(-1).status),'pending');
await page.evaluate(async()=>{window.discovery=await import('/character-discovery.js?v=20260909dev305');window.rules=await import('/character-discovery-rules.js?v=20260909dev305');g.state.activeId=a;const c=g.state.characters[a];c.discovery={lockRevision:333,locks:Object.fromEntries(Object.keys(rules.DISCOVERY_AXES).map(k=>[k,k!=='aggressionLevel']))};window.noise=rules.DISCOVERY_SCENES.find(q=>q.id==='noise');window.lockedBefore={...c};const random=Math.random;Math.random=()=>0.999;discovery.showDiscovery(c,{},noise);Math.random=random});const answer=await page.evaluate(()=>noise.choices[0].text.ko);await page.getByRole('button',{name:answer,exact:true}).click().catch(async()=>{await page.evaluate(()=>document.querySelectorAll('dialog.character-discovery-dialog').forEach(d=>d.close()));await page.evaluate(()=>{const original=Math.random;Math.random=()=>0.999;discovery.showDiscovery(g.state.characters[a],{},noise);Math.random=original});await page.getByRole('button',{name:answer,exact:true}).click()});await page.waitForFunction(()=>g.state.characters[a].discovery.answered?.includes('noise'));assert.equal(await page.evaluate(()=>g.state.characters[a].emotionalSensitivity),await page.evaluate(()=>lockedBefore.emotionalSensitivity));
const checks=await page.evaluate(()=>{for(const style of Object.keys(vo.REVIEWED_STYLE_NAMES))for(const lang of ['ko','en','ja']){if(vo.REVIEWED_LETTERS[style][lang].length!==16||vo.REVIEWED_PUSH[style][lang].length!==22)throw Error('Counts');for(const kind of vo.LETTER_KEYS){const t=vo.relationshipLetterCopy({speechStyle:style},kind,'나래',lang);if(t.includes('{상대}')||!t.includes('나래'))throw Error('Placeholder')}if(!ss.SPEECH_STYLE_OPTIONS.includes(style))throw Error('Missing style')}return true});assert(checks);
await page.reload();await page.waitForFunction(()=>window.DrawerVillageNavigation);const saved=await page.evaluate(async()=>{const g=await import('/state.js?v=20260909dev305'),r=await import('/relationship-letters.js');return {count:r.relationshipLetters(g.state).length,metrics:Object.values(g.state.relationshipDevelopment)[0].metrics}});assert.equal(saved.count,2);assert(saved.metrics.tension>=85);
await page.evaluate(()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close());window.DrawerVillageNavigation.go('character')});await page.locator('.character-quick-choice').waitFor();await page.waitForTimeout(500);await page.evaluate(()=>document.querySelectorAll('dialog[open]').forEach(d=>d.close()));await page.screenshot({path:resolve(out,engine+'-profile.png')});assert(await page.locator('.character-quick-choice').textContent().then(s=>s.includes('처음이라면')));await page.evaluate(()=>window.DrawerVillageNavigation.go('credits'));await page.waitForFunction(()=>document.querySelectorAll('.supporter-name').length===7);await page.screenshot({path:resolve(out,engine+'-credits.png')});
console.log('PASS390: noise locked-answer save, profile emphasis, 7 credits, no automatic relation, pending letter, choices/idempotence, lock, breakup, mailbox close, reload persistence, 570 reviewed lines/3 languages');
}finally{await browser.close();server.close()}
